// Code generated by tools/cmdgen. DO NOT EDIT.

package auto

import "github.com/spf13/cobra"

func GroupActions() *cobra.Command {
	cmd := &cobra.Command{Use: "actions", Short: "Auto-generated commands for actions"}
	cmd.AddCommand(cmdDeleteActionsId())
	cmd.AddCommand(cmdDeleteActionsIdactionReactionsId())
	cmd.AddCommand(cmdGetActionsId())
	cmd.AddCommand(cmdGetActionsIdBoard())
	cmd.AddCommand(cmdGetActionsIdCard())
	cmd.AddCommand(cmdGetActionsIdField())
	cmd.AddCommand(cmdGetActionsIdList())
	cmd.AddCommand(cmdGetActionsIdMember())
	cmd.AddCommand(cmdGetActionsIdMembercreator())
	cmd.AddCommand(cmdGetActionsIdOrganization())
	cmd.AddCommand(cmdGetActionsIdactionReactions())
	cmd.AddCommand(cmdGetActionsIdactionReactionsId())
	cmd.AddCommand(cmdGetActionsIdactionReactionsummary())
	cmd.AddCommand(cmdPostActionsIdactionReactions())
	cmd.AddCommand(cmdPutActionsId())
	cmd.AddCommand(cmdPutActionsIdText())
	return cmd
}

func cmdDeleteActionsId() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "delete-actions-id <id>",
		Short: "Delete an Action",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "DELETE", "/actions/{id}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdDeleteActionsIdactionReactionsId() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "delete-actions-idaction-reactions-id <idAction> <id>",
		Short: "Delete Action's Reaction",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"idAction" + "=" + args[0],
				"id" + "=" + args[1],
			}
			queryVars := []string{}
			return execRaw(cmd, "DELETE", "/actions/{idAction}/reactions/{id}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetActionsId() *cobra.Command {
	var (
		q_display string
		q_entities string
		q_fields string
		q_member string
		q_memberfields string
		q_memberCreator string
		q_memberCreatorfields string
	)
	cmd := &cobra.Command{
		Use:   "get-actions-id <id>",
		Short: "Get an Action",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_display != "" { queryVars = append(queryVars, "display" + "=" + q_display) }
			if q_entities != "" { queryVars = append(queryVars, "entities" + "=" + q_entities) }
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			if q_member != "" { queryVars = append(queryVars, "member" + "=" + q_member) }
			if q_memberfields != "" { queryVars = append(queryVars, "member_fields" + "=" + q_memberfields) }
			if q_memberCreator != "" { queryVars = append(queryVars, "memberCreator" + "=" + q_memberCreator) }
			if q_memberCreatorfields != "" { queryVars = append(queryVars, "memberCreator_fields" + "=" + q_memberCreatorfields) }
			return execRaw(cmd, "GET", "/actions/{id}", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_display, "display", "", "")
	cmd.Flags().StringVar(&q_entities, "entities", "", "")
	cmd.Flags().StringVar(&q_fields, "fields", "", "`all` or a comma-separated list of action [fields](/cloud/trello/guides/rest-...")
	cmd.Flags().StringVar(&q_member, "member", "", "")
	cmd.Flags().StringVar(&q_memberfields, "member_fields", "", "`all` or a comma-separated list of member [fields](/cloud/trello/guides/rest-...")
	cmd.Flags().StringVar(&q_memberCreator, "memberCreator", "", "Whether to include the member object for the creator of the action")
	cmd.Flags().StringVar(&q_memberCreatorfields, "memberCreator_fields", "", "`all` or a comma-separated list of member [fields](/cloud/trello/guides/rest-...")
	return cmd
}

func cmdGetActionsIdBoard() *cobra.Command {
	var (
		q_fields string
	)
	cmd := &cobra.Command{
		Use:   "get-actions-id-board <id>",
		Short: "Get the Board for an Action",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			return execRaw(cmd, "GET", "/actions/{id}/board", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_fields, "fields", "", "`all` or a comma-separated list of board fields")
	return cmd
}

func cmdGetActionsIdCard() *cobra.Command {
	var (
		q_fields string
	)
	cmd := &cobra.Command{
		Use:   "get-actions-id-card <id>",
		Short: "Get the Card for an Action",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			return execRaw(cmd, "GET", "/actions/{id}/card", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_fields, "fields", "", "`all` or a comma-separated list of card fields")
	return cmd
}

func cmdGetActionsIdField() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "get-actions-id-field <id> <field>",
		Short: "Get a specific field on an Action",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"field" + "=" + args[1],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/actions/{id}/{field}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetActionsIdList() *cobra.Command {
	var (
		q_fields string
	)
	cmd := &cobra.Command{
		Use:   "get-actions-id-list <id>",
		Short: "Get the List for an Action",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			return execRaw(cmd, "GET", "/actions/{id}/list", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_fields, "fields", "", "`all` or a comma-separated list of list fields")
	return cmd
}

func cmdGetActionsIdMember() *cobra.Command {
	var (
		q_fields string
	)
	cmd := &cobra.Command{
		Use:   "get-actions-id-member <id>",
		Short: "Get the Member of an Action",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			return execRaw(cmd, "GET", "/actions/{id}/member", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_fields, "fields", "", "`all` or a comma-separated list of member fields")
	return cmd
}

func cmdGetActionsIdMembercreator() *cobra.Command {
	var (
		q_fields string
	)
	cmd := &cobra.Command{
		Use:   "get-actions-id-membercreator <id>",
		Short: "Get the Member Creator of an Action",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			return execRaw(cmd, "GET", "/actions/{id}/memberCreator", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_fields, "fields", "", "`all` or a comma-separated list of member fields")
	return cmd
}

func cmdGetActionsIdOrganization() *cobra.Command {
	var (
		q_fields string
	)
	cmd := &cobra.Command{
		Use:   "get-actions-id-organization <id>",
		Short: "Get the Organization of an Action",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			return execRaw(cmd, "GET", "/actions/{id}/organization", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_fields, "fields", "", "`all` or a comma-separated list of organization fields")
	return cmd
}

func cmdGetActionsIdactionReactions() *cobra.Command {
	var (
		q_member string
		q_emoji string
	)
	cmd := &cobra.Command{
		Use:   "get-actions-idaction-reactions <idAction>",
		Short: "Get Action's Reactions",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"idAction" + "=" + args[0],
			}
			queryVars := []string{}
			if q_member != "" { queryVars = append(queryVars, "member" + "=" + q_member) }
			if q_emoji != "" { queryVars = append(queryVars, "emoji" + "=" + q_emoji) }
			return execRaw(cmd, "GET", "/actions/{idAction}/reactions", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_member, "member", "", "Whether to load the member as a nested resource. See [Members Nested Resource...")
	cmd.Flags().StringVar(&q_emoji, "emoji", "", "Whether to load the emoji as a nested resource.")
	return cmd
}

func cmdGetActionsIdactionReactionsId() *cobra.Command {
	var (
		q_member string
		q_emoji string
	)
	cmd := &cobra.Command{
		Use:   "get-actions-idaction-reactions-id <idAction> <id>",
		Short: "Get Action's Reaction",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"idAction" + "=" + args[0],
				"id" + "=" + args[1],
			}
			queryVars := []string{}
			if q_member != "" { queryVars = append(queryVars, "member" + "=" + q_member) }
			if q_emoji != "" { queryVars = append(queryVars, "emoji" + "=" + q_emoji) }
			return execRaw(cmd, "GET", "/actions/{idAction}/reactions/{id}", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_member, "member", "", "Whether to load the member as a nested resource. See [Members Nested Resource...")
	cmd.Flags().StringVar(&q_emoji, "emoji", "", "Whether to load the emoji as a nested resource.")
	return cmd
}

func cmdGetActionsIdactionReactionsummary() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "get-actions-idaction-reactionsummary <idAction>",
		Short: "List Action's summary of Reactions",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"idAction" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/actions/{idAction}/reactionsSummary", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdPostActionsIdactionReactions() *cobra.Command {
	var (
		dataArg string
	)
	cmd := &cobra.Command{
		Use:   "post-actions-idaction-reactions <idAction>",
		Short: "Create Reaction for Action",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"idAction" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "POST", "/actions/{idAction}/reactions", pathVars, queryVars, dataArg)
		},
	}
	cmd.Flags().StringVar(&dataArg, "data", "", "Request body: literal JSON or @file")
	return cmd
}

func cmdPutActionsId() *cobra.Command {
	var (
		q_text string
	)
	cmd := &cobra.Command{
		Use:   "put-actions-id <id>",
		Short: "Update an Action",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_text != "" { queryVars = append(queryVars, "text" + "=" + q_text) }
			return execRaw(cmd, "PUT", "/actions/{id}", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_text, "text", "", "The new text for the comment")
	return cmd
}

func cmdPutActionsIdText() *cobra.Command {
	var (
		q_value string
	)
	cmd := &cobra.Command{
		Use:   "put-actions-id-text <id>",
		Short: "Update a Comment Action",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_value != "" { queryVars = append(queryVars, "value" + "=" + q_value) }
			return execRaw(cmd, "PUT", "/actions/{id}/text", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_value, "value", "", "The new text for the comment")
	return cmd
}

