// Code generated by tools/cmdgen. DO NOT EDIT.

package auto

import "github.com/spf13/cobra"

func GroupApplications() *cobra.Command {
	cmd := &cobra.Command{Use: "applications", Short: "Auto-generated commands for applications"}
	cmd.AddCommand(cmdApplicationsKeyCompliance())
	return cmd
}

func cmdApplicationsKeyCompliance() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "applications-key-compliance <key>",
		Short: "Get Application's compliance data",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"key" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/applications/{key}/compliance", pathVars, queryVars, "")
		},
	}
	return cmd
}

