// Code generated by tools/cmdgen. DO NOT EDIT.

package auto

import "github.com/spf13/cobra"

// Groups returns all auto-generated resource command groups.
func Groups() []*cobra.Command {
	return []*cobra.Command{
		GroupActions(),
		GroupApplications(),
		GroupBatch(),
		GroupBoards(),
		GroupCards(),
		GroupChecklists(),
		GroupCustomFields(),
		GroupEmoji(),
		GroupEnterprises(),
		GroupLabels(),
		GroupLists(),
		GroupMembers(),
		GroupNotifications(),
		GroupOrganizations(),
		GroupPlugins(),
		GroupSearch(),
		GroupTokens(),
		GroupWebhooks(),
	}
}
