// Code generated by tools/cmdgen. DO NOT EDIT.

package auto

import "github.com/spf13/cobra"

func GroupBatch() *cobra.Command {
	cmd := &cobra.Command{Use: "batch", Short: "Auto-generated commands for batch"}
	cmd.AddCommand(cmdGetBatch())
	return cmd
}

func cmdGetBatch() *cobra.Command {
	var (
		q_urls string
	)
	cmd := &cobra.Command{
		Use:   "get-batch",
		Short: "Batch Requests",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
			}
			queryVars := []string{}
			if q_urls != "" { queryVars = append(queryVars, "urls" + "=" + q_urls) }
			return execRaw(cmd, "GET", "/batch", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_urls, "urls", "", "A list of API routes. Maximum of 10 routes allowed. The routes should begin w...")
	return cmd
}

