// Code generated by tools/cmdgen. DO NOT EDIT.

package auto

import "github.com/spf13/cobra"

func GroupBoards() *cobra.Command {
	cmd := &cobra.Command{Use: "boards", Short: "Auto-generated commands for boards"}
	cmd.AddCommand(cmdBoardsIdChecklists())
	cmd.AddCommand(cmdBoardsidmembersidmember())
	cmd.AddCommand(cmdDeleteBoardsId())
	cmd.AddCommand(cmdDeleteBoardsIdBoardplugins())
	cmd.AddCommand(cmdGetBoardIdPlugins())
	cmd.AddCommand(cmdGetBoardsId())
	cmd.AddCommand(cmdGetBoardsIdActions())
	cmd.AddCommand(cmdGetBoardsIdBoardplugins())
	cmd.AddCommand(cmdGetBoardsIdBoardstars())
	cmd.AddCommand(cmdGetBoardsIdCards())
	cmd.AddCommand(cmdGetBoardsIdCardsFilter())
	cmd.AddCommand(cmdGetBoardsIdCustomfields())
	cmd.AddCommand(cmdGetBoardsIdField())
	cmd.AddCommand(cmdGetBoardsIdLabels())
	cmd.AddCommand(cmdGetBoardsIdLists())
	cmd.AddCommand(cmdGetBoardsIdListsFilter())
	cmd.AddCommand(cmdGetBoardsIdMembers())
	cmd.AddCommand(cmdGetBoardsIdMemberships())
	cmd.AddCommand(cmdPostBoards())
	cmd.AddCommand(cmdPostBoardsIdBoardplugins())
	cmd.AddCommand(cmdPostBoardsIdCalendarkeyGenerate())
	cmd.AddCommand(cmdPostBoardsIdEmailkeyGenerate())
	cmd.AddCommand(cmdPostBoardsIdIdtags())
	cmd.AddCommand(cmdPostBoardsIdLabels())
	cmd.AddCommand(cmdPostBoardsIdLists())
	cmd.AddCommand(cmdPostBoardsIdMarkedasviewed())
	cmd.AddCommand(cmdPutBoardsId())
	cmd.AddCommand(cmdPutBoardsIdMembers())
	cmd.AddCommand(cmdPutBoardsIdMembersIdmember())
	cmd.AddCommand(cmdPutBoardsIdMembershipsIdmembership())
	cmd.AddCommand(cmdPutBoardsIdMyprefsEmailposition())
	cmd.AddCommand(cmdPutBoardsIdMyprefsIdemaillist())
	cmd.AddCommand(cmdPutBoardsIdMyprefsShowsidebar())
	cmd.AddCommand(cmdPutBoardsIdMyprefsShowsidebaractivity())
	cmd.AddCommand(cmdPutBoardsIdMyprefsShowsidebarboardactions())
	cmd.AddCommand(cmdPutBoardsIdMyprefsShowsidebarmembers())
	return cmd
}

func cmdBoardsIdChecklists() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "boards-id-checklists <id>",
		Short: "Get Checklists on a Board",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/boards/{id}/checklists", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdBoardsidmembersidmember() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "boardsidmembersidmember <id> <idMember>",
		Short: "Remove Member from Board",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idMember" + "=" + args[1],
			}
			queryVars := []string{}
			return execRaw(cmd, "DELETE", "/boards/{id}/members/{idMember}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdDeleteBoardsId() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "delete-boards-id <id>",
		Short: "Delete a Board",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "DELETE", "/boards/{id}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdDeleteBoardsIdBoardplugins() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "delete-boards-id-boardplugins <id> <idPlugin>",
		Short: "Disable a Power-Up on a Board",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idPlugin" + "=" + args[1],
			}
			queryVars := []string{}
			return execRaw(cmd, "DELETE", "/boards/{id}/boardPlugins/{idPlugin}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetBoardIdPlugins() *cobra.Command {
	var (
		q_filter string
	)
	cmd := &cobra.Command{
		Use:   "get-board-id-plugins <id>",
		Short: "Get Power-Ups on a Board",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_filter != "" { queryVars = append(queryVars, "filter" + "=" + q_filter) }
			return execRaw(cmd, "GET", "/boards/{id}/plugins", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_filter, "filter", "", "One of: `enabled` or `available`")
	return cmd
}

func cmdGetBoardsId() *cobra.Command {
	var (
		q_actions string
		q_boardStars string
		q_cards string
		q_cardpluginData string
		q_checklists string
		q_customFields string
		q_fields string
		q_labels string
		q_lists string
		q_members string
		q_memberships string
		q_pluginData string
		q_organization string
		q_organizationpluginData string
		q_myPrefs string
		q_tags string
	)
	cmd := &cobra.Command{
		Use:   "get-boards-id <id>",
		Short: "Get a Board",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_actions != "" { queryVars = append(queryVars, "actions" + "=" + q_actions) }
			if q_boardStars != "" { queryVars = append(queryVars, "boardStars" + "=" + q_boardStars) }
			if q_cards != "" { queryVars = append(queryVars, "cards" + "=" + q_cards) }
			if q_cardpluginData != "" { queryVars = append(queryVars, "card_pluginData" + "=" + q_cardpluginData) }
			if q_checklists != "" { queryVars = append(queryVars, "checklists" + "=" + q_checklists) }
			if q_customFields != "" { queryVars = append(queryVars, "customFields" + "=" + q_customFields) }
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			if q_labels != "" { queryVars = append(queryVars, "labels" + "=" + q_labels) }
			if q_lists != "" { queryVars = append(queryVars, "lists" + "=" + q_lists) }
			if q_members != "" { queryVars = append(queryVars, "members" + "=" + q_members) }
			if q_memberships != "" { queryVars = append(queryVars, "memberships" + "=" + q_memberships) }
			if q_pluginData != "" { queryVars = append(queryVars, "pluginData" + "=" + q_pluginData) }
			if q_organization != "" { queryVars = append(queryVars, "organization" + "=" + q_organization) }
			if q_organizationpluginData != "" { queryVars = append(queryVars, "organization_pluginData" + "=" + q_organizationpluginData) }
			if q_myPrefs != "" { queryVars = append(queryVars, "myPrefs" + "=" + q_myPrefs) }
			if q_tags != "" { queryVars = append(queryVars, "tags" + "=" + q_tags) }
			return execRaw(cmd, "GET", "/boards/{id}", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_actions, "actions", "", "This is a nested resource. Read more about actions as nested resources [here]...")
	cmd.Flags().StringVar(&q_boardStars, "boardStars", "", "Valid values are one of: `mine` or `none`.")
	cmd.Flags().StringVar(&q_cards, "cards", "", "This is a nested resource. Read more about cards as nested resources [here](/...")
	cmd.Flags().StringVar(&q_cardpluginData, "card_pluginData", "", "Use with the `cards` param to include card pluginData with the response")
	cmd.Flags().StringVar(&q_checklists, "checklists", "", "This is a nested resource. Read more about checklists as nested resources [he...")
	cmd.Flags().StringVar(&q_customFields, "customFields", "", "This is a nested resource. Read more about custom fields as nested resources ...")
	cmd.Flags().StringVar(&q_fields, "fields", "", "The fields of the board to be included in the response. Valid values: all or ...")
	cmd.Flags().StringVar(&q_labels, "labels", "", "This is a nested resource. Read more about labels as nested resources [here](...")
	cmd.Flags().StringVar(&q_lists, "lists", "", "This is a nested resource. Read more about lists as nested resources [here](/...")
	cmd.Flags().StringVar(&q_members, "members", "", "This is a nested resource. Read more about members as nested resources [here]...")
	cmd.Flags().StringVar(&q_memberships, "memberships", "", "This is a nested resource. Read more about memberships as nested resources [h...")
	cmd.Flags().StringVar(&q_pluginData, "pluginData", "", "Determines whether the pluginData for this board should be returned. Valid va...")
	cmd.Flags().StringVar(&q_organization, "organization", "", "This is a nested resource. Read more about organizations as nested resources ...")
	cmd.Flags().StringVar(&q_organizationpluginData, "organization_pluginData", "", "Use with the `organization` param to include organization pluginData with the...")
	cmd.Flags().StringVar(&q_myPrefs, "myPrefs", "", "")
	cmd.Flags().StringVar(&q_tags, "tags", "", "Also known as collections, tags, refer to the collection(s) that a Board belo...")
	return cmd
}

func cmdGetBoardsIdActions() *cobra.Command {
	var (
		q_fields string
		q_filter string
		q_format string
		q_idModels string
		q_limit string
		q_member string
		q_memberfields string
		q_memberCreator string
		q_memberCreatorfields string
		q_page string
		q_reactions string
		q_before string
		q_since string
	)
	cmd := &cobra.Command{
		Use:   "get-boards-id-actions <boardId>",
		Short: "Get Actions of a Board",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"boardId" + "=" + args[0],
			}
			queryVars := []string{}
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			if q_filter != "" { queryVars = append(queryVars, "filter" + "=" + q_filter) }
			if q_format != "" { queryVars = append(queryVars, "format" + "=" + q_format) }
			if q_idModels != "" { queryVars = append(queryVars, "idModels" + "=" + q_idModels) }
			if q_limit != "" { queryVars = append(queryVars, "limit" + "=" + q_limit) }
			if q_member != "" { queryVars = append(queryVars, "member" + "=" + q_member) }
			if q_memberfields != "" { queryVars = append(queryVars, "member_fields" + "=" + q_memberfields) }
			if q_memberCreator != "" { queryVars = append(queryVars, "memberCreator" + "=" + q_memberCreator) }
			if q_memberCreatorfields != "" { queryVars = append(queryVars, "memberCreator_fields" + "=" + q_memberCreatorfields) }
			if q_page != "" { queryVars = append(queryVars, "page" + "=" + q_page) }
			if q_reactions != "" { queryVars = append(queryVars, "reactions" + "=" + q_reactions) }
			if q_before != "" { queryVars = append(queryVars, "before" + "=" + q_before) }
			if q_since != "" { queryVars = append(queryVars, "since" + "=" + q_since) }
			return execRaw(cmd, "GET", "/boards/{boardId}/actions", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_fields, "fields", "", "The fields to be returned for the Actions. [See Action fields here](/cloud/tr...")
	cmd.Flags().StringVar(&q_filter, "filter", "", "A comma-separated list of [action types](/cloud/trello/guides/rest-api/action...")
	cmd.Flags().StringVar(&q_format, "format", "", "The format of the returned Actions. Either list or count.")
	cmd.Flags().StringVar(&q_idModels, "idModels", "", "A comma-separated list of idModels. Only actions related to these models will...")
	cmd.Flags().StringVar(&q_limit, "limit", "", "The limit of the number of responses, between 0 and 1000.")
	cmd.Flags().StringVar(&q_member, "member", "", "Whether to return the member object for each action.")
	cmd.Flags().StringVar(&q_memberfields, "member_fields", "", "The fields of the [member](/cloud/trello/guides/rest-api/object-definitions/#...")
	cmd.Flags().StringVar(&q_memberCreator, "memberCreator", "", "Whether to return the memberCreator object for each action.")
	cmd.Flags().StringVar(&q_memberCreatorfields, "memberCreator_fields", "", "The fields of the [member](/cloud/trello/guides/rest-api/object-definitions/#...")
	cmd.Flags().StringVar(&q_page, "page", "", "The page of results for actions.")
	cmd.Flags().StringVar(&q_reactions, "reactions", "", "Whether to show reactions on comments or not.")
	cmd.Flags().StringVar(&q_before, "before", "", "A date string in the form of YYYY-MM-DDThh:mm:ssZ or a mongo object ID. Only ...")
	cmd.Flags().StringVar(&q_since, "since", "", "A date string in the form of YYYY-MM-DDThh:mm:ssZ or a mongo object ID. Only ...")
	return cmd
}

func cmdGetBoardsIdBoardplugins() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "get-boards-id-boardplugins <id>",
		Short: "Get Enabled Power-Ups on Board",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/boards/{id}/boardPlugins", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetBoardsIdBoardstars() *cobra.Command {
	var (
		q_filter string
	)
	cmd := &cobra.Command{
		Use:   "get-boards-id-boardstars <boardId>",
		Short: "Get boardStars on a Board",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"boardId" + "=" + args[0],
			}
			queryVars := []string{}
			if q_filter != "" { queryVars = append(queryVars, "filter" + "=" + q_filter) }
			return execRaw(cmd, "GET", "/boards/{boardId}/boardStars", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_filter, "filter", "", "Valid values: mine, none")
	return cmd
}

func cmdGetBoardsIdCards() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "get-boards-id-cards <id>",
		Short: "Get Cards on a Board",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/boards/{id}/cards", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetBoardsIdCardsFilter() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "get-boards-id-cards-filter <id> <filter>",
		Short: "Get filtered Cards on a Board",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"filter" + "=" + args[1],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/boards/{id}/cards/{filter}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetBoardsIdCustomfields() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "get-boards-id-customfields <id>",
		Short: "Get Custom Fields for Board",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/boards/{id}/customFields", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetBoardsIdField() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "get-boards-id-field <id> <field>",
		Short: "Get a field on a Board",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"field" + "=" + args[1],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/boards/{id}/{field}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetBoardsIdLabels() *cobra.Command {
	var (
		q_fields string
		q_limit string
	)
	cmd := &cobra.Command{
		Use:   "get-boards-id-labels <id>",
		Short: "Get Labels on a Board",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			if q_limit != "" { queryVars = append(queryVars, "limit" + "=" + q_limit) }
			return execRaw(cmd, "GET", "/boards/{id}/labels", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_fields, "fields", "", "The fields to be returned for the Labels.")
	cmd.Flags().StringVar(&q_limit, "limit", "", "The number of Labels to be returned.")
	return cmd
}

func cmdGetBoardsIdLists() *cobra.Command {
	var (
		q_cards string
		q_cardfields string
		q_filter string
		q_fields string
	)
	cmd := &cobra.Command{
		Use:   "get-boards-id-lists <id>",
		Short: "Get Lists on a Board",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_cards != "" { queryVars = append(queryVars, "cards" + "=" + q_cards) }
			if q_cardfields != "" { queryVars = append(queryVars, "card_fields" + "=" + q_cardfields) }
			if q_filter != "" { queryVars = append(queryVars, "filter" + "=" + q_filter) }
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			return execRaw(cmd, "GET", "/boards/{id}/lists", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_cards, "cards", "", "Filter to apply to Cards.")
	cmd.Flags().StringVar(&q_cardfields, "card_fields", "", "`all` or a comma-separated list of card [fields](/cloud/trello/guides/rest-ap...")
	cmd.Flags().StringVar(&q_filter, "filter", "", "Filter to apply to Lists")
	cmd.Flags().StringVar(&q_fields, "fields", "", "`all` or a comma-separated list of list [fields](/cloud/trello/guides/rest-ap...")
	return cmd
}

func cmdGetBoardsIdListsFilter() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "get-boards-id-lists-filter <id> <filter>",
		Short: "Get filtered Lists on a Board",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"filter" + "=" + args[1],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/boards/{id}/lists/{filter}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetBoardsIdMembers() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "get-boards-id-members <id>",
		Short: "Get the Members of a Board",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/boards/{id}/members", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetBoardsIdMemberships() *cobra.Command {
	var (
		q_filter string
		q_activity string
		q_orgMemberType string
		q_member string
		q_memberfields string
	)
	cmd := &cobra.Command{
		Use:   "get-boards-id-memberships <id>",
		Short: "Get Memberships of a Board",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_filter != "" { queryVars = append(queryVars, "filter" + "=" + q_filter) }
			if q_activity != "" { queryVars = append(queryVars, "activity" + "=" + q_activity) }
			if q_orgMemberType != "" { queryVars = append(queryVars, "orgMemberType" + "=" + q_orgMemberType) }
			if q_member != "" { queryVars = append(queryVars, "member" + "=" + q_member) }
			if q_memberfields != "" { queryVars = append(queryVars, "member_fields" + "=" + q_memberfields) }
			return execRaw(cmd, "GET", "/boards/{id}/memberships", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_filter, "filter", "", "One of `admins`, `all`, `none`, `normal`")
	cmd.Flags().StringVar(&q_activity, "activity", "", "Works for premium organizations only.")
	cmd.Flags().StringVar(&q_orgMemberType, "orgMemberType", "", "Shows the type of member to the org the user is. For instance, an org admin w...")
	cmd.Flags().StringVar(&q_member, "member", "", "Determines whether to include a [nested member object](/cloud/trello/guides/r...")
	cmd.Flags().StringVar(&q_memberfields, "member_fields", "", "Fields to show if `member=true`. Valid values: [nested member resource fields...")
	return cmd
}

func cmdPostBoards() *cobra.Command {
	var (
		q_name string
		q_defaultLabels string
		q_defaultLists string
		q_desc string
		q_idOrganization string
		q_idBoardSource string
		q_keepFromSource string
		q_powerUps string
		q_prefspermissionLevel string
		q_prefsvoting string
		q_prefscomments string
		q_prefsinvitations string
		q_prefsselfJoin string
		q_prefscardCovers string
		q_prefsbackground string
		q_prefscardAging string
	)
	cmd := &cobra.Command{
		Use:   "post-boards",
		Short: "Create a Board",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
			}
			queryVars := []string{}
			if q_name != "" { queryVars = append(queryVars, "name" + "=" + q_name) }
			if q_defaultLabels != "" { queryVars = append(queryVars, "defaultLabels" + "=" + q_defaultLabels) }
			if q_defaultLists != "" { queryVars = append(queryVars, "defaultLists" + "=" + q_defaultLists) }
			if q_desc != "" { queryVars = append(queryVars, "desc" + "=" + q_desc) }
			if q_idOrganization != "" { queryVars = append(queryVars, "idOrganization" + "=" + q_idOrganization) }
			if q_idBoardSource != "" { queryVars = append(queryVars, "idBoardSource" + "=" + q_idBoardSource) }
			if q_keepFromSource != "" { queryVars = append(queryVars, "keepFromSource" + "=" + q_keepFromSource) }
			if q_powerUps != "" { queryVars = append(queryVars, "powerUps" + "=" + q_powerUps) }
			if q_prefspermissionLevel != "" { queryVars = append(queryVars, "prefs_permissionLevel" + "=" + q_prefspermissionLevel) }
			if q_prefsvoting != "" { queryVars = append(queryVars, "prefs_voting" + "=" + q_prefsvoting) }
			if q_prefscomments != "" { queryVars = append(queryVars, "prefs_comments" + "=" + q_prefscomments) }
			if q_prefsinvitations != "" { queryVars = append(queryVars, "prefs_invitations" + "=" + q_prefsinvitations) }
			if q_prefsselfJoin != "" { queryVars = append(queryVars, "prefs_selfJoin" + "=" + q_prefsselfJoin) }
			if q_prefscardCovers != "" { queryVars = append(queryVars, "prefs_cardCovers" + "=" + q_prefscardCovers) }
			if q_prefsbackground != "" { queryVars = append(queryVars, "prefs_background" + "=" + q_prefsbackground) }
			if q_prefscardAging != "" { queryVars = append(queryVars, "prefs_cardAging" + "=" + q_prefscardAging) }
			return execRaw(cmd, "POST", "/boards/", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_name, "name", "", "The new name for the board. 1 to 16384 characters long.")
	cmd.Flags().StringVar(&q_defaultLabels, "defaultLabels", "", "Determines whether to use the default set of labels.")
	cmd.Flags().StringVar(&q_defaultLists, "defaultLists", "", "Determines whether to add the default set of lists to a board (To Do, Doing, ...")
	cmd.Flags().StringVar(&q_desc, "desc", "", "A new description for the board, 0 to 16384 characters long")
	cmd.Flags().StringVar(&q_idOrganization, "idOrganization", "", "The id or name of the Workspace the board should belong to.")
	cmd.Flags().StringVar(&q_idBoardSource, "idBoardSource", "", "The id of a board to copy into the new board.")
	cmd.Flags().StringVar(&q_keepFromSource, "keepFromSource", "", "To keep cards from the original board pass in the value `cards`")
	cmd.Flags().StringVar(&q_powerUps, "powerUps", "", "The Power-Ups that should be enabled on the new board. One of: `all`, `calend...")
	cmd.Flags().StringVar(&q_prefspermissionLevel, "prefs_permissionLevel", "", "The permissions level of the board. One of: `org`, `private`, `public`.")
	cmd.Flags().StringVar(&q_prefsvoting, "prefs_voting", "", "Who can vote on this board. One of `disabled`, `members`, `observers`, `org`,...")
	cmd.Flags().StringVar(&q_prefscomments, "prefs_comments", "", "Who can comment on cards on this board. One of: `disabled`, `members`, `obser...")
	cmd.Flags().StringVar(&q_prefsinvitations, "prefs_invitations", "", "Determines what types of members can invite users to join. One of: `admins`, ...")
	cmd.Flags().StringVar(&q_prefsselfJoin, "prefs_selfJoin", "", "Determines whether users can join the boards themselves or whether they have ...")
	cmd.Flags().StringVar(&q_prefscardCovers, "prefs_cardCovers", "", "Determines whether card covers are enabled.")
	cmd.Flags().StringVar(&q_prefsbackground, "prefs_background", "", "The id of a custom background or one of: `blue`, `orange`, `green`, `red`, `p...")
	cmd.Flags().StringVar(&q_prefscardAging, "prefs_cardAging", "", "Determines the type of card aging that should take place on the board if card...")
	return cmd
}

func cmdPostBoardsIdBoardplugins() *cobra.Command {
	var (
		q_idPlugin string
	)
	cmd := &cobra.Command{
		Use:   "post-boards-id-boardplugins <id>",
		Short: "Enable a Power-Up on a Board",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_idPlugin != "" { queryVars = append(queryVars, "idPlugin" + "=" + q_idPlugin) }
			return execRaw(cmd, "POST", "/boards/{id}/boardPlugins", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_idPlugin, "idPlugin", "", "The ID of the Power-Up to enable")
	return cmd
}

func cmdPostBoardsIdCalendarkeyGenerate() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "post-boards-id-calendarkey-generate <id>",
		Short: "Create a calendarKey for a Board",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "POST", "/boards/{id}/calendarKey/generate", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdPostBoardsIdEmailkeyGenerate() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "post-boards-id-emailkey-generate <id>",
		Short: "Create a emailKey for a Board",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "POST", "/boards/{id}/emailKey/generate", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdPostBoardsIdIdtags() *cobra.Command {
	var (
		q_value string
	)
	cmd := &cobra.Command{
		Use:   "post-boards-id-idtags <id>",
		Short: "Create a Tag for a Board",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_value != "" { queryVars = append(queryVars, "value" + "=" + q_value) }
			return execRaw(cmd, "POST", "/boards/{id}/idTags", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_value, "value", "", "The id of a tag from the organization to which this board belongs.")
	return cmd
}

func cmdPostBoardsIdLabels() *cobra.Command {
	var (
		q_name string
		q_color string
	)
	cmd := &cobra.Command{
		Use:   "post-boards-id-labels <id>",
		Short: "Create a Label on a Board",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_name != "" { queryVars = append(queryVars, "name" + "=" + q_name) }
			if q_color != "" { queryVars = append(queryVars, "color" + "=" + q_color) }
			return execRaw(cmd, "POST", "/boards/{id}/labels", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_name, "name", "", "The name of the label to be created. 1 to 16384 characters long.")
	cmd.Flags().StringVar(&q_color, "color", "", "Sets the color of the new label. Valid values are a label color or `null`.")
	return cmd
}

func cmdPostBoardsIdLists() *cobra.Command {
	var (
		q_name string
		q_pos string
	)
	cmd := &cobra.Command{
		Use:   "post-boards-id-lists <id>",
		Short: "Create a List on a Board",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_name != "" { queryVars = append(queryVars, "name" + "=" + q_name) }
			if q_pos != "" { queryVars = append(queryVars, "pos" + "=" + q_pos) }
			return execRaw(cmd, "POST", "/boards/{id}/lists", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_name, "name", "", "The name of the list to be created. 1 to 16384 characters long.")
	cmd.Flags().StringVar(&q_pos, "pos", "", "Determines the position of the list. Valid values: `top`, `bottom`, or a posi...")
	return cmd
}

func cmdPostBoardsIdMarkedasviewed() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "post-boards-id-markedasviewed <id>",
		Short: "Mark Board as viewed",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "POST", "/boards/{id}/markedAsViewed", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdPutBoardsId() *cobra.Command {
	var (
		q_name string
		q_desc string
		q_closed string
		q_subscribed string
		q_idOrganization string
		q_prefspermissionLevel string
		q_prefsselfJoin string
		q_prefscardCovers string
		q_prefshideVotes string
		q_prefsinvitations string
		q_prefsvoting string
		q_prefscomments string
		q_prefsbackground string
		q_prefscardAging string
		q_prefscalendarFeedEnabled string
	)
	cmd := &cobra.Command{
		Use:   "put-boards-id <id>",
		Short: "Update a Board",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_name != "" { queryVars = append(queryVars, "name" + "=" + q_name) }
			if q_desc != "" { queryVars = append(queryVars, "desc" + "=" + q_desc) }
			if q_closed != "" { queryVars = append(queryVars, "closed" + "=" + q_closed) }
			if q_subscribed != "" { queryVars = append(queryVars, "subscribed" + "=" + q_subscribed) }
			if q_idOrganization != "" { queryVars = append(queryVars, "idOrganization" + "=" + q_idOrganization) }
			if q_prefspermissionLevel != "" { queryVars = append(queryVars, "prefs/permissionLevel" + "=" + q_prefspermissionLevel) }
			if q_prefsselfJoin != "" { queryVars = append(queryVars, "prefs/selfJoin" + "=" + q_prefsselfJoin) }
			if q_prefscardCovers != "" { queryVars = append(queryVars, "prefs/cardCovers" + "=" + q_prefscardCovers) }
			if q_prefshideVotes != "" { queryVars = append(queryVars, "prefs/hideVotes" + "=" + q_prefshideVotes) }
			if q_prefsinvitations != "" { queryVars = append(queryVars, "prefs/invitations" + "=" + q_prefsinvitations) }
			if q_prefsvoting != "" { queryVars = append(queryVars, "prefs/voting" + "=" + q_prefsvoting) }
			if q_prefscomments != "" { queryVars = append(queryVars, "prefs/comments" + "=" + q_prefscomments) }
			if q_prefsbackground != "" { queryVars = append(queryVars, "prefs/background" + "=" + q_prefsbackground) }
			if q_prefscardAging != "" { queryVars = append(queryVars, "prefs/cardAging" + "=" + q_prefscardAging) }
			if q_prefscalendarFeedEnabled != "" { queryVars = append(queryVars, "prefs/calendarFeedEnabled" + "=" + q_prefscalendarFeedEnabled) }
			return execRaw(cmd, "PUT", "/boards/{id}", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_name, "name", "", "The new name for the board. 1 to 16384 characters long.")
	cmd.Flags().StringVar(&q_desc, "desc", "", "A new description for the board, 0 to 16384 characters long")
	cmd.Flags().StringVar(&q_closed, "closed", "", "Whether the board is closed")
	cmd.Flags().StringVar(&q_subscribed, "subscribed", "", "Whether the acting user is subscribed to the board")
	cmd.Flags().StringVar(&q_idOrganization, "idOrganization", "", "The id of the Workspace the board should be moved to")
	cmd.Flags().StringVar(&q_prefspermissionLevel, "prefs/permissionLevel", "", "One of: org, private, public")
	cmd.Flags().StringVar(&q_prefsselfJoin, "prefs/selfJoin", "", "Whether Workspace members can join the board themselves")
	cmd.Flags().StringVar(&q_prefscardCovers, "prefs/cardCovers", "", "Whether card covers should be displayed on this board")
	cmd.Flags().StringVar(&q_prefshideVotes, "prefs/hideVotes", "", "Determines whether the Voting Power-Up should hide who voted on cards or not.")
	cmd.Flags().StringVar(&q_prefsinvitations, "prefs/invitations", "", "Who can invite people to this board. One of: admins, members")
	cmd.Flags().StringVar(&q_prefsvoting, "prefs/voting", "", "Who can vote on this board. One of disabled, members, observers, org, public")
	cmd.Flags().StringVar(&q_prefscomments, "prefs/comments", "", "Who can comment on cards on this board. One of: disabled, members, observers,...")
	cmd.Flags().StringVar(&q_prefsbackground, "prefs/background", "", "The id of a custom background or one of: blue, orange, green, red, purple, pi...")
	cmd.Flags().StringVar(&q_prefscardAging, "prefs/cardAging", "", "One of: pirate, regular")
	cmd.Flags().StringVar(&q_prefscalendarFeedEnabled, "prefs/calendarFeedEnabled", "", "Determines whether the calendar feed is enabled or not.")
	return cmd
}

func cmdPutBoardsIdMembers() *cobra.Command {
	var (
		q_email string
		q_type string
		dataArg string
	)
	cmd := &cobra.Command{
		Use:   "put-boards-id-members <id>",
		Short: "Invite Member to Board via email",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_email != "" { queryVars = append(queryVars, "email" + "=" + q_email) }
			if q_type != "" { queryVars = append(queryVars, "type" + "=" + q_type) }
			return execRaw(cmd, "PUT", "/boards/{id}/members", pathVars, queryVars, dataArg)
		},
	}
	cmd.Flags().StringVar(&q_email, "email", "", "The email address of a user to add as a member of the board.")
	cmd.Flags().StringVar(&q_type, "type", "", "Valid values: admin, normal, observer. Determines what type of member the use...")
	cmd.Flags().StringVar(&dataArg, "data", "", "Request body: literal JSON or @file")
	return cmd
}

func cmdPutBoardsIdMembersIdmember() *cobra.Command {
	var (
		q_type string
		q_allowBillableGuest string
	)
	cmd := &cobra.Command{
		Use:   "put-boards-id-members-idmember <id> <idMember>",
		Short: "Add a Member to a Board",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idMember" + "=" + args[1],
			}
			queryVars := []string{}
			if q_type != "" { queryVars = append(queryVars, "type" + "=" + q_type) }
			if q_allowBillableGuest != "" { queryVars = append(queryVars, "allowBillableGuest" + "=" + q_allowBillableGuest) }
			return execRaw(cmd, "PUT", "/boards/{id}/members/{idMember}", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_type, "type", "", "One of: admin, normal, observer. Determines the type of member this user will...")
	cmd.Flags().StringVar(&q_allowBillableGuest, "allowBillableGuest", "", "Optional param that allows organization admins to add multi-board guests onto...")
	return cmd
}

func cmdPutBoardsIdMembershipsIdmembership() *cobra.Command {
	var (
		q_type string
		q_memberfields string
	)
	cmd := &cobra.Command{
		Use:   "put-boards-id-memberships-idmembership <id> <idMembership>",
		Short: "Update Membership of Member on a Board",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idMembership" + "=" + args[1],
			}
			queryVars := []string{}
			if q_type != "" { queryVars = append(queryVars, "type" + "=" + q_type) }
			if q_memberfields != "" { queryVars = append(queryVars, "member_fields" + "=" + q_memberfields) }
			return execRaw(cmd, "PUT", "/boards/{id}/memberships/{idMembership}", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_type, "type", "", "One of: admin, normal, observer. Determines the type of member that this memb...")
	cmd.Flags().StringVar(&q_memberfields, "member_fields", "", "Valid values: all, avatarHash, bio, bioData, confirmed, fullName, idPremOrgsA...")
	return cmd
}

func cmdPutBoardsIdMyprefsEmailposition() *cobra.Command {
	var (
		q_value string
	)
	cmd := &cobra.Command{
		Use:   "put-boards-id-myprefs-emailposition <id>",
		Short: "Update emailPosition Pref on a Board",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_value != "" { queryVars = append(queryVars, "value" + "=" + q_value) }
			return execRaw(cmd, "PUT", "/boards/{id}/myPrefs/emailPosition", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_value, "value", "", "Valid values: bottom, top. Determines the position of the email address.")
	return cmd
}

func cmdPutBoardsIdMyprefsIdemaillist() *cobra.Command {
	var (
		q_value string
	)
	cmd := &cobra.Command{
		Use:   "put-boards-id-myprefs-idemaillist <id>",
		Short: "Update idEmailList Pref on a Board",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_value != "" { queryVars = append(queryVars, "value" + "=" + q_value) }
			return execRaw(cmd, "PUT", "/boards/{id}/myPrefs/idEmailList", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_value, "value", "", "The id of an email list.")
	return cmd
}

func cmdPutBoardsIdMyprefsShowsidebar() *cobra.Command {
	var (
		q_value string
	)
	cmd := &cobra.Command{
		Use:   "put-boards-id-myprefs-showsidebar <id>",
		Short: "Update showSidebar Pref on a Board",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_value != "" { queryVars = append(queryVars, "value" + "=" + q_value) }
			return execRaw(cmd, "PUT", "/boards/{id}/myPrefs/showSidebar", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_value, "value", "", "Determines whether to show the side bar.")
	return cmd
}

func cmdPutBoardsIdMyprefsShowsidebaractivity() *cobra.Command {
	var (
		q_value string
	)
	cmd := &cobra.Command{
		Use:   "put-boards-id-myprefs-showsidebaractivity <id>",
		Short: "Update showSidebarActivity Pref on a Board",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_value != "" { queryVars = append(queryVars, "value" + "=" + q_value) }
			return execRaw(cmd, "PUT", "/boards/{id}/myPrefs/showSidebarActivity", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_value, "value", "", "Determines whether to show sidebar activity.")
	return cmd
}

func cmdPutBoardsIdMyprefsShowsidebarboardactions() *cobra.Command {
	var (
		q_value string
	)
	cmd := &cobra.Command{
		Use:   "put-boards-id-myprefs-showsidebarboardactions <id>",
		Short: "Update showSidebarBoardActions Pref on a Board",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_value != "" { queryVars = append(queryVars, "value" + "=" + q_value) }
			return execRaw(cmd, "PUT", "/boards/{id}/myPrefs/showSidebarBoardActions", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_value, "value", "", "Determines whether to show the sidebar board actions.")
	return cmd
}

func cmdPutBoardsIdMyprefsShowsidebarmembers() *cobra.Command {
	var (
		q_value string
	)
	cmd := &cobra.Command{
		Use:   "put-boards-id-myprefs-showsidebarmembers <id>",
		Short: "Update showSidebarMembers Pref on a Board",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_value != "" { queryVars = append(queryVars, "value" + "=" + q_value) }
			return execRaw(cmd, "PUT", "/boards/{id}/myPrefs/showSidebarMembers", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_value, "value", "", "Determines whether to show members of the board in the sidebar.")
	return cmd
}

