// Code generated by tools/cmdgen. DO NOT EDIT.

package auto

import "github.com/spf13/cobra"

func GroupCards() *cobra.Command {
	cmd := &cobra.Command{Use: "cards", Short: "Auto-generated commands for cards"}
	cmd.AddCommand(cmdCardsidmembersvoted1())
	cmd.AddCommand(cmdDeleteCardsId())
	cmd.AddCommand(cmdDeleteCardsIdActionsIdComments())
	cmd.AddCommand(cmdDeleteCardsIdCheckitemIdcheckitem())
	cmd.AddCommand(cmdDeleteCardsIdChecklistsIdchecklist())
	cmd.AddCommand(cmdDeleteCardsIdIdlabelsIdlabel())
	cmd.AddCommand(cmdDeleteCardsIdMembersvotedIdmember())
	cmd.AddCommand(cmdDeleteCardsIdStickersIdsticker())
	cmd.AddCommand(cmdDeleteIdIdmembersIdmember())
	cmd.AddCommand(cmdDeletedCardsIdAttachmentsIdattachment())
	cmd.AddCommand(cmdGetCardsId())
	cmd.AddCommand(cmdGetCardsIdActions())
	cmd.AddCommand(cmdGetCardsIdAttachments())
	cmd.AddCommand(cmdGetCardsIdAttachmentsIdattachment())
	cmd.AddCommand(cmdGetCardsIdBoard())
	cmd.AddCommand(cmdGetCardsIdCheckitemIdcheckitem())
	cmd.AddCommand(cmdGetCardsIdCheckitemstates())
	cmd.AddCommand(cmdGetCardsIdChecklists())
	cmd.AddCommand(cmdGetCardsIdCustomfielditems())
	cmd.AddCommand(cmdGetCardsIdField())
	cmd.AddCommand(cmdGetCardsIdList())
	cmd.AddCommand(cmdGetCardsIdMembers())
	cmd.AddCommand(cmdGetCardsIdMembersvoted())
	cmd.AddCommand(cmdGetCardsIdPlugindata())
	cmd.AddCommand(cmdGetCardsIdStickers())
	cmd.AddCommand(cmdGetCardsIdStickersIdsticker())
	cmd.AddCommand(cmdPostCards())
	cmd.AddCommand(cmdPostCardsIdActionsComments())
	cmd.AddCommand(cmdPostCardsIdAttachments())
	cmd.AddCommand(cmdPostCardsIdChecklists())
	cmd.AddCommand(cmdPostCardsIdIdlabels())
	cmd.AddCommand(cmdPostCardsIdIdmembers())
	cmd.AddCommand(cmdPostCardsIdLabels())
	cmd.AddCommand(cmdPostCardsIdMarkassociatednotificationsread())
	cmd.AddCommand(cmdPostCardsIdStickers())
	cmd.AddCommand(cmdPutCardsId())
	cmd.AddCommand(cmdPutCardsIdActionsIdactionComments())
	cmd.AddCommand(cmdPutCardsIdCheckitemIdcheckitem())
	cmd.AddCommand(cmdPutCardsIdStickersIdsticker())
	cmd.AddCommand(cmdPutCardsIdcardChecklistIdchecklistCheckitemIdcheckitem())
	cmd.AddCommand(cmdPutCardsIdcardCustomfieldIdcustomfieldItem())
	cmd.AddCommand(cmdPutCardsIdcardCustomfields())
	return cmd
}

func cmdCardsidmembersvoted1() *cobra.Command {
	var (
		q_value string
	)
	cmd := &cobra.Command{
		Use:   "cardsidmembersvoted-1 <id>",
		Short: "Add Member vote to Card",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_value != "" { queryVars = append(queryVars, "value" + "=" + q_value) }
			return execRaw(cmd, "POST", "/cards/{id}/membersVoted", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_value, "value", "", "The ID of the member to vote 'yes' on the card")
	return cmd
}

func cmdDeleteCardsId() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "delete-cards-id <id>",
		Short: "Delete a Card",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "DELETE", "/cards/{id}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdDeleteCardsIdActionsIdComments() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "delete-cards-id-actions-id-comments <id> <idAction>",
		Short: "Delete a comment on a Card",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idAction" + "=" + args[1],
			}
			queryVars := []string{}
			return execRaw(cmd, "DELETE", "/cards/{id}/actions/{idAction}/comments", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdDeleteCardsIdCheckitemIdcheckitem() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "delete-cards-id-checkitem-idcheckitem <id> <idCheckItem>",
		Short: "Delete checkItem on a Card",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idCheckItem" + "=" + args[1],
			}
			queryVars := []string{}
			return execRaw(cmd, "DELETE", "/cards/{id}/checkItem/{idCheckItem}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdDeleteCardsIdChecklistsIdchecklist() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "delete-cards-id-checklists-idchecklist <id> <idChecklist>",
		Short: "Delete a Checklist on a Card",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idChecklist" + "=" + args[1],
			}
			queryVars := []string{}
			return execRaw(cmd, "DELETE", "/cards/{id}/checklists/{idChecklist}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdDeleteCardsIdIdlabelsIdlabel() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "delete-cards-id-idlabels-idlabel <id> <idLabel>",
		Short: "Remove a Label from a Card",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idLabel" + "=" + args[1],
			}
			queryVars := []string{}
			return execRaw(cmd, "DELETE", "/cards/{id}/idLabels/{idLabel}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdDeleteCardsIdMembersvotedIdmember() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "delete-cards-id-membersvoted-idmember <id> <idMember>",
		Short: "Remove a Member's Vote on a Card",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idMember" + "=" + args[1],
			}
			queryVars := []string{}
			return execRaw(cmd, "DELETE", "/cards/{id}/membersVoted/{idMember}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdDeleteCardsIdStickersIdsticker() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "delete-cards-id-stickers-idsticker <id> <idSticker>",
		Short: "Delete a Sticker on a Card",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idSticker" + "=" + args[1],
			}
			queryVars := []string{}
			return execRaw(cmd, "DELETE", "/cards/{id}/stickers/{idSticker}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdDeleteIdIdmembersIdmember() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "delete-id-idmembers-idmember <id> <idMember>",
		Short: "Remove a Member from a Card",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idMember" + "=" + args[1],
			}
			queryVars := []string{}
			return execRaw(cmd, "DELETE", "/cards/{id}/idMembers/{idMember}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdDeletedCardsIdAttachmentsIdattachment() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "deleted-cards-id-attachments-idattachment <id> <idAttachment>",
		Short: "Delete an Attachment on a Card",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idAttachment" + "=" + args[1],
			}
			queryVars := []string{}
			return execRaw(cmd, "DELETE", "/cards/{id}/attachments/{idAttachment}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetCardsId() *cobra.Command {
	var (
		q_fields string
		q_actions string
		q_attachments string
		q_attachmentfields string
		q_members string
		q_memberfields string
		q_membersVoted string
		q_memberVotedfields string
		q_checkItemStates string
		q_checklists string
		q_checklistfields string
		q_board string
		q_boardfields string
		q_list string
		q_pluginData string
		q_stickers string
		q_stickerfields string
		q_customFieldItems string
	)
	cmd := &cobra.Command{
		Use:   "get-cards-id <id>",
		Short: "Get a Card",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			if q_actions != "" { queryVars = append(queryVars, "actions" + "=" + q_actions) }
			if q_attachments != "" { queryVars = append(queryVars, "attachments" + "=" + q_attachments) }
			if q_attachmentfields != "" { queryVars = append(queryVars, "attachment_fields" + "=" + q_attachmentfields) }
			if q_members != "" { queryVars = append(queryVars, "members" + "=" + q_members) }
			if q_memberfields != "" { queryVars = append(queryVars, "member_fields" + "=" + q_memberfields) }
			if q_membersVoted != "" { queryVars = append(queryVars, "membersVoted" + "=" + q_membersVoted) }
			if q_memberVotedfields != "" { queryVars = append(queryVars, "memberVoted_fields" + "=" + q_memberVotedfields) }
			if q_checkItemStates != "" { queryVars = append(queryVars, "checkItemStates" + "=" + q_checkItemStates) }
			if q_checklists != "" { queryVars = append(queryVars, "checklists" + "=" + q_checklists) }
			if q_checklistfields != "" { queryVars = append(queryVars, "checklist_fields" + "=" + q_checklistfields) }
			if q_board != "" { queryVars = append(queryVars, "board" + "=" + q_board) }
			if q_boardfields != "" { queryVars = append(queryVars, "board_fields" + "=" + q_boardfields) }
			if q_list != "" { queryVars = append(queryVars, "list" + "=" + q_list) }
			if q_pluginData != "" { queryVars = append(queryVars, "pluginData" + "=" + q_pluginData) }
			if q_stickers != "" { queryVars = append(queryVars, "stickers" + "=" + q_stickers) }
			if q_stickerfields != "" { queryVars = append(queryVars, "sticker_fields" + "=" + q_stickerfields) }
			if q_customFieldItems != "" { queryVars = append(queryVars, "customFieldItems" + "=" + q_customFieldItems) }
			return execRaw(cmd, "GET", "/cards/{id}", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_fields, "fields", "", "`all` or a comma-separated list of [fields](/cloud/trello/guides/rest-api/obj...")
	cmd.Flags().StringVar(&q_actions, "actions", "", "See the [Actions Nested Resource](/cloud/trello/guides/rest-api/nested-resour...")
	cmd.Flags().StringVar(&q_attachments, "attachments", "", "`true`, `false`, or `cover`")
	cmd.Flags().StringVar(&q_attachmentfields, "attachment_fields", "", "`all` or a comma-separated list of attachment [fields](/cloud/trello/guides/r...")
	cmd.Flags().StringVar(&q_members, "members", "", "Whether to return member objects for members on the card")
	cmd.Flags().StringVar(&q_memberfields, "member_fields", "", "`all` or a comma-separated list of member [fields](/cloud/trello/guides/rest-...")
	cmd.Flags().StringVar(&q_membersVoted, "membersVoted", "", "Whether to return member objects for members who voted on the card")
	cmd.Flags().StringVar(&q_memberVotedfields, "memberVoted_fields", "", "`all` or a comma-separated list of member [fields](/cloud/trello/guides/rest-...")
	cmd.Flags().StringVar(&q_checkItemStates, "checkItemStates", "", "")
	cmd.Flags().StringVar(&q_checklists, "checklists", "", "Whether to return the checklists on the card. `all` or `none`")
	cmd.Flags().StringVar(&q_checklistfields, "checklist_fields", "", "`all` or a comma-separated list of `idBoard,idCard,name,pos`")
	cmd.Flags().StringVar(&q_board, "board", "", "Whether to return the board object the card is on")
	cmd.Flags().StringVar(&q_boardfields, "board_fields", "", "`all` or a comma-separated list of board [fields](/cloud/trello/guides/rest-a...")
	cmd.Flags().StringVar(&q_list, "list", "", "See the [Lists Nested Resource](/cloud/trello/guides/rest-api/nested-resources/)")
	cmd.Flags().StringVar(&q_pluginData, "pluginData", "", "Whether to include pluginData on the card with the response")
	cmd.Flags().StringVar(&q_stickers, "stickers", "", "Whether to include sticker models with the response")
	cmd.Flags().StringVar(&q_stickerfields, "sticker_fields", "", "`all` or a comma-separated list of sticker [fields](/cloud/trello/guides/rest...")
	cmd.Flags().StringVar(&q_customFieldItems, "customFieldItems", "", "Whether to include the customFieldItems")
	return cmd
}

func cmdGetCardsIdActions() *cobra.Command {
	var (
		q_filter string
		q_page string
	)
	cmd := &cobra.Command{
		Use:   "get-cards-id-actions <id>",
		Short: "Get Actions on a Card",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_filter != "" { queryVars = append(queryVars, "filter" + "=" + q_filter) }
			if q_page != "" { queryVars = append(queryVars, "page" + "=" + q_page) }
			return execRaw(cmd, "GET", "/cards/{id}/actions", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_filter, "filter", "", "A comma-separated list of [action types](https://developer.atlassian.com/clou...")
	cmd.Flags().StringVar(&q_page, "page", "", "The page of results for actions. Each page of results has 50 actions.")
	return cmd
}

func cmdGetCardsIdAttachments() *cobra.Command {
	var (
		q_fields string
		q_filter string
	)
	cmd := &cobra.Command{
		Use:   "get-cards-id-attachments <id>",
		Short: "Get Attachments on a Card",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			if q_filter != "" { queryVars = append(queryVars, "filter" + "=" + q_filter) }
			return execRaw(cmd, "GET", "/cards/{id}/attachments", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_fields, "fields", "", "`all` or a comma-separated list of attachment [fields](/cloud/trello/guides/r...")
	cmd.Flags().StringVar(&q_filter, "filter", "", "Use `cover` to restrict to just the cover attachment")
	return cmd
}

func cmdGetCardsIdAttachmentsIdattachment() *cobra.Command {
	var (
		q_fields string
	)
	cmd := &cobra.Command{
		Use:   "get-cards-id-attachments-idattachment <id> <idAttachment>",
		Short: "Get an Attachment on a Card",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idAttachment" + "=" + args[1],
			}
			queryVars := []string{}
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			return execRaw(cmd, "GET", "/cards/{id}/attachments/{idAttachment}", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_fields, "fields", "", "The Attachment fields to be included in the response.")
	return cmd
}

func cmdGetCardsIdBoard() *cobra.Command {
	var (
		q_fields string
	)
	cmd := &cobra.Command{
		Use:   "get-cards-id-board <id>",
		Short: "Get the Board the Card is on",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			return execRaw(cmd, "GET", "/cards/{id}/board", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_fields, "fields", "", "`all` or a comma-separated list of board [fields](/cloud/trello/guides/rest-a...")
	return cmd
}

func cmdGetCardsIdCheckitemIdcheckitem() *cobra.Command {
	var (
		q_fields string
	)
	cmd := &cobra.Command{
		Use:   "get-cards-id-checkitem-idcheckitem <id> <idCheckItem>",
		Short: "Get checkItem on a Card",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idCheckItem" + "=" + args[1],
			}
			queryVars := []string{}
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			return execRaw(cmd, "GET", "/cards/{id}/checkItem/{idCheckItem}", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_fields, "fields", "", "`all` or a comma-separated list of `name,nameData,pos,state,type,due,dueRemin...")
	return cmd
}

func cmdGetCardsIdCheckitemstates() *cobra.Command {
	var (
		q_fields string
	)
	cmd := &cobra.Command{
		Use:   "get-cards-id-checkitemstates <id>",
		Short: "Get checkItems on a Card",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			return execRaw(cmd, "GET", "/cards/{id}/checkItemStates", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_fields, "fields", "", "`all` or a comma-separated list of: `idCheckItem`, `state`")
	return cmd
}

func cmdGetCardsIdChecklists() *cobra.Command {
	var (
		q_checkItems string
		q_checkItemfields string
		q_filter string
		q_fields string
	)
	cmd := &cobra.Command{
		Use:   "get-cards-id-checklists <id>",
		Short: "Get Checklists on a Card",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_checkItems != "" { queryVars = append(queryVars, "checkItems" + "=" + q_checkItems) }
			if q_checkItemfields != "" { queryVars = append(queryVars, "checkItem_fields" + "=" + q_checkItemfields) }
			if q_filter != "" { queryVars = append(queryVars, "filter" + "=" + q_filter) }
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			return execRaw(cmd, "GET", "/cards/{id}/checklists", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_checkItems, "checkItems", "", "`all` or `none`")
	cmd.Flags().StringVar(&q_checkItemfields, "checkItem_fields", "", "`all` or a comma-separated list of: `name,nameData,pos,state,type,due,dueRemi...")
	cmd.Flags().StringVar(&q_filter, "filter", "", "`all` or `none`")
	cmd.Flags().StringVar(&q_fields, "fields", "", "`all` or a comma-separated list of: `idBoard,idCard,name,pos`")
	return cmd
}

func cmdGetCardsIdCustomfielditems() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "get-cards-id-customfielditems <id>",
		Short: "Get Custom Field Items for a Card",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/cards/{id}/customFieldItems", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetCardsIdField() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "get-cards-id-field <id> <field>",
		Short: "Get a field on a Card",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"field" + "=" + args[1],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/cards/{id}/{field}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetCardsIdList() *cobra.Command {
	var (
		q_fields string
	)
	cmd := &cobra.Command{
		Use:   "get-cards-id-list <id>",
		Short: "Get the List of a Card",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			return execRaw(cmd, "GET", "/cards/{id}/list", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_fields, "fields", "", "`all` or a comma-separated list of list [fields](/cloud/trello/guides/rest-ap...")
	return cmd
}

func cmdGetCardsIdMembers() *cobra.Command {
	var (
		q_fields string
	)
	cmd := &cobra.Command{
		Use:   "get-cards-id-members <id>",
		Short: "Get the Members of a Card",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			return execRaw(cmd, "GET", "/cards/{id}/members", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_fields, "fields", "", "`all` or a comma-separated list of member [fields](/cloud/trello/guides/rest-...")
	return cmd
}

func cmdGetCardsIdMembersvoted() *cobra.Command {
	var (
		q_fields string
	)
	cmd := &cobra.Command{
		Use:   "get-cards-id-membersvoted <id>",
		Short: "Get Members who have voted on a Card",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			return execRaw(cmd, "GET", "/cards/{id}/membersVoted", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_fields, "fields", "", "`all` or a comma-separated list of member [fields](/cloud/trello/guides/rest-...")
	return cmd
}

func cmdGetCardsIdPlugindata() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "get-cards-id-plugindata <id>",
		Short: "Get pluginData on a Card",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/cards/{id}/pluginData", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetCardsIdStickers() *cobra.Command {
	var (
		q_fields string
	)
	cmd := &cobra.Command{
		Use:   "get-cards-id-stickers <id>",
		Short: "Get Stickers on a Card",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			return execRaw(cmd, "GET", "/cards/{id}/stickers", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_fields, "fields", "", "`all` or a comma-separated list of sticker [fields](/cloud/trello/guides/rest...")
	return cmd
}

func cmdGetCardsIdStickersIdsticker() *cobra.Command {
	var (
		q_fields string
	)
	cmd := &cobra.Command{
		Use:   "get-cards-id-stickers-idsticker <id> <idSticker>",
		Short: "Get a Sticker on a Card",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idSticker" + "=" + args[1],
			}
			queryVars := []string{}
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			return execRaw(cmd, "GET", "/cards/{id}/stickers/{idSticker}", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_fields, "fields", "", "`all` or a comma-separated list of sticker [fields](/cloud/trello/guides/rest...")
	return cmd
}

func cmdPostCards() *cobra.Command {
	var (
		q_name string
		q_desc string
		q_pos string
		q_due string
		q_start string
		q_dueComplete string
		q_idList string
		q_idMembers string
		q_idLabels string
		q_urlSource string
		q_fileSource string
		q_mimeType string
		q_idCardSource string
		q_keepFromSource string
		q_address string
		q_locationName string
		q_coordinates string
		q_cardRole string
	)
	cmd := &cobra.Command{
		Use:   "post-cards",
		Short: "Create a new Card",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
			}
			queryVars := []string{}
			if q_name != "" { queryVars = append(queryVars, "name" + "=" + q_name) }
			if q_desc != "" { queryVars = append(queryVars, "desc" + "=" + q_desc) }
			if q_pos != "" { queryVars = append(queryVars, "pos" + "=" + q_pos) }
			if q_due != "" { queryVars = append(queryVars, "due" + "=" + q_due) }
			if q_start != "" { queryVars = append(queryVars, "start" + "=" + q_start) }
			if q_dueComplete != "" { queryVars = append(queryVars, "dueComplete" + "=" + q_dueComplete) }
			if q_idList != "" { queryVars = append(queryVars, "idList" + "=" + q_idList) }
			if q_idMembers != "" { queryVars = append(queryVars, "idMembers" + "=" + q_idMembers) }
			if q_idLabels != "" { queryVars = append(queryVars, "idLabels" + "=" + q_idLabels) }
			if q_urlSource != "" { queryVars = append(queryVars, "urlSource" + "=" + q_urlSource) }
			if q_fileSource != "" { queryVars = append(queryVars, "fileSource" + "=" + q_fileSource) }
			if q_mimeType != "" { queryVars = append(queryVars, "mimeType" + "=" + q_mimeType) }
			if q_idCardSource != "" { queryVars = append(queryVars, "idCardSource" + "=" + q_idCardSource) }
			if q_keepFromSource != "" { queryVars = append(queryVars, "keepFromSource" + "=" + q_keepFromSource) }
			if q_address != "" { queryVars = append(queryVars, "address" + "=" + q_address) }
			if q_locationName != "" { queryVars = append(queryVars, "locationName" + "=" + q_locationName) }
			if q_coordinates != "" { queryVars = append(queryVars, "coordinates" + "=" + q_coordinates) }
			if q_cardRole != "" { queryVars = append(queryVars, "cardRole" + "=" + q_cardRole) }
			return execRaw(cmd, "POST", "/cards", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_name, "name", "", "The name for the card")
	cmd.Flags().StringVar(&q_desc, "desc", "", "The description for the card")
	cmd.Flags().StringVar(&q_pos, "pos", "", "The position of the new card. `top`, `bottom`, or a positive float")
	cmd.Flags().StringVar(&q_due, "due", "", "A due date for the card")
	cmd.Flags().StringVar(&q_start, "start", "", "The start date of a card, or `null`")
	cmd.Flags().StringVar(&q_dueComplete, "dueComplete", "", "Whether the status of the card is complete")
	cmd.Flags().StringVar(&q_idList, "idList", "", "The ID of the list the card should be created in")
	cmd.Flags().StringVar(&q_idMembers, "idMembers", "", "Comma-separated list of member IDs to add to the card")
	cmd.Flags().StringVar(&q_idLabels, "idLabels", "", "Comma-separated list of label IDs to add to the card")
	cmd.Flags().StringVar(&q_urlSource, "urlSource", "", "A URL starting with `http://` or `https://`. The URL will be attached to the ...")
	cmd.Flags().StringVar(&q_fileSource, "fileSource", "", "")
	cmd.Flags().StringVar(&q_mimeType, "mimeType", "", "The mimeType of the attachment. Max length 256")
	cmd.Flags().StringVar(&q_idCardSource, "idCardSource", "", "The ID of a card to copy into the new card")
	cmd.Flags().StringVar(&q_keepFromSource, "keepFromSource", "", "If using `idCardSource` you can specify which properties to copy over. `all` ...")
	cmd.Flags().StringVar(&q_address, "address", "", "For use with/by the Map View")
	cmd.Flags().StringVar(&q_locationName, "locationName", "", "For use with/by the Map View")
	cmd.Flags().StringVar(&q_coordinates, "coordinates", "", "For use with/by the Map View. Should take the form latitude,longitude")
	cmd.Flags().StringVar(&q_cardRole, "cardRole", "", "For displaying cards in different ways based on the card name. Board cards mu...")
	return cmd
}

func cmdPostCardsIdActionsComments() *cobra.Command {
	var (
		q_text string
	)
	cmd := &cobra.Command{
		Use:   "post-cards-id-actions-comments <id>",
		Short: "Add a new comment to a Card",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_text != "" { queryVars = append(queryVars, "text" + "=" + q_text) }
			return execRaw(cmd, "POST", "/cards/{id}/actions/comments", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_text, "text", "", "The comment")
	return cmd
}

func cmdPostCardsIdAttachments() *cobra.Command {
	var (
		q_name string
		q_file string
		q_mimeType string
		q_url string
		q_setCover string
	)
	cmd := &cobra.Command{
		Use:   "post-cards-id-attachments <id>",
		Short: "Create Attachment On Card",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_name != "" { queryVars = append(queryVars, "name" + "=" + q_name) }
			if q_file != "" { queryVars = append(queryVars, "file" + "=" + q_file) }
			if q_mimeType != "" { queryVars = append(queryVars, "mimeType" + "=" + q_mimeType) }
			if q_url != "" { queryVars = append(queryVars, "url" + "=" + q_url) }
			if q_setCover != "" { queryVars = append(queryVars, "setCover" + "=" + q_setCover) }
			return execRaw(cmd, "POST", "/cards/{id}/attachments", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_name, "name", "", "The name of the attachment. Max length 256.")
	cmd.Flags().StringVar(&q_file, "file", "", "The file to attach, as multipart/form-data")
	cmd.Flags().StringVar(&q_mimeType, "mimeType", "", "The mimeType of the attachment. Max length 256")
	cmd.Flags().StringVar(&q_url, "url", "", "A URL to attach. Must start with `http://` or `https://`")
	cmd.Flags().StringVar(&q_setCover, "setCover", "", "Determines whether to use the new attachment as a cover for the Card.")
	return cmd
}

func cmdPostCardsIdChecklists() *cobra.Command {
	var (
		q_name string
		q_idChecklistSource string
		q_pos string
	)
	cmd := &cobra.Command{
		Use:   "post-cards-id-checklists <id>",
		Short: "Create Checklist on a Card",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_name != "" { queryVars = append(queryVars, "name" + "=" + q_name) }
			if q_idChecklistSource != "" { queryVars = append(queryVars, "idChecklistSource" + "=" + q_idChecklistSource) }
			if q_pos != "" { queryVars = append(queryVars, "pos" + "=" + q_pos) }
			return execRaw(cmd, "POST", "/cards/{id}/checklists", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_name, "name", "", "The name of the checklist")
	cmd.Flags().StringVar(&q_idChecklistSource, "idChecklistSource", "", "The ID of a source checklist to copy into the new one")
	cmd.Flags().StringVar(&q_pos, "pos", "", "The position of the checklist on the card. One of: `top`, `bottom`, or a posi...")
	return cmd
}

func cmdPostCardsIdIdlabels() *cobra.Command {
	var (
		q_value string
	)
	cmd := &cobra.Command{
		Use:   "post-cards-id-idlabels <id>",
		Short: "Add a Label to a Card",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_value != "" { queryVars = append(queryVars, "value" + "=" + q_value) }
			return execRaw(cmd, "POST", "/cards/{id}/idLabels", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_value, "value", "", "The ID of the label to add")
	return cmd
}

func cmdPostCardsIdIdmembers() *cobra.Command {
	var (
		q_value string
	)
	cmd := &cobra.Command{
		Use:   "post-cards-id-idmembers <id>",
		Short: "Add a Member to a Card",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_value != "" { queryVars = append(queryVars, "value" + "=" + q_value) }
			return execRaw(cmd, "POST", "/cards/{id}/idMembers", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_value, "value", "", "The ID of the Member to add to the card")
	return cmd
}

func cmdPostCardsIdLabels() *cobra.Command {
	var (
		q_color string
		q_name string
	)
	cmd := &cobra.Command{
		Use:   "post-cards-id-labels <id>",
		Short: "Create a new Label on a Card",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_color != "" { queryVars = append(queryVars, "color" + "=" + q_color) }
			if q_name != "" { queryVars = append(queryVars, "name" + "=" + q_name) }
			return execRaw(cmd, "POST", "/cards/{id}/labels", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_color, "color", "", "A valid label color or `null`. See [labels](/cloud/trello/guides/rest-api/obj...")
	cmd.Flags().StringVar(&q_name, "name", "", "A name for the label")
	return cmd
}

func cmdPostCardsIdMarkassociatednotificationsread() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "post-cards-id-markassociatednotificationsread <id>",
		Short: "Mark a Card's Notifications as read",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "POST", "/cards/{id}/markAssociatedNotificationsRead", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdPostCardsIdStickers() *cobra.Command {
	var (
		q_image string
		q_top string
		q_left string
		q_zIndex string
		q_rotate string
	)
	cmd := &cobra.Command{
		Use:   "post-cards-id-stickers <id>",
		Short: "Add a Sticker to a Card",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_image != "" { queryVars = append(queryVars, "image" + "=" + q_image) }
			if q_top != "" { queryVars = append(queryVars, "top" + "=" + q_top) }
			if q_left != "" { queryVars = append(queryVars, "left" + "=" + q_left) }
			if q_zIndex != "" { queryVars = append(queryVars, "zIndex" + "=" + q_zIndex) }
			if q_rotate != "" { queryVars = append(queryVars, "rotate" + "=" + q_rotate) }
			return execRaw(cmd, "POST", "/cards/{id}/stickers", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_image, "image", "", "For custom stickers, the id of the sticker. For default stickers, the string ...")
	cmd.Flags().StringVar(&q_top, "top", "", "The top position of the sticker, from -60 to 100")
	cmd.Flags().StringVar(&q_left, "left", "", "The left position of the sticker, from -60 to 100")
	cmd.Flags().StringVar(&q_zIndex, "zIndex", "", "The z-index of the sticker")
	cmd.Flags().StringVar(&q_rotate, "rotate", "", "The rotation of the sticker")
	return cmd
}

func cmdPutCardsId() *cobra.Command {
	var (
		q_name string
		q_desc string
		q_closed string
		q_idMembers string
		q_idAttachmentCover string
		q_idList string
		q_idLabels string
		q_idBoard string
		q_pos string
		q_due string
		q_start string
		q_dueComplete string
		q_subscribed string
		q_address string
		q_locationName string
		q_coordinates string
		q_cover string
	)
	cmd := &cobra.Command{
		Use:   "put-cards-id <id>",
		Short: "Update a Card",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_name != "" { queryVars = append(queryVars, "name" + "=" + q_name) }
			if q_desc != "" { queryVars = append(queryVars, "desc" + "=" + q_desc) }
			if q_closed != "" { queryVars = append(queryVars, "closed" + "=" + q_closed) }
			if q_idMembers != "" { queryVars = append(queryVars, "idMembers" + "=" + q_idMembers) }
			if q_idAttachmentCover != "" { queryVars = append(queryVars, "idAttachmentCover" + "=" + q_idAttachmentCover) }
			if q_idList != "" { queryVars = append(queryVars, "idList" + "=" + q_idList) }
			if q_idLabels != "" { queryVars = append(queryVars, "idLabels" + "=" + q_idLabels) }
			if q_idBoard != "" { queryVars = append(queryVars, "idBoard" + "=" + q_idBoard) }
			if q_pos != "" { queryVars = append(queryVars, "pos" + "=" + q_pos) }
			if q_due != "" { queryVars = append(queryVars, "due" + "=" + q_due) }
			if q_start != "" { queryVars = append(queryVars, "start" + "=" + q_start) }
			if q_dueComplete != "" { queryVars = append(queryVars, "dueComplete" + "=" + q_dueComplete) }
			if q_subscribed != "" { queryVars = append(queryVars, "subscribed" + "=" + q_subscribed) }
			if q_address != "" { queryVars = append(queryVars, "address" + "=" + q_address) }
			if q_locationName != "" { queryVars = append(queryVars, "locationName" + "=" + q_locationName) }
			if q_coordinates != "" { queryVars = append(queryVars, "coordinates" + "=" + q_coordinates) }
			if q_cover != "" { queryVars = append(queryVars, "cover" + "=" + q_cover) }
			return execRaw(cmd, "PUT", "/cards/{id}", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_name, "name", "", "The new name for the card")
	cmd.Flags().StringVar(&q_desc, "desc", "", "The new description for the card")
	cmd.Flags().StringVar(&q_closed, "closed", "", "Whether the card should be archived (closed: true)")
	cmd.Flags().StringVar(&q_idMembers, "idMembers", "", "Comma-separated list of member IDs")
	cmd.Flags().StringVar(&q_idAttachmentCover, "idAttachmentCover", "", "The ID of the image attachment the card should use as its cover, or null for ...")
	cmd.Flags().StringVar(&q_idList, "idList", "", "The ID of the list the card should be in")
	cmd.Flags().StringVar(&q_idLabels, "idLabels", "", "Comma-separated list of label IDs")
	cmd.Flags().StringVar(&q_idBoard, "idBoard", "", "The ID of the board the card should be on")
	cmd.Flags().StringVar(&q_pos, "pos", "", "The position of the card in its list. `top`, `bottom`, or a positive float")
	cmd.Flags().StringVar(&q_due, "due", "", "When the card is due, or `null`")
	cmd.Flags().StringVar(&q_start, "start", "", "The start date of a card, or `null`")
	cmd.Flags().StringVar(&q_dueComplete, "dueComplete", "", "Whether the status of the card is complete")
	cmd.Flags().StringVar(&q_subscribed, "subscribed", "", "Whether the member is should be subscribed to the card")
	cmd.Flags().StringVar(&q_address, "address", "", "For use with/by the Map View")
	cmd.Flags().StringVar(&q_locationName, "locationName", "", "For use with/by the Map View")
	cmd.Flags().StringVar(&q_coordinates, "coordinates", "", "For use with/by the Map View. Should be latitude,longitude")
	cmd.Flags().StringVar(&q_cover, "cover", "", "Updates the card's cover  | Option | Values | About |  |--------|--------|---...")
	return cmd
}

func cmdPutCardsIdActionsIdactionComments() *cobra.Command {
	var (
		q_text string
	)
	cmd := &cobra.Command{
		Use:   "put-cards-id-actions-idaction-comments <id> <idAction>",
		Short: "Update Comment Action on a Card",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idAction" + "=" + args[1],
			}
			queryVars := []string{}
			if q_text != "" { queryVars = append(queryVars, "text" + "=" + q_text) }
			return execRaw(cmd, "PUT", "/cards/{id}/actions/{idAction}/comments", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_text, "text", "", "The new text for the comment")
	return cmd
}

func cmdPutCardsIdCheckitemIdcheckitem() *cobra.Command {
	var (
		q_name string
		q_state string
		q_idChecklist string
		q_pos string
		q_due string
		q_dueReminder string
		q_idMember string
	)
	cmd := &cobra.Command{
		Use:   "put-cards-id-checkitem-idcheckitem <id> <idCheckItem>",
		Short: "Update a checkItem on a Card",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idCheckItem" + "=" + args[1],
			}
			queryVars := []string{}
			if q_name != "" { queryVars = append(queryVars, "name" + "=" + q_name) }
			if q_state != "" { queryVars = append(queryVars, "state" + "=" + q_state) }
			if q_idChecklist != "" { queryVars = append(queryVars, "idChecklist" + "=" + q_idChecklist) }
			if q_pos != "" { queryVars = append(queryVars, "pos" + "=" + q_pos) }
			if q_due != "" { queryVars = append(queryVars, "due" + "=" + q_due) }
			if q_dueReminder != "" { queryVars = append(queryVars, "dueReminder" + "=" + q_dueReminder) }
			if q_idMember != "" { queryVars = append(queryVars, "idMember" + "=" + q_idMember) }
			return execRaw(cmd, "PUT", "/cards/{id}/checkItem/{idCheckItem}", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_name, "name", "", "The new name for the checklist item")
	cmd.Flags().StringVar(&q_state, "state", "", "One of: `complete`, `incomplete`")
	cmd.Flags().StringVar(&q_idChecklist, "idChecklist", "", "The ID of the checklist this item is in")
	cmd.Flags().StringVar(&q_pos, "pos", "", "`top`, `bottom`, or a positive float")
	cmd.Flags().StringVar(&q_due, "due", "", "A due date for the checkitem")
	cmd.Flags().StringVar(&q_dueReminder, "dueReminder", "", "A dueReminder for the due date on the checkitem")
	cmd.Flags().StringVar(&q_idMember, "idMember", "", "The ID of the member to remove from the card")
	return cmd
}

func cmdPutCardsIdStickersIdsticker() *cobra.Command {
	var (
		q_top string
		q_left string
		q_zIndex string
		q_rotate string
	)
	cmd := &cobra.Command{
		Use:   "put-cards-id-stickers-idsticker <id> <idSticker>",
		Short: "Update a Sticker on a Card",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idSticker" + "=" + args[1],
			}
			queryVars := []string{}
			if q_top != "" { queryVars = append(queryVars, "top" + "=" + q_top) }
			if q_left != "" { queryVars = append(queryVars, "left" + "=" + q_left) }
			if q_zIndex != "" { queryVars = append(queryVars, "zIndex" + "=" + q_zIndex) }
			if q_rotate != "" { queryVars = append(queryVars, "rotate" + "=" + q_rotate) }
			return execRaw(cmd, "PUT", "/cards/{id}/stickers/{idSticker}", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_top, "top", "", "The top position of the sticker, from -60 to 100")
	cmd.Flags().StringVar(&q_left, "left", "", "The left position of the sticker, from -60 to 100")
	cmd.Flags().StringVar(&q_zIndex, "zIndex", "", "The z-index of the sticker")
	cmd.Flags().StringVar(&q_rotate, "rotate", "", "The rotation of the sticker")
	return cmd
}

func cmdPutCardsIdcardChecklistIdchecklistCheckitemIdcheckitem() *cobra.Command {
	var (
		q_pos string
	)
	cmd := &cobra.Command{
		Use:   "put-cards-idcard-checklist-idchecklist-checkitem-idcheckitem <idCard> <idCheckItem> <idChecklist>",
		Short: "Update Checkitem on Checklist on Card",
		Args:  cobra.ExactArgs(3),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"idCard" + "=" + args[0],
				"idCheckItem" + "=" + args[1],
				"idChecklist" + "=" + args[2],
			}
			queryVars := []string{}
			if q_pos != "" { queryVars = append(queryVars, "pos" + "=" + q_pos) }
			return execRaw(cmd, "PUT", "/cards/{idCard}/checklist/{idChecklist}/checkItem/{idCheckItem}", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_pos, "pos", "", "`top`, `bottom`, or a positive float")
	return cmd
}

func cmdPutCardsIdcardCustomfieldIdcustomfieldItem() *cobra.Command {
	var (
		dataArg string
	)
	cmd := &cobra.Command{
		Use:   "put-cards-idcard-customfield-idcustomfield-item <idCard> <idCustomField>",
		Short: "Update Custom Field item on Card",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"idCard" + "=" + args[0],
				"idCustomField" + "=" + args[1],
			}
			queryVars := []string{}
			return execRaw(cmd, "PUT", "/cards/{idCard}/customField/{idCustomField}/item", pathVars, queryVars, dataArg)
		},
	}
	cmd.Flags().StringVar(&dataArg, "data", "", "Request body: literal JSON or @file")
	return cmd
}

func cmdPutCardsIdcardCustomfields() *cobra.Command {
	var (
		dataArg string
	)
	cmd := &cobra.Command{
		Use:   "put-cards-idcard-customfields <idCard>",
		Short: "Update Multiple Custom Field items on Card",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"idCard" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "PUT", "/cards/{idCard}/customFields", pathVars, queryVars, dataArg)
		},
	}
	cmd.Flags().StringVar(&dataArg, "data", "", "Request body: literal JSON or @file")
	return cmd
}

