// Code generated by tools/cmdgen. DO NOT EDIT.

package auto

import "github.com/spf13/cobra"

func GroupChecklists() *cobra.Command {
	cmd := &cobra.Command{Use: "checklists", Short: "Auto-generated commands for checklists"}
	cmd.AddCommand(cmdDeleteChecklistsId())
	cmd.AddCommand(cmdDeleteChecklistsIdCheckitemsIdcheckitem())
	cmd.AddCommand(cmdGetChecklistsId())
	cmd.AddCommand(cmdGetChecklistsIdBoard())
	cmd.AddCommand(cmdGetChecklistsIdCards())
	cmd.AddCommand(cmdGetChecklistsIdCheckitems())
	cmd.AddCommand(cmdGetChecklistsIdCheckitemsIdcheckitem())
	cmd.AddCommand(cmdGetChecklistsIdField())
	cmd.AddCommand(cmdPostChecklists())
	cmd.AddCommand(cmdPostChecklistsIdCheckitems())
	cmd.AddCommand(cmdPutChecklistsIdField())
	cmd.AddCommand(cmdPutCheclistsId())
	return cmd
}

func cmdDeleteChecklistsId() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "delete-checklists-id <id>",
		Short: "Delete a Checklist",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "DELETE", "/checklists/{id}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdDeleteChecklistsIdCheckitemsIdcheckitem() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "delete-checklists-id-checkitems-idcheckitem <id> <idCheckItem>",
		Short: "Delete Checkitem from Checklist",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idCheckItem" + "=" + args[1],
			}
			queryVars := []string{}
			return execRaw(cmd, "DELETE", "/checklists/{id}/checkItems/{idCheckItem}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetChecklistsId() *cobra.Command {
	var (
		q_cards string
		q_checkItems string
		q_checkItemfields string
		q_fields string
	)
	cmd := &cobra.Command{
		Use:   "get-checklists-id <id>",
		Short: "Get a Checklist",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_cards != "" { queryVars = append(queryVars, "cards" + "=" + q_cards) }
			if q_checkItems != "" { queryVars = append(queryVars, "checkItems" + "=" + q_checkItems) }
			if q_checkItemfields != "" { queryVars = append(queryVars, "checkItem_fields" + "=" + q_checkItemfields) }
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			return execRaw(cmd, "GET", "/checklists/{id}", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_cards, "cards", "", "Valid values: `all`, `closed`, `none`, `open`, `visible`. Cards is a nested r...")
	cmd.Flags().StringVar(&q_checkItems, "checkItems", "", "The check items on the list to return. One of: `all`, `none`.")
	cmd.Flags().StringVar(&q_checkItemfields, "checkItem_fields", "", "The fields on the checkItem to return if checkItems are being returned. `all`...")
	cmd.Flags().StringVar(&q_fields, "fields", "", "`all` or a comma-separated list of checklist [fields](/cloud/trello/guides/re...")
	return cmd
}

func cmdGetChecklistsIdBoard() *cobra.Command {
	var (
		q_fields string
	)
	cmd := &cobra.Command{
		Use:   "get-checklists-id-board <id>",
		Short: "Get the Board the Checklist is on",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			return execRaw(cmd, "GET", "/checklists/{id}/board", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_fields, "fields", "", "`all` or a comma-separated list of board [fields](/cloud/trello/guides/rest-a...")
	return cmd
}

func cmdGetChecklistsIdCards() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "get-checklists-id-cards <id>",
		Short: "Get the Card a Checklist is on",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/checklists/{id}/cards", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetChecklistsIdCheckitems() *cobra.Command {
	var (
		q_filter string
		q_fields string
	)
	cmd := &cobra.Command{
		Use:   "get-checklists-id-checkitems <id>",
		Short: "Get Checkitems on a Checklist",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_filter != "" { queryVars = append(queryVars, "filter" + "=" + q_filter) }
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			return execRaw(cmd, "GET", "/checklists/{id}/checkItems", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_filter, "filter", "", "One of: `all`, `none`.")
	cmd.Flags().StringVar(&q_fields, "fields", "", "One of: `all`, `name`, `nameData`, `pos`, `state`,`type`, `due`, `dueReminder...")
	return cmd
}

func cmdGetChecklistsIdCheckitemsIdcheckitem() *cobra.Command {
	var (
		q_fields string
	)
	cmd := &cobra.Command{
		Use:   "get-checklists-id-checkitems-idcheckitem <id> <idCheckItem>",
		Short: "Get a Checkitem on a Checklist",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idCheckItem" + "=" + args[1],
			}
			queryVars := []string{}
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			return execRaw(cmd, "GET", "/checklists/{id}/checkItems/{idCheckItem}", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_fields, "fields", "", "One of: `all`, `name`, `nameData`, `pos`, `state`, `type`, `due`, `dueReminde...")
	return cmd
}

func cmdGetChecklistsIdField() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "get-checklists-id-field <id> <field>",
		Short: "Get field on a Checklist",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"field" + "=" + args[1],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/checklists/{id}/{field}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdPostChecklists() *cobra.Command {
	var (
		q_idCard string
		q_name string
		q_pos string
		q_idChecklistSource string
	)
	cmd := &cobra.Command{
		Use:   "post-checklists",
		Short: "Create a Checklist",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
			}
			queryVars := []string{}
			if q_idCard != "" { queryVars = append(queryVars, "idCard" + "=" + q_idCard) }
			if q_name != "" { queryVars = append(queryVars, "name" + "=" + q_name) }
			if q_pos != "" { queryVars = append(queryVars, "pos" + "=" + q_pos) }
			if q_idChecklistSource != "" { queryVars = append(queryVars, "idChecklistSource" + "=" + q_idChecklistSource) }
			return execRaw(cmd, "POST", "/checklists", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_idCard, "idCard", "", "The ID of the Card that the checklist should be added to.")
	cmd.Flags().StringVar(&q_name, "name", "", "The name of the checklist. Should be a string of length 1 to 16384.")
	cmd.Flags().StringVar(&q_pos, "pos", "", "The position of the checklist on the card. One of: `top`, `bottom`, or a posi...")
	cmd.Flags().StringVar(&q_idChecklistSource, "idChecklistSource", "", "The ID of a checklist to copy into the new checklist.")
	return cmd
}

func cmdPostChecklistsIdCheckitems() *cobra.Command {
	var (
		q_name string
		q_pos string
		q_checked string
		q_due string
		q_dueReminder string
		q_idMember string
	)
	cmd := &cobra.Command{
		Use:   "post-checklists-id-checkitems <id>",
		Short: "Create Checkitem on Checklist",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_name != "" { queryVars = append(queryVars, "name" + "=" + q_name) }
			if q_pos != "" { queryVars = append(queryVars, "pos" + "=" + q_pos) }
			if q_checked != "" { queryVars = append(queryVars, "checked" + "=" + q_checked) }
			if q_due != "" { queryVars = append(queryVars, "due" + "=" + q_due) }
			if q_dueReminder != "" { queryVars = append(queryVars, "dueReminder" + "=" + q_dueReminder) }
			if q_idMember != "" { queryVars = append(queryVars, "idMember" + "=" + q_idMember) }
			return execRaw(cmd, "POST", "/checklists/{id}/checkItems", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_name, "name", "", "The name of the new check item on the checklist. Should be a string of length...")
	cmd.Flags().StringVar(&q_pos, "pos", "", "The position of the check item in the checklist. One of: `top`, `bottom`, or ...")
	cmd.Flags().StringVar(&q_checked, "checked", "", "Determines whether the check item is already checked when created.")
	cmd.Flags().StringVar(&q_due, "due", "", "A due date for the checkitem")
	cmd.Flags().StringVar(&q_dueReminder, "dueReminder", "", "A dueReminder for the due date on the checkitem")
	cmd.Flags().StringVar(&q_idMember, "idMember", "", "An ID of a member resource.")
	return cmd
}

func cmdPutChecklistsIdField() *cobra.Command {
	var (
		q_value string
	)
	cmd := &cobra.Command{
		Use:   "put-checklists-id-field <id> <field>",
		Short: "Update field on a Checklist",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"field" + "=" + args[1],
			}
			queryVars := []string{}
			if q_value != "" { queryVars = append(queryVars, "value" + "=" + q_value) }
			return execRaw(cmd, "PUT", "/checklists/{id}/{field}", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_value, "value", "", "The value to change the checklist name to. Should be a string of length 1 to ...")
	return cmd
}

func cmdPutCheclistsId() *cobra.Command {
	var (
		q_name string
		q_pos string
	)
	cmd := &cobra.Command{
		Use:   "put-checlists-id <id>",
		Short: "Update a Checklist",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_name != "" { queryVars = append(queryVars, "name" + "=" + q_name) }
			if q_pos != "" { queryVars = append(queryVars, "pos" + "=" + q_pos) }
			return execRaw(cmd, "PUT", "/checklists/{id}", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_name, "name", "", "Name of the new checklist being created. Should be length of 1 to 16384.")
	cmd.Flags().StringVar(&q_pos, "pos", "", "Determines the position of the checklist on the card. One of: `top`, `bottom`...")
	return cmd
}

