// Code generated by tools/cmdgen. DO NOT EDIT.

package auto

import "github.com/spf13/cobra"

func GroupCustomFields() *cobra.Command {
	cmd := &cobra.Command{Use: "customFields", Short: "Auto-generated commands for customFields"}
	cmd.AddCommand(cmdDeleteCustomfieldsId())
	cmd.AddCommand(cmdDeleteCustomfieldsOptionsIdcustomfieldoption())
	cmd.AddCommand(cmdGetCustomfieldsId())
	cmd.AddCommand(cmdGetCustomfieldsIdOptions())
	cmd.AddCommand(cmdGetCustomfieldsOptionsIdcustomfieldoption())
	cmd.AddCommand(cmdPostCustomfields())
	cmd.AddCommand(cmdPostCustomfieldsIdOptions())
	cmd.AddCommand(cmdPutCustomfieldsId())
	return cmd
}

func cmdDeleteCustomfieldsId() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "delete-customfields-id <id>",
		Short: "Delete a Custom Field definition",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "DELETE", "/customFields/{id}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdDeleteCustomfieldsOptionsIdcustomfieldoption() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "delete-customfields-options-idcustomfieldoption <id> <idCustomFieldOption>",
		Short: "Delete Option of Custom Field dropdown",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idCustomFieldOption" + "=" + args[1],
			}
			queryVars := []string{}
			return execRaw(cmd, "DELETE", "/customFields/{id}/options/{idCustomFieldOption}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetCustomfieldsId() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "get-customfields-id <id>",
		Short: "Get a Custom Field",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/customFields/{id}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetCustomfieldsIdOptions() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "get-customfields-id-options <id>",
		Short: "Add Option to Custom Field dropdown",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "POST", "/customFields/{id}/options", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetCustomfieldsOptionsIdcustomfieldoption() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "get-customfields-options-idcustomfieldoption <id> <idCustomFieldOption>",
		Short: "Get Option of Custom Field dropdown",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idCustomFieldOption" + "=" + args[1],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/customFields/{id}/options/{idCustomFieldOption}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdPostCustomfields() *cobra.Command {
	var (
		dataArg string
	)
	cmd := &cobra.Command{
		Use:   "post-customfields",
		Short: "Create a new Custom Field on a Board",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
			}
			queryVars := []string{}
			return execRaw(cmd, "POST", "/customFields", pathVars, queryVars, dataArg)
		},
	}
	cmd.Flags().StringVar(&dataArg, "data", "", "Request body: literal JSON or @file")
	return cmd
}

func cmdPostCustomfieldsIdOptions() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "post-customfields-id-options <id>",
		Short: "Get Options of Custom Field drop down",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/customFields/{id}/options", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdPutCustomfieldsId() *cobra.Command {
	var (
		dataArg string
	)
	cmd := &cobra.Command{
		Use:   "put-customfields-id <id>",
		Short: "Update a Custom Field definition",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "PUT", "/customFields/{id}", pathVars, queryVars, dataArg)
		},
	}
	cmd.Flags().StringVar(&dataArg, "data", "", "Request body: literal JSON or @file")
	return cmd
}

