// Code generated by tools/cmdgen. DO NOT EDIT.

package auto

import "github.com/spf13/cobra"

func GroupEmoji() *cobra.Command {
	cmd := &cobra.Command{Use: "emoji", Short: "Auto-generated commands for emoji"}
	cmd.AddCommand(cmdEmoji())
	return cmd
}

func cmdEmoji() *cobra.Command {
	var (
		q_locale string
		q_spritesheets string
	)
	cmd := &cobra.Command{
		Use:   "emoji",
		Short: "List available Emoji",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
			}
			queryVars := []string{}
			if q_locale != "" { queryVars = append(queryVars, "locale" + "=" + q_locale) }
			if q_spritesheets != "" { queryVars = append(queryVars, "spritesheets" + "=" + q_spritesheets) }
			return execRaw(cmd, "GET", "/emoji", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_locale, "locale", "", "The locale to return emoji descriptions and names in. Defaults to the logged ...")
	cmd.Flags().StringVar(&q_spritesheets, "spritesheets", "", "`true` to return spritesheet URLs in the response")
	return cmd
}

