// Code generated by tools/cmdgen. DO NOT EDIT.

package auto

import "github.com/spf13/cobra"

func GroupEnterprises() *cobra.Command {
	cmd := &cobra.Command{Use: "enterprises", Short: "Auto-generated commands for enterprises"}
	cmd.AddCommand(cmdDeleteEnterprisesIdOrganizationsIdorg())
	cmd.AddCommand(cmdEnterprisesIdMembersIdmemberDeactivated())
	cmd.AddCommand(cmdEnterprisesIdOrganizationsIdmember())
	cmd.AddCommand(cmdGetEnterprisesId())
	cmd.AddCommand(cmdGetEnterprisesIdAdmins())
	cmd.AddCommand(cmdGetEnterprisesIdAuditlog())
	cmd.AddCommand(cmdGetEnterprisesIdClaimableorganizations())
	cmd.AddCommand(cmdGetEnterprisesIdMembers())
	cmd.AddCommand(cmdGetEnterprisesIdMembersIdmember())
	cmd.AddCommand(cmdGetEnterprisesIdOrganizations())
	cmd.AddCommand(cmdGetEnterprisesIdOrganizationsBulkIdorganizations())
	cmd.AddCommand(cmdGetEnterprisesIdPendingorganizations())
	cmd.AddCommand(cmdGetEnterprisesIdSignupurl())
	cmd.AddCommand(cmdGetEnterprisesIdTransferrableBulkIdorganizations())
	cmd.AddCommand(cmdGetEnterprisesIdTransferrableOrganizationIdorganization())
	cmd.AddCommand(cmdGetUsersId())
	cmd.AddCommand(cmdPostEnterprisesIdTokens())
	cmd.AddCommand(cmdPutEnterprisesIdAdminsIdmember())
	cmd.AddCommand(cmdPutEnterprisesIdEnterprisejoinrequestBulk())
	cmd.AddCommand(cmdPutEnterprisesIdMembersIdmemberLicensed())
	cmd.AddCommand(cmdPutEnterprisesIdOrganizations())
	return cmd
}

func cmdDeleteEnterprisesIdOrganizationsIdorg() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "delete-enterprises-id-organizations-idorg <id> <idOrg>",
		Short: "Delete an Organization from an Enterprise.",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idOrg" + "=" + args[1],
			}
			queryVars := []string{}
			return execRaw(cmd, "DELETE", "/enterprises/{id}/organizations/{idOrg}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdEnterprisesIdMembersIdmemberDeactivated() *cobra.Command {
	var (
		q_value string
		q_fields string
		q_organizationfields string
		q_boardfields string
	)
	cmd := &cobra.Command{
		Use:   "enterprises-id-members-idmember-deactivated <id> <idMember>",
		Short: "Deactivate a Member of an Enterprise.",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idMember" + "=" + args[1],
			}
			queryVars := []string{}
			if q_value != "" { queryVars = append(queryVars, "value" + "=" + q_value) }
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			if q_organizationfields != "" { queryVars = append(queryVars, "organization_fields" + "=" + q_organizationfields) }
			if q_boardfields != "" { queryVars = append(queryVars, "board_fields" + "=" + q_boardfields) }
			return execRaw(cmd, "PUT", "/enterprises/{id}/members/{idMember}/deactivated", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_value, "value", "", "Determines whether the user is deactivated or not.")
	cmd.Flags().StringVar(&q_fields, "fields", "", "A comma separated list of any valid values that the [nested member field reso...")
	cmd.Flags().StringVar(&q_organizationfields, "organization_fields", "", "Any valid value that the [nested organization resource](/cloud/trello/guides/...")
	cmd.Flags().StringVar(&q_boardfields, "board_fields", "", "Any valid value that the [nested board resource](/cloud/trello/guides/rest-ap...")
	return cmd
}

func cmdEnterprisesIdOrganizationsIdmember() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "enterprises-id-organizations-idmember <id> <idMember>",
		Short: "Remove a Member as admin from Enterprise.",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idMember" + "=" + args[1],
			}
			queryVars := []string{}
			return execRaw(cmd, "DELETE", "/enterprises/{id}/admins/{idMember}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetEnterprisesId() *cobra.Command {
	var (
		q_fields string
		q_members string
		q_memberfields string
		q_memberfilter string
		q_membersort string
		q_membersortBy string
		q_membersortOrder string
		q_memberstartIndex string
		q_membercount string
		q_organizations string
		q_organizationfields string
		q_organizationpaidaccounts string
		q_organizationmemberships string
	)
	cmd := &cobra.Command{
		Use:   "get-enterprises-id <id>",
		Short: "Get an Enterprise",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			if q_members != "" { queryVars = append(queryVars, "members" + "=" + q_members) }
			if q_memberfields != "" { queryVars = append(queryVars, "member_fields" + "=" + q_memberfields) }
			if q_memberfilter != "" { queryVars = append(queryVars, "member_filter" + "=" + q_memberfilter) }
			if q_membersort != "" { queryVars = append(queryVars, "member_sort" + "=" + q_membersort) }
			if q_membersortBy != "" { queryVars = append(queryVars, "member_sortBy" + "=" + q_membersortBy) }
			if q_membersortOrder != "" { queryVars = append(queryVars, "member_sortOrder" + "=" + q_membersortOrder) }
			if q_memberstartIndex != "" { queryVars = append(queryVars, "member_startIndex" + "=" + q_memberstartIndex) }
			if q_membercount != "" { queryVars = append(queryVars, "member_count" + "=" + q_membercount) }
			if q_organizations != "" { queryVars = append(queryVars, "organizations" + "=" + q_organizations) }
			if q_organizationfields != "" { queryVars = append(queryVars, "organization_fields" + "=" + q_organizationfields) }
			if q_organizationpaidaccounts != "" { queryVars = append(queryVars, "organization_paid_accounts" + "=" + q_organizationpaidaccounts) }
			if q_organizationmemberships != "" { queryVars = append(queryVars, "organization_memberships" + "=" + q_organizationmemberships) }
			return execRaw(cmd, "GET", "/enterprises/{id}", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_fields, "fields", "", "Comma-separated list of: `id`, `name`, `displayName`, `prefs`, `ssoActivation...")
	cmd.Flags().StringVar(&q_members, "members", "", "One of: `none`, `normal`, `admins`, `owners`, `all`")
	cmd.Flags().StringVar(&q_memberfields, "member_fields", "", "One of: `avatarHash`, `fullName`, `initials`, `username`")
	cmd.Flags().StringVar(&q_memberfilter, "member_filter", "", "Pass a SCIM-style query to filter members. This takes precedence over the all...")
	cmd.Flags().StringVar(&q_membersort, "member_sort", "", "This parameter expects a SCIM-style sorting value prefixed by a `-` to sort d...")
	cmd.Flags().StringVar(&q_membersortBy, "member_sortBy", "", "Deprecated: Please use member_sort. This parameter expects a SCIM-style sorti...")
	cmd.Flags().StringVar(&q_membersortOrder, "member_sortOrder", "", "Deprecated: Please use member_sort. One of: `ascending`, `descending`, `asc`,...")
	cmd.Flags().StringVar(&q_memberstartIndex, "member_startIndex", "", "Any integer between 0 and 100.")
	cmd.Flags().StringVar(&q_membercount, "member_count", "", "0 to 100")
	cmd.Flags().StringVar(&q_organizations, "organizations", "", "One of: `none`, `members`, `public`, `all`")
	cmd.Flags().StringVar(&q_organizationfields, "organization_fields", "", "Any valid value that the [nested organization field resource]() accepts.")
	cmd.Flags().StringVar(&q_organizationpaidaccounts, "organization_paid_accounts", "", "Whether or not to include paid account information in the returned workspace ...")
	cmd.Flags().StringVar(&q_organizationmemberships, "organization_memberships", "", "Comma-seperated list of: `me`, `normal`, `admin`, `active`, `deactivated`")
	return cmd
}

func cmdGetEnterprisesIdAdmins() *cobra.Command {
	var (
		q_fields string
	)
	cmd := &cobra.Command{
		Use:   "get-enterprises-id-admins <id>",
		Short: "Get Enterprise admin Members",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			return execRaw(cmd, "GET", "/enterprises/{id}/admins", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_fields, "fields", "", "Any valid value that the [nested member field resource]() accepts.")
	return cmd
}

func cmdGetEnterprisesIdAuditlog() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "get-enterprises-id-auditlog <id>",
		Short: "Get auditlog data for an Enterprise",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/enterprises/{id}/auditlog", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetEnterprisesIdClaimableorganizations() *cobra.Command {
	var (
		q_limit string
		q_cursor string
		q_name string
		q_activeSince string
		q_inactiveSince string
	)
	cmd := &cobra.Command{
		Use:   "get-enterprises-id-claimableorganizations <id>",
		Short: "Get ClaimableOrganizations of an Enterprise",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_limit != "" { queryVars = append(queryVars, "limit" + "=" + q_limit) }
			if q_cursor != "" { queryVars = append(queryVars, "cursor" + "=" + q_cursor) }
			if q_name != "" { queryVars = append(queryVars, "name" + "=" + q_name) }
			if q_activeSince != "" { queryVars = append(queryVars, "activeSince" + "=" + q_activeSince) }
			if q_inactiveSince != "" { queryVars = append(queryVars, "inactiveSince" + "=" + q_inactiveSince) }
			return execRaw(cmd, "GET", "/enterprises/{id}/claimableOrganizations", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_limit, "limit", "", "Limits the number of workspaces to be sorted")
	cmd.Flags().StringVar(&q_cursor, "cursor", "", "Specifies the sort order to return matching documents")
	cmd.Flags().StringVar(&q_name, "name", "", "Name of the enterprise to retrieve workspaces for")
	cmd.Flags().StringVar(&q_activeSince, "activeSince", "", "Date in YYYY-MM-DD format indicating the date to search up to for activeness ...")
	cmd.Flags().StringVar(&q_inactiveSince, "inactiveSince", "", "Date in YYYY-MM-DD format indicating the date to search up to for inactivenes...")
	return cmd
}

func cmdGetEnterprisesIdMembers() *cobra.Command {
	var (
		q_fields string
		q_filter string
		q_sort string
		q_sortBy string
		q_sortOrder string
		q_startIndex string
		q_count string
		q_organizationfields string
		q_boardfields string
	)
	cmd := &cobra.Command{
		Use:   "get-enterprises-id-members <id>",
		Short: "Get Members of Enterprise",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			if q_filter != "" { queryVars = append(queryVars, "filter" + "=" + q_filter) }
			if q_sort != "" { queryVars = append(queryVars, "sort" + "=" + q_sort) }
			if q_sortBy != "" { queryVars = append(queryVars, "sortBy" + "=" + q_sortBy) }
			if q_sortOrder != "" { queryVars = append(queryVars, "sortOrder" + "=" + q_sortOrder) }
			if q_startIndex != "" { queryVars = append(queryVars, "startIndex" + "=" + q_startIndex) }
			if q_count != "" { queryVars = append(queryVars, "count" + "=" + q_count) }
			if q_organizationfields != "" { queryVars = append(queryVars, "organization_fields" + "=" + q_organizationfields) }
			if q_boardfields != "" { queryVars = append(queryVars, "board_fields" + "=" + q_boardfields) }
			return execRaw(cmd, "GET", "/enterprises/{id}/members", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_fields, "fields", "", "A comma-seperated list of valid [member fields](/cloud/trello/guides/rest-api...")
	cmd.Flags().StringVar(&q_filter, "filter", "", "Pass a SCIM-style query to filter members. This takes precedence over the all...")
	cmd.Flags().StringVar(&q_sort, "sort", "", "This parameter expects a SCIM-style sorting value prefixed by a `-` to sort d...")
	cmd.Flags().StringVar(&q_sortBy, "sortBy", "", "Deprecated: Please use `sort` instead. This parameter expects a SCIM-style so...")
	cmd.Flags().StringVar(&q_sortOrder, "sortOrder", "", "Deprecated: Please use `sort` instead. One of: `ascending`, `descending`, `as...")
	cmd.Flags().StringVar(&q_startIndex, "startIndex", "", "Any integer between 0 and 9999.")
	cmd.Flags().StringVar(&q_count, "count", "", "SCIM-style filter.")
	cmd.Flags().StringVar(&q_organizationfields, "organization_fields", "", "Any valid value that the [nested organization field resource](/cloud/trello/g...")
	cmd.Flags().StringVar(&q_boardfields, "board_fields", "", "Any valid value that the [nested board resource](/cloud/trello/guides/rest-ap...")
	return cmd
}

func cmdGetEnterprisesIdMembersIdmember() *cobra.Command {
	var (
		q_fields string
		q_organizationfields string
		q_boardfields string
	)
	cmd := &cobra.Command{
		Use:   "get-enterprises-id-members-idmember <id> <idMember>",
		Short: "Get a Member of Enterprise",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idMember" + "=" + args[1],
			}
			queryVars := []string{}
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			if q_organizationfields != "" { queryVars = append(queryVars, "organization_fields" + "=" + q_organizationfields) }
			if q_boardfields != "" { queryVars = append(queryVars, "board_fields" + "=" + q_boardfields) }
			return execRaw(cmd, "GET", "/enterprises/{id}/members/{idMember}", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_fields, "fields", "", "A comma separated list of any valid values that the [nested member field reso...")
	cmd.Flags().StringVar(&q_organizationfields, "organization_fields", "", "Any valid value that the [nested organization field resource](/cloud/trello/g...")
	cmd.Flags().StringVar(&q_boardfields, "board_fields", "", "Any valid value that the [nested board resource](/cloud/trello/guides/rest-ap...")
	return cmd
}

func cmdGetEnterprisesIdOrganizations() *cobra.Command {
	var (
		q_fields string
		q_filter string
		q_startIndex string
		q_count string
	)
	cmd := &cobra.Command{
		Use:   "get-enterprises-id-organizations <id>",
		Short: "Get Organizations of an Enterprise",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			if q_filter != "" { queryVars = append(queryVars, "filter" + "=" + q_filter) }
			if q_startIndex != "" { queryVars = append(queryVars, "startIndex" + "=" + q_startIndex) }
			if q_count != "" { queryVars = append(queryVars, "count" + "=" + q_count) }
			return execRaw(cmd, "GET", "/enterprises/{id}/organizations", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_fields, "fields", "", "comma-separated list of organization [fields](/cloud/trello/guides/rest-api/o...")
	cmd.Flags().StringVar(&q_filter, "filter", "", "")
	cmd.Flags().StringVar(&q_startIndex, "startIndex", "", "Any integer greater than and equal to 1.")
	cmd.Flags().StringVar(&q_count, "count", "", "Any integer between 0 and 100.")
	return cmd
}

func cmdGetEnterprisesIdOrganizationsBulkIdorganizations() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "get-enterprises-id-organizations-bulk-idorganizations <id> <idOrganizations>",
		Short: "Bulk accept a set of organizations to an Enterprise.",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idOrganizations" + "=" + args[1],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/enterprises/{id}/organizations/bulk/{idOrganizations}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetEnterprisesIdPendingorganizations() *cobra.Command {
	var (
		q_activeSince string
		q_inactiveSince string
	)
	cmd := &cobra.Command{
		Use:   "get-enterprises-id-pendingorganizations <id>",
		Short: "Get PendingOrganizations of an Enterprise",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_activeSince != "" { queryVars = append(queryVars, "activeSince" + "=" + q_activeSince) }
			if q_inactiveSince != "" { queryVars = append(queryVars, "inactiveSince" + "=" + q_inactiveSince) }
			return execRaw(cmd, "GET", "/enterprises/{id}/pendingOrganizations", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_activeSince, "activeSince", "", "Date in YYYY-MM-DD format indicating the date to search up to for activeness ...")
	cmd.Flags().StringVar(&q_inactiveSince, "inactiveSince", "", "Date in YYYY-MM-DD format indicating the date to search up to for inactivenes...")
	return cmd
}

func cmdGetEnterprisesIdSignupurl() *cobra.Command {
	var (
		q_authenticate string
		q_confirmationAccepted string
		q_returnUrl string
		q_tosAccepted string
	)
	cmd := &cobra.Command{
		Use:   "get-enterprises-id-signupurl <id>",
		Short: "Get signupUrl for Enterprise",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_authenticate != "" { queryVars = append(queryVars, "authenticate" + "=" + q_authenticate) }
			if q_confirmationAccepted != "" { queryVars = append(queryVars, "confirmationAccepted" + "=" + q_confirmationAccepted) }
			if q_returnUrl != "" { queryVars = append(queryVars, "returnUrl" + "=" + q_returnUrl) }
			if q_tosAccepted != "" { queryVars = append(queryVars, "tosAccepted" + "=" + q_tosAccepted) }
			return execRaw(cmd, "GET", "/enterprises/{id}/signupUrl", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_authenticate, "authenticate", "", "")
	cmd.Flags().StringVar(&q_confirmationAccepted, "confirmationAccepted", "", "")
	cmd.Flags().StringVar(&q_returnUrl, "returnUrl", "", "Any valid URL.")
	cmd.Flags().StringVar(&q_tosAccepted, "tosAccepted", "", "Designates whether the user has seen/consented to the Trello ToS prior to bei...")
	return cmd
}

func cmdGetEnterprisesIdTransferrableBulkIdorganizations() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "get-enterprises-id-transferrable-bulk-idorganizations <id> <idOrganizations>",
		Short: "Get a bulk list of organizations that can be transferred to an enterprise.",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idOrganizations" + "=" + args[1],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/enterprises/{id}/transferrable/bulk/{idOrganizations}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetEnterprisesIdTransferrableOrganizationIdorganization() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "get-enterprises-id-transferrable-organization-idorganization <id> <idOrganization>",
		Short: "Get whether an organization can be transferred to an enterprise.",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idOrganization" + "=" + args[1],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/enterprises/{id}/transferrable/organization/{idOrganization}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetUsersId() *cobra.Command {
	var (
		q_licensed string
		q_deactivated string
		q_collaborator string
		q_managed string
		q_admin string
		q_activeSince string
		q_inactiveSince string
		q_search string
		q_cursor string
	)
	cmd := &cobra.Command{
		Use:   "get-users-id <id>",
		Short: "Get Users of an Enterprise",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_licensed != "" { queryVars = append(queryVars, "licensed" + "=" + q_licensed) }
			if q_deactivated != "" { queryVars = append(queryVars, "deactivated" + "=" + q_deactivated) }
			if q_collaborator != "" { queryVars = append(queryVars, "collaborator" + "=" + q_collaborator) }
			if q_managed != "" { queryVars = append(queryVars, "managed" + "=" + q_managed) }
			if q_admin != "" { queryVars = append(queryVars, "admin" + "=" + q_admin) }
			if q_activeSince != "" { queryVars = append(queryVars, "activeSince" + "=" + q_activeSince) }
			if q_inactiveSince != "" { queryVars = append(queryVars, "inactiveSince" + "=" + q_inactiveSince) }
			if q_search != "" { queryVars = append(queryVars, "search" + "=" + q_search) }
			if q_cursor != "" { queryVars = append(queryVars, "cursor" + "=" + q_cursor) }
			return execRaw(cmd, "GET", "/enterprises/{id}/members/query", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_licensed, "licensed", "", "When true, returns members who possess a license for the corresponding Trello...")
	cmd.Flags().StringVar(&q_deactivated, "deactivated", "", "When true, returns members who have been deactivated for the corresponding Tr...")
	cmd.Flags().StringVar(&q_collaborator, "collaborator", "", "When true, returns members who are guests on one or more boards in the corres...")
	cmd.Flags().StringVar(&q_managed, "managed", "", "When true, returns members who are managed by the corresponding Trello Enterp...")
	cmd.Flags().StringVar(&q_admin, "admin", "", "When true, returns members who are administrators of the corresponding Trello...")
	cmd.Flags().StringVar(&q_activeSince, "activeSince", "", "Returns only Trello users active since this date (inclusive).")
	cmd.Flags().StringVar(&q_inactiveSince, "inactiveSince", "", "Returns only Trello users active since this date (inclusive).")
	cmd.Flags().StringVar(&q_search, "search", "", "Returns members with email address or full name that start with the search va...")
	cmd.Flags().StringVar(&q_cursor, "cursor", "", "Cursor to return next set of results, use cursor returned in the response to ...")
	return cmd
}

func cmdPostEnterprisesIdTokens() *cobra.Command {
	var (
		q_expiration string
	)
	cmd := &cobra.Command{
		Use:   "post-enterprises-id-tokens <id>",
		Short: "Create an auth Token for an Enterprise.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_expiration != "" { queryVars = append(queryVars, "expiration" + "=" + q_expiration) }
			return execRaw(cmd, "POST", "/enterprises/{id}/tokens", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_expiration, "expiration", "", "One of: `1hour`, `1day`, `30days`, `never`")
	return cmd
}

func cmdPutEnterprisesIdAdminsIdmember() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "put-enterprises-id-admins-idmember <id> <idMember>",
		Short: "Update Member to be admin of Enterprise",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idMember" + "=" + args[1],
			}
			queryVars := []string{}
			return execRaw(cmd, "PUT", "/enterprises/{id}/admins/{idMember}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdPutEnterprisesIdEnterprisejoinrequestBulk() *cobra.Command {
	var (
		q_idOrganizations string
	)
	cmd := &cobra.Command{
		Use:   "put-enterprises-id-enterprisejoinrequest-bulk <id>",
		Short: "Decline enterpriseJoinRequests from one organization or a bulk list of organi...",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_idOrganizations != "" { queryVars = append(queryVars, "idOrganizations" + "=" + q_idOrganizations) }
			return execRaw(cmd, "PUT", "/enterprises/${id}/enterpriseJoinRequest/bulk", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_idOrganizations, "idOrganizations", "", "An array of IDs of an Organization resource.")
	return cmd
}

func cmdPutEnterprisesIdMembersIdmemberLicensed() *cobra.Command {
	var (
		q_value string
	)
	cmd := &cobra.Command{
		Use:   "put-enterprises-id-members-idmember-licensed <id> <idMember>",
		Short: "Update a Member's licensed status",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idMember" + "=" + args[1],
			}
			queryVars := []string{}
			if q_value != "" { queryVars = append(queryVars, "value" + "=" + q_value) }
			return execRaw(cmd, "PUT", "/enterprises/{id}/members/{idMember}/licensed", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_value, "value", "", "Boolean value to determine whether the user should be given an Enterprise lic...")
	return cmd
}

func cmdPutEnterprisesIdOrganizations() *cobra.Command {
	var (
		q_idOrganization string
	)
	cmd := &cobra.Command{
		Use:   "put-enterprises-id-organizations <id>",
		Short: "Transfer an Organization to an Enterprise.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_idOrganization != "" { queryVars = append(queryVars, "idOrganization" + "=" + q_idOrganization) }
			return execRaw(cmd, "PUT", "/enterprises/{id}/organizations", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_idOrganization, "idOrganization", "", "ID of Organization to be transferred to Enterprise.")
	return cmd
}

