// Code generated by tools/cmdgen. DO NOT EDIT.

package auto

import "github.com/spf13/cobra"

func GroupLabels() *cobra.Command {
	cmd := &cobra.Command{Use: "labels", Short: "Auto-generated commands for labels"}
	cmd.AddCommand(cmdDeleteLabelsId())
	cmd.AddCommand(cmdGetLabelsId())
	cmd.AddCommand(cmdPostLabels())
	cmd.AddCommand(cmdPutLabelsId())
	cmd.AddCommand(cmdPutLabelsIdField())
	return cmd
}

func cmdDeleteLabelsId() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "delete-labels-id <id>",
		Short: "Delete a Label",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "DELETE", "/labels/{id}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetLabelsId() *cobra.Command {
	var (
		q_fields string
	)
	cmd := &cobra.Command{
		Use:   "get-labels-id <id>",
		Short: "Get a Label",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			return execRaw(cmd, "GET", "/labels/{id}", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_fields, "fields", "", "all or a comma-separated list of [fields](/cloud/trello/guides/rest-api/objec...")
	return cmd
}

func cmdPostLabels() *cobra.Command {
	var (
		q_name string
		q_color string
		q_idBoard string
	)
	cmd := &cobra.Command{
		Use:   "post-labels",
		Short: "Create a Label",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
			}
			queryVars := []string{}
			if q_name != "" { queryVars = append(queryVars, "name" + "=" + q_name) }
			if q_color != "" { queryVars = append(queryVars, "color" + "=" + q_color) }
			if q_idBoard != "" { queryVars = append(queryVars, "idBoard" + "=" + q_idBoard) }
			return execRaw(cmd, "POST", "/labels", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_name, "name", "", "Name for the label")
	cmd.Flags().StringVar(&q_color, "color", "", "The color for the label.")
	cmd.Flags().StringVar(&q_idBoard, "idBoard", "", "The ID of the Board to create the Label on.")
	return cmd
}

func cmdPutLabelsId() *cobra.Command {
	var (
		q_name string
		q_color string
	)
	cmd := &cobra.Command{
		Use:   "put-labels-id <id>",
		Short: "Update a Label",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_name != "" { queryVars = append(queryVars, "name" + "=" + q_name) }
			if q_color != "" { queryVars = append(queryVars, "color" + "=" + q_color) }
			return execRaw(cmd, "PUT", "/labels/{id}", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_name, "name", "", "The new name for the label")
	cmd.Flags().StringVar(&q_color, "color", "", "The new color for the label. See: [fields](/cloud/trello/guides/rest-api/obje...")
	return cmd
}

func cmdPutLabelsIdField() *cobra.Command {
	var (
		q_value string
	)
	cmd := &cobra.Command{
		Use:   "put-labels-id-field <id> <field>",
		Short: "Update a field on a label",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"field" + "=" + args[1],
			}
			queryVars := []string{}
			if q_value != "" { queryVars = append(queryVars, "value" + "=" + q_value) }
			return execRaw(cmd, "PUT", "/labels/{id}/{field}", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_value, "value", "", "The new value for the field.")
	return cmd
}

