// Code generated by tools/cmdgen. DO NOT EDIT.

package auto

import "github.com/spf13/cobra"

func GroupLists() *cobra.Command {
	cmd := &cobra.Command{Use: "lists", Short: "Auto-generated commands for lists"}
	cmd.AddCommand(cmdGetListsId())
	cmd.AddCommand(cmdGetListsIdActions())
	cmd.AddCommand(cmdGetListsIdBoard())
	cmd.AddCommand(cmdGetListsIdCards())
	cmd.AddCommand(cmdPostLists())
	cmd.AddCommand(cmdPostListsIdArchiveallcards())
	cmd.AddCommand(cmdPostListsIdMoveallcards())
	cmd.AddCommand(cmdPutIdIdboard())
	cmd.AddCommand(cmdPutListsId())
	cmd.AddCommand(cmdPutListsIdClosed())
	cmd.AddCommand(cmdPutListsIdField())
	return cmd
}

func cmdGetListsId() *cobra.Command {
	var (
		q_fields string
	)
	cmd := &cobra.Command{
		Use:   "get-lists-id <id>",
		Short: "Get a List",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			return execRaw(cmd, "GET", "/lists/{id}", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_fields, "fields", "", "`all` or a comma separated list of List field names.")
	return cmd
}

func cmdGetListsIdActions() *cobra.Command {
	var (
		q_filter string
	)
	cmd := &cobra.Command{
		Use:   "get-lists-id-actions <id>",
		Short: "Get Actions for a List",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_filter != "" { queryVars = append(queryVars, "filter" + "=" + q_filter) }
			return execRaw(cmd, "GET", "/lists/{id}/actions", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_filter, "filter", "", "A comma-separated list of [action types](https://developer.atlassian.com/clou...")
	return cmd
}

func cmdGetListsIdBoard() *cobra.Command {
	var (
		q_fields string
	)
	cmd := &cobra.Command{
		Use:   "get-lists-id-board <id>",
		Short: "Get the Board a List is on",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			return execRaw(cmd, "GET", "/lists/{id}/board", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_fields, "fields", "", "`all` or a comma-separated list of board [fields](/cloud/trello/guides/rest-a...")
	return cmd
}

func cmdGetListsIdCards() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "get-lists-id-cards <id>",
		Short: "Get Cards in a List",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/lists/{id}/cards", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdPostLists() *cobra.Command {
	var (
		q_name string
		q_idBoard string
		q_idListSource string
		q_pos string
	)
	cmd := &cobra.Command{
		Use:   "post-lists",
		Short: "Create a new List",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
			}
			queryVars := []string{}
			if q_name != "" { queryVars = append(queryVars, "name" + "=" + q_name) }
			if q_idBoard != "" { queryVars = append(queryVars, "idBoard" + "=" + q_idBoard) }
			if q_idListSource != "" { queryVars = append(queryVars, "idListSource" + "=" + q_idListSource) }
			if q_pos != "" { queryVars = append(queryVars, "pos" + "=" + q_pos) }
			return execRaw(cmd, "POST", "/lists", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_name, "name", "", "Name for the list")
	cmd.Flags().StringVar(&q_idBoard, "idBoard", "", "The long ID of the board the list should be created on")
	cmd.Flags().StringVar(&q_idListSource, "idListSource", "", "ID of the List to copy into the new List")
	cmd.Flags().StringVar(&q_pos, "pos", "", "Position of the list. `top`, `bottom`, or a positive floating point number")
	return cmd
}

func cmdPostListsIdArchiveallcards() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "post-lists-id-archiveallcards <id>",
		Short: "Archive all Cards in List",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "POST", "/lists/{id}/archiveAllCards", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdPostListsIdMoveallcards() *cobra.Command {
	var (
		q_idBoard string
		q_idList string
	)
	cmd := &cobra.Command{
		Use:   "post-lists-id-moveallcards <id>",
		Short: "Move all Cards in List",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_idBoard != "" { queryVars = append(queryVars, "idBoard" + "=" + q_idBoard) }
			if q_idList != "" { queryVars = append(queryVars, "idList" + "=" + q_idList) }
			return execRaw(cmd, "POST", "/lists/{id}/moveAllCards", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_idBoard, "idBoard", "", "The ID of the board the cards should be moved to")
	cmd.Flags().StringVar(&q_idList, "idList", "", "The ID of the list that the cards should be moved to")
	return cmd
}

func cmdPutIdIdboard() *cobra.Command {
	var (
		q_value string
	)
	cmd := &cobra.Command{
		Use:   "put-id-idboard <id>",
		Short: "Move List to Board",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_value != "" { queryVars = append(queryVars, "value" + "=" + q_value) }
			return execRaw(cmd, "PUT", "/lists/{id}/idBoard", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_value, "value", "", "The ID of the board to move the list to")
	return cmd
}

func cmdPutListsId() *cobra.Command {
	var (
		q_name string
		q_closed string
		q_idBoard string
		q_pos string
		q_subscribed string
	)
	cmd := &cobra.Command{
		Use:   "put-lists-id <id>",
		Short: "Update a List",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_name != "" { queryVars = append(queryVars, "name" + "=" + q_name) }
			if q_closed != "" { queryVars = append(queryVars, "closed" + "=" + q_closed) }
			if q_idBoard != "" { queryVars = append(queryVars, "idBoard" + "=" + q_idBoard) }
			if q_pos != "" { queryVars = append(queryVars, "pos" + "=" + q_pos) }
			if q_subscribed != "" { queryVars = append(queryVars, "subscribed" + "=" + q_subscribed) }
			return execRaw(cmd, "PUT", "/lists/{id}", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_name, "name", "", "New name for the list")
	cmd.Flags().StringVar(&q_closed, "closed", "", "Whether the list should be closed (archived)")
	cmd.Flags().StringVar(&q_idBoard, "idBoard", "", "ID of a board the list should be moved to")
	cmd.Flags().StringVar(&q_pos, "pos", "", "New position for the list: `top`, `bottom`, or a positive floating point number")
	cmd.Flags().StringVar(&q_subscribed, "subscribed", "", "Whether the active member is subscribed to this list")
	return cmd
}

func cmdPutListsIdClosed() *cobra.Command {
	var (
		q_value string
	)
	cmd := &cobra.Command{
		Use:   "put-lists-id-closed <id>",
		Short: "Archive or unarchive a list",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_value != "" { queryVars = append(queryVars, "value" + "=" + q_value) }
			return execRaw(cmd, "PUT", "/lists/{id}/closed", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_value, "value", "", "Set to true to close (archive) the list")
	return cmd
}

func cmdPutListsIdField() *cobra.Command {
	var (
		q_value string
	)
	cmd := &cobra.Command{
		Use:   "put-lists-id-field <id> <field>",
		Short: "Update a field on a List",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"field" + "=" + args[1],
			}
			queryVars := []string{}
			if q_value != "" { queryVars = append(queryVars, "value" + "=" + q_value) }
			return execRaw(cmd, "PUT", "/lists/{id}/{field}", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_value, "value", "", "The new value for the field")
	return cmd
}

