// Code generated by tools/cmdgen. DO NOT EDIT.

package auto

import "github.com/spf13/cobra"

func GroupMembers() *cobra.Command {
	cmd := &cobra.Command{Use: "members", Short: "Auto-generated commands for members"}
	cmd.AddCommand(cmdDeleteMembersIdBoardbackgroundsIdbackground())
	cmd.AddCommand(cmdDeleteMembersIdBoardstarsIdstar())
	cmd.AddCommand(cmdDeleteMembersIdCustomboardbackgroundsIdbackground())
	cmd.AddCommand(cmdDeleteMembersIdCustomstickersIdsticker())
	cmd.AddCommand(cmdDeleteMembersIdSavedsearchesIdsearch())
	cmd.AddCommand(cmdGetMembersIdActions())
	cmd.AddCommand(cmdGetMembersIdBoardbackgrounds())
	cmd.AddCommand(cmdGetMembersIdBoardbackgroundsIdbackground())
	cmd.AddCommand(cmdGetMembersIdBoards())
	cmd.AddCommand(cmdGetMembersIdBoardsinvited())
	cmd.AddCommand(cmdGetMembersIdBoardstars())
	cmd.AddCommand(cmdGetMembersIdBoardstarsIdstar())
	cmd.AddCommand(cmdGetMembersIdCards())
	cmd.AddCommand(cmdGetMembersIdCustomboardbackgrounds())
	cmd.AddCommand(cmdGetMembersIdCustomboardbackgroundsIdbackground())
	cmd.AddCommand(cmdGetMembersIdCustomemoji())
	cmd.AddCommand(cmdGetMembersIdCustomstickers())
	cmd.AddCommand(cmdGetMembersIdCustomstickersIdsticker())
	cmd.AddCommand(cmdGetMembersIdField())
	cmd.AddCommand(cmdGetMembersIdNotificationchannelsettings())
	cmd.AddCommand(cmdGetMembersIdNotificationchannelsettingsChannel())
	cmd.AddCommand(cmdGetMembersIdNotifications())
	cmd.AddCommand(cmdGetMembersIdOrganizations())
	cmd.AddCommand(cmdGetMembersIdOrganizationsinvited())
	cmd.AddCommand(cmdGetMembersIdSavedsearches())
	cmd.AddCommand(cmdGetMembersIdSavedsearchesIdsearch())
	cmd.AddCommand(cmdGetMembersIdTokens())
	cmd.AddCommand(cmdGetMembersid())
	cmd.AddCommand(cmdMembersidavatar())
	cmd.AddCommand(cmdMembersidcustomboardbackgrounds1())
	cmd.AddCommand(cmdMembersidcustomemojiidemoji())
	cmd.AddCommand(cmdPostMembersIdBoardbackgrounds1())
	cmd.AddCommand(cmdPostMembersIdBoardstars())
	cmd.AddCommand(cmdPostMembersIdCustomemoji())
	cmd.AddCommand(cmdPostMembersIdCustomstickers())
	cmd.AddCommand(cmdPostMembersIdOnetimemessagesdismissed())
	cmd.AddCommand(cmdPostMembersIdSavedsearches())
	cmd.AddCommand(cmdPutMembersId())
	cmd.AddCommand(cmdPutMembersIdBoardbackgroundsIdbackground())
	cmd.AddCommand(cmdPutMembersIdBoardstarsIdstar())
	cmd.AddCommand(cmdPutMembersIdCustomboardbackgroundsIdbackground())
	cmd.AddCommand(cmdPutMembersIdNotificationchannelsettings())
	cmd.AddCommand(cmdPutMembersIdNotificationchannelsettingsChannel())
	cmd.AddCommand(cmdPutMembersIdSavedsearchesIdsearch())
	return cmd
}

func cmdDeleteMembersIdBoardbackgroundsIdbackground() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "delete-members-id-boardbackgrounds-idbackground <id> <idBackground>",
		Short: "Delete a Member's custom Board background",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idBackground" + "=" + args[1],
			}
			queryVars := []string{}
			return execRaw(cmd, "DELETE", "/members/{id}/boardBackgrounds/{idBackground}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdDeleteMembersIdBoardstarsIdstar() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "delete-members-id-boardstars-idstar <id> <idStar>",
		Short: "Delete Star for Board",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idStar" + "=" + args[1],
			}
			queryVars := []string{}
			return execRaw(cmd, "DELETE", "/members/{id}/boardStars/{idStar}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdDeleteMembersIdCustomboardbackgroundsIdbackground() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "delete-members-id-customboardbackgrounds-idbackground <id> <idBackground>",
		Short: "Delete custom Board Background of Member",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idBackground" + "=" + args[1],
			}
			queryVars := []string{}
			return execRaw(cmd, "DELETE", "/members/{id}/customBoardBackgrounds/{idBackground}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdDeleteMembersIdCustomstickersIdsticker() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "delete-members-id-customstickers-idsticker <id> <idSticker>",
		Short: "Delete a Member's custom Sticker",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idSticker" + "=" + args[1],
			}
			queryVars := []string{}
			return execRaw(cmd, "DELETE", "/members/{id}/customStickers/{idSticker}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdDeleteMembersIdSavedsearchesIdsearch() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "delete-members-id-savedsearches-idsearch <id> <idSearch>",
		Short: "Delete a saved search",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idSearch" + "=" + args[1],
			}
			queryVars := []string{}
			return execRaw(cmd, "DELETE", "/members/{id}/savedSearches/{idSearch}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetMembersIdActions() *cobra.Command {
	var (
		q_filter string
	)
	cmd := &cobra.Command{
		Use:   "get-members-id-actions <id>",
		Short: "Get a Member's Actions",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_filter != "" { queryVars = append(queryVars, "filter" + "=" + q_filter) }
			return execRaw(cmd, "GET", "/members/{id}/actions", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_filter, "filter", "", "A comma-separated list of [action types](https://developer.atlassian.com/clou...")
	return cmd
}

func cmdGetMembersIdBoardbackgrounds() *cobra.Command {
	var (
		q_filter string
	)
	cmd := &cobra.Command{
		Use:   "get-members-id-boardbackgrounds <id>",
		Short: "Get Member's custom Board backgrounds",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_filter != "" { queryVars = append(queryVars, "filter" + "=" + q_filter) }
			return execRaw(cmd, "GET", "/members/{id}/boardBackgrounds", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_filter, "filter", "", "One of: `all`, `custom`, `default`, `none`, `premium`")
	return cmd
}

func cmdGetMembersIdBoardbackgroundsIdbackground() *cobra.Command {
	var (
		q_fields string
	)
	cmd := &cobra.Command{
		Use:   "get-members-id-boardbackgrounds-idbackground <id> <idBackground>",
		Short: "Get a boardBackground of a Member",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idBackground" + "=" + args[1],
			}
			queryVars := []string{}
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			return execRaw(cmd, "GET", "/members/{id}/boardBackgrounds/{idBackground}", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_fields, "fields", "", "`all` or a comma-separated list of: `brightness`, `fullSizeUrl`, `scaled`, `t...")
	return cmd
}

func cmdGetMembersIdBoards() *cobra.Command {
	var (
		q_filter string
		q_fields string
		q_lists string
		q_organization string
		q_organizationfields string
	)
	cmd := &cobra.Command{
		Use:   "get-members-id-boards <id>",
		Short: "Get Boards that Member belongs to",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_filter != "" { queryVars = append(queryVars, "filter" + "=" + q_filter) }
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			if q_lists != "" { queryVars = append(queryVars, "lists" + "=" + q_lists) }
			if q_organization != "" { queryVars = append(queryVars, "organization" + "=" + q_organization) }
			if q_organizationfields != "" { queryVars = append(queryVars, "organization_fields" + "=" + q_organizationfields) }
			return execRaw(cmd, "GET", "/members/{id}/boards", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_filter, "filter", "", "`all` or a comma-separated list of: `closed`, `members`, `open`, `organizatio...")
	cmd.Flags().StringVar(&q_fields, "fields", "", "`all` or a comma-separated list of board [fields](/cloud/trello/guides/rest-a...")
	cmd.Flags().StringVar(&q_lists, "lists", "", "Which lists to include with the boards. One of: `all`, `closed`, `none`, `open`")
	cmd.Flags().StringVar(&q_organization, "organization", "", "Whether to include the Organization object with the Boards")
	cmd.Flags().StringVar(&q_organizationfields, "organization_fields", "", "`all` or a comma-separated list of organization [fields](/cloud/trello/guides...")
	return cmd
}

func cmdGetMembersIdBoardsinvited() *cobra.Command {
	var (
		q_fields string
	)
	cmd := &cobra.Command{
		Use:   "get-members-id-boardsinvited <id>",
		Short: "Get Boards the Member has been invited to",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			return execRaw(cmd, "GET", "/members/{id}/boardsInvited", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_fields, "fields", "", "`all` or a comma-separated list of board [fields](/cloud/trello/guides/rest-a...")
	return cmd
}

func cmdGetMembersIdBoardstars() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "get-members-id-boardstars <id>",
		Short: "Get a Member's boardStars",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/members/{id}/boardStars", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetMembersIdBoardstarsIdstar() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "get-members-id-boardstars-idstar <id> <idStar>",
		Short: "Get a boardStar of Member",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idStar" + "=" + args[1],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/members/{id}/boardStars/{idStar}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetMembersIdCards() *cobra.Command {
	var (
		q_filter string
	)
	cmd := &cobra.Command{
		Use:   "get-members-id-cards <id>",
		Short: "Get Cards the Member is on",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_filter != "" { queryVars = append(queryVars, "filter" + "=" + q_filter) }
			return execRaw(cmd, "GET", "/members/{id}/cards", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_filter, "filter", "", "One of: `all`, `closed`, `complete`, `incomplete`, `none`, `open`, `visible`")
	return cmd
}

func cmdGetMembersIdCustomboardbackgrounds() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "get-members-id-customboardbackgrounds <id>",
		Short: "Get a Member's custom Board Backgrounds",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/members/{id}/customBoardBackgrounds", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetMembersIdCustomboardbackgroundsIdbackground() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "get-members-id-customboardbackgrounds-idbackground <id> <idBackground>",
		Short: "Get custom Board Background of Member",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idBackground" + "=" + args[1],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/members/{id}/customBoardBackgrounds/{idBackground}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetMembersIdCustomemoji() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "get-members-id-customemoji <id>",
		Short: "Get a Member's customEmojis",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/members/{id}/customEmoji", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetMembersIdCustomstickers() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "get-members-id-customstickers <id>",
		Short: "Get Member's custom Stickers",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/members/{id}/customStickers", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetMembersIdCustomstickersIdsticker() *cobra.Command {
	var (
		q_fields string
	)
	cmd := &cobra.Command{
		Use:   "get-members-id-customstickers-idsticker <id> <idSticker>",
		Short: "Get a Member's custom Sticker",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idSticker" + "=" + args[1],
			}
			queryVars := []string{}
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			return execRaw(cmd, "GET", "/members/{id}/customStickers/{idSticker}", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_fields, "fields", "", "`all` or a comma-separated list of `scaled`, `url`")
	return cmd
}

func cmdGetMembersIdField() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "get-members-id-field <id> <field>",
		Short: "Get a field on a Member",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"field" + "=" + args[1],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/members/{id}/{field}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetMembersIdNotificationchannelsettings() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "get-members-id-notificationchannelsettings <id>",
		Short: "Get a Member's notification channel settings",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/members/{id}/notificationsChannelSettings", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetMembersIdNotificationchannelsettingsChannel() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "get-members-id-notificationchannelsettings-channel <id> <channel>",
		Short: "Get blocked notification keys of Member on this channel",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"channel" + "=" + args[1],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/members/{id}/notificationsChannelSettings/{channel}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetMembersIdNotifications() *cobra.Command {
	var (
		q_entities string
		q_display string
		q_filter string
		q_readfilter string
		q_fields string
		q_limit string
		q_page string
		q_before string
		q_since string
		q_memberCreator string
		q_memberCreatorfields string
	)
	cmd := &cobra.Command{
		Use:   "get-members-id-notifications <id>",
		Short: "Get Member's Notifications",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_entities != "" { queryVars = append(queryVars, "entities" + "=" + q_entities) }
			if q_display != "" { queryVars = append(queryVars, "display" + "=" + q_display) }
			if q_filter != "" { queryVars = append(queryVars, "filter" + "=" + q_filter) }
			if q_readfilter != "" { queryVars = append(queryVars, "read_filter" + "=" + q_readfilter) }
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			if q_limit != "" { queryVars = append(queryVars, "limit" + "=" + q_limit) }
			if q_page != "" { queryVars = append(queryVars, "page" + "=" + q_page) }
			if q_before != "" { queryVars = append(queryVars, "before" + "=" + q_before) }
			if q_since != "" { queryVars = append(queryVars, "since" + "=" + q_since) }
			if q_memberCreator != "" { queryVars = append(queryVars, "memberCreator" + "=" + q_memberCreator) }
			if q_memberCreatorfields != "" { queryVars = append(queryVars, "memberCreator_fields" + "=" + q_memberCreatorfields) }
			return execRaw(cmd, "GET", "/members/{id}/notifications", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_entities, "entities", "", "")
	cmd.Flags().StringVar(&q_display, "display", "", "")
	cmd.Flags().StringVar(&q_filter, "filter", "", "")
	cmd.Flags().StringVar(&q_readfilter, "read_filter", "", "One of: `all`, `read`, `unread`")
	cmd.Flags().StringVar(&q_fields, "fields", "", "`all` or a comma-separated list of notification [fields](/cloud/trello/guides...")
	cmd.Flags().StringVar(&q_limit, "limit", "", "Max 1000")
	cmd.Flags().StringVar(&q_page, "page", "", "Max 100")
	cmd.Flags().StringVar(&q_before, "before", "", "A notification ID")
	cmd.Flags().StringVar(&q_since, "since", "", "A notification ID")
	cmd.Flags().StringVar(&q_memberCreator, "memberCreator", "", "")
	cmd.Flags().StringVar(&q_memberCreatorfields, "memberCreator_fields", "", "`all` or a comma-separated list of member [fields](/cloud/trello/guides/rest-...")
	return cmd
}

func cmdGetMembersIdOrganizations() *cobra.Command {
	var (
		q_filter string
		q_fields string
		q_paidaccount string
	)
	cmd := &cobra.Command{
		Use:   "get-members-id-organizations <id>",
		Short: "Get Member's Organizations",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_filter != "" { queryVars = append(queryVars, "filter" + "=" + q_filter) }
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			if q_paidaccount != "" { queryVars = append(queryVars, "paid_account" + "=" + q_paidaccount) }
			return execRaw(cmd, "GET", "/members/{id}/organizations", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_filter, "filter", "", "One of: `all`, `members`, `none`, `public` (Note: `members` filters to only p...")
	cmd.Flags().StringVar(&q_fields, "fields", "", "`all` or a comma-separated list of organization [fields](/cloud/trello/guides...")
	cmd.Flags().StringVar(&q_paidaccount, "paid_account", "", "Whether or not to include paid account information in the returned workspace ...")
	return cmd
}

func cmdGetMembersIdOrganizationsinvited() *cobra.Command {
	var (
		q_fields string
	)
	cmd := &cobra.Command{
		Use:   "get-members-id-organizationsinvited <id>",
		Short: "Get Organizations a Member has been invited to",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			return execRaw(cmd, "GET", "/members/{id}/organizationsInvited", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_fields, "fields", "", "`all` or a comma-separated list of organization [fields](/cloud/trello/guides...")
	return cmd
}

func cmdGetMembersIdSavedsearches() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "get-members-id-savedsearches <id>",
		Short: "Get Member's saved searched",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/members/{id}/savedSearches", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetMembersIdSavedsearchesIdsearch() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "get-members-id-savedsearches-idsearch <id> <idSearch>",
		Short: "Get a saved search",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idSearch" + "=" + args[1],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/members/{id}/savedSearches/{idSearch}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetMembersIdTokens() *cobra.Command {
	var (
		q_webhooks string
	)
	cmd := &cobra.Command{
		Use:   "get-members-id-tokens <id>",
		Short: "Get Member's Tokens",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_webhooks != "" { queryVars = append(queryVars, "webhooks" + "=" + q_webhooks) }
			return execRaw(cmd, "GET", "/members/{id}/tokens", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_webhooks, "webhooks", "", "Whether to include webhooks")
	return cmd
}

func cmdGetMembersid() *cobra.Command {
	var (
		q_actions string
		q_boards string
		q_boardBackgrounds string
		q_boardsInvited string
		q_boardsInvitedfields string
		q_boardStars string
		q_cards string
		q_customBoardBackgrounds string
		q_customEmoji string
		q_customStickers string
		q_fields string
		q_notifications string
		q_organizations string
		q_organizationfields string
		q_organizationpaidaccount string
		q_organizationsInvited string
		q_organizationsInvitedfields string
		q_paidaccount string
		q_savedSearches string
		q_tokens string
	)
	cmd := &cobra.Command{
		Use:   "get-members=id <id>",
		Short: "Get a Member",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_actions != "" { queryVars = append(queryVars, "actions" + "=" + q_actions) }
			if q_boards != "" { queryVars = append(queryVars, "boards" + "=" + q_boards) }
			if q_boardBackgrounds != "" { queryVars = append(queryVars, "boardBackgrounds" + "=" + q_boardBackgrounds) }
			if q_boardsInvited != "" { queryVars = append(queryVars, "boardsInvited" + "=" + q_boardsInvited) }
			if q_boardsInvitedfields != "" { queryVars = append(queryVars, "boardsInvited_fields" + "=" + q_boardsInvitedfields) }
			if q_boardStars != "" { queryVars = append(queryVars, "boardStars" + "=" + q_boardStars) }
			if q_cards != "" { queryVars = append(queryVars, "cards" + "=" + q_cards) }
			if q_customBoardBackgrounds != "" { queryVars = append(queryVars, "customBoardBackgrounds" + "=" + q_customBoardBackgrounds) }
			if q_customEmoji != "" { queryVars = append(queryVars, "customEmoji" + "=" + q_customEmoji) }
			if q_customStickers != "" { queryVars = append(queryVars, "customStickers" + "=" + q_customStickers) }
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			if q_notifications != "" { queryVars = append(queryVars, "notifications" + "=" + q_notifications) }
			if q_organizations != "" { queryVars = append(queryVars, "organizations" + "=" + q_organizations) }
			if q_organizationfields != "" { queryVars = append(queryVars, "organization_fields" + "=" + q_organizationfields) }
			if q_organizationpaidaccount != "" { queryVars = append(queryVars, "organization_paid_account" + "=" + q_organizationpaidaccount) }
			if q_organizationsInvited != "" { queryVars = append(queryVars, "organizationsInvited" + "=" + q_organizationsInvited) }
			if q_organizationsInvitedfields != "" { queryVars = append(queryVars, "organizationsInvited_fields" + "=" + q_organizationsInvitedfields) }
			if q_paidaccount != "" { queryVars = append(queryVars, "paid_account" + "=" + q_paidaccount) }
			if q_savedSearches != "" { queryVars = append(queryVars, "savedSearches" + "=" + q_savedSearches) }
			if q_tokens != "" { queryVars = append(queryVars, "tokens" + "=" + q_tokens) }
			return execRaw(cmd, "GET", "/members/{id}", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_actions, "actions", "", "See the [Actions Nested Resource](/cloud/trello/guides/rest-api/nested-resour...")
	cmd.Flags().StringVar(&q_boards, "boards", "", "See the [Boards Nested Resource](/cloud/trello/guides/rest-api/nested-resourc...")
	cmd.Flags().StringVar(&q_boardBackgrounds, "boardBackgrounds", "", "One of: `all`, `custom`, `default`, `none`, `premium`")
	cmd.Flags().StringVar(&q_boardsInvited, "boardsInvited", "", "`all` or a comma-separated list of: closed, members, open, organization, pinn...")
	cmd.Flags().StringVar(&q_boardsInvitedfields, "boardsInvited_fields", "", "`all` or a comma-separated list of board [fields](/cloud/trello/guides/rest-a...")
	cmd.Flags().StringVar(&q_boardStars, "boardStars", "", "Whether to return the boardStars or not")
	cmd.Flags().StringVar(&q_cards, "cards", "", "See the [Cards Nested Resource](/cloud/trello/guides/rest-api/nested-resource...")
	cmd.Flags().StringVar(&q_customBoardBackgrounds, "customBoardBackgrounds", "", "`all` or `none`")
	cmd.Flags().StringVar(&q_customEmoji, "customEmoji", "", "`all` or `none`")
	cmd.Flags().StringVar(&q_customStickers, "customStickers", "", "`all` or `none`")
	cmd.Flags().StringVar(&q_fields, "fields", "", "`all` or a comma-separated list of member [fields](/cloud/trello/guides/rest-...")
	cmd.Flags().StringVar(&q_notifications, "notifications", "", "See the [Notifications Nested Resource](/cloud/trello/guides/rest-api/nested-...")
	cmd.Flags().StringVar(&q_organizations, "organizations", "", "One of: `all`, `members`, `none`, `public`")
	cmd.Flags().StringVar(&q_organizationfields, "organization_fields", "", "`all` or a comma-separated list of organization [fields](/cloud/trello/guides...")
	cmd.Flags().StringVar(&q_organizationpaidaccount, "organization_paid_account", "", "Whether or not to include paid account information in the returned workspace ...")
	cmd.Flags().StringVar(&q_organizationsInvited, "organizationsInvited", "", "One of: `all`, `members`, `none`, `public`")
	cmd.Flags().StringVar(&q_organizationsInvitedfields, "organizationsInvited_fields", "", "`all` or a comma-separated list of organization [fields](/cloud/trello/guides...")
	cmd.Flags().StringVar(&q_paidaccount, "paid_account", "", "Whether or not to include paid account information in the returned member object")
	cmd.Flags().StringVar(&q_savedSearches, "savedSearches", "", "")
	cmd.Flags().StringVar(&q_tokens, "tokens", "", "`all` or `none`")
	return cmd
}

func cmdMembersidavatar() *cobra.Command {
	var (
		q_file string
	)
	cmd := &cobra.Command{
		Use:   "membersidavatar <id>",
		Short: "Create Avatar for Member",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_file != "" { queryVars = append(queryVars, "file" + "=" + q_file) }
			return execRaw(cmd, "POST", "/members/{id}/avatar", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_file, "file", "", "")
	return cmd
}

func cmdMembersidcustomboardbackgrounds1() *cobra.Command {
	var (
		q_file string
	)
	cmd := &cobra.Command{
		Use:   "membersidcustomboardbackgrounds-1 <id>",
		Short: "Create a new custom Board Background",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_file != "" { queryVars = append(queryVars, "file" + "=" + q_file) }
			return execRaw(cmd, "POST", "/members/{id}/customBoardBackgrounds", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_file, "file", "", "")
	return cmd
}

func cmdMembersidcustomemojiidemoji() *cobra.Command {
	var (
		q_fields string
	)
	cmd := &cobra.Command{
		Use:   "membersidcustomemojiidemoji <id> <idEmoji>",
		Short: "Get a Member's custom Emoji",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idEmoji" + "=" + args[1],
			}
			queryVars := []string{}
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			return execRaw(cmd, "GET", "/members/{id}/customEmoji/{idEmoji}", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_fields, "fields", "", "`all` or a comma-separated list of `name`, `url`")
	return cmd
}

func cmdPostMembersIdBoardbackgrounds1() *cobra.Command {
	var (
		q_file string
	)
	cmd := &cobra.Command{
		Use:   "post-members-id-boardbackgrounds-1 <id>",
		Short: "Upload new boardBackground for Member",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_file != "" { queryVars = append(queryVars, "file" + "=" + q_file) }
			return execRaw(cmd, "POST", "/members/{id}/boardBackgrounds", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_file, "file", "", "")
	return cmd
}

func cmdPostMembersIdBoardstars() *cobra.Command {
	var (
		q_idBoard string
		q_pos string
	)
	cmd := &cobra.Command{
		Use:   "post-members-id-boardstars <id>",
		Short: "Create Star for Board",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_idBoard != "" { queryVars = append(queryVars, "idBoard" + "=" + q_idBoard) }
			if q_pos != "" { queryVars = append(queryVars, "pos" + "=" + q_pos) }
			return execRaw(cmd, "POST", "/members/{id}/boardStars", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_idBoard, "idBoard", "", "The ID of the board to star")
	cmd.Flags().StringVar(&q_pos, "pos", "", "The position of the newly starred board. `top`, `bottom`, or a positive float.")
	return cmd
}

func cmdPostMembersIdCustomemoji() *cobra.Command {
	var (
		q_file string
		q_name string
	)
	cmd := &cobra.Command{
		Use:   "post-members-id-customemoji <id>",
		Short: "Create custom Emoji for Member",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_file != "" { queryVars = append(queryVars, "file" + "=" + q_file) }
			if q_name != "" { queryVars = append(queryVars, "name" + "=" + q_name) }
			return execRaw(cmd, "POST", "/members/{id}/customEmoji", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_file, "file", "", "")
	cmd.Flags().StringVar(&q_name, "name", "", "Name for the emoji. 2 - 64 characters")
	return cmd
}

func cmdPostMembersIdCustomstickers() *cobra.Command {
	var (
		q_file string
	)
	cmd := &cobra.Command{
		Use:   "post-members-id-customstickers <id>",
		Short: "Create custom Sticker for Member",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_file != "" { queryVars = append(queryVars, "file" + "=" + q_file) }
			return execRaw(cmd, "POST", "/members/{id}/customStickers", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_file, "file", "", "")
	return cmd
}

func cmdPostMembersIdOnetimemessagesdismissed() *cobra.Command {
	var (
		q_value string
	)
	cmd := &cobra.Command{
		Use:   "post-members-id-onetimemessagesdismissed <id>",
		Short: "Dismiss a message for Member",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_value != "" { queryVars = append(queryVars, "value" + "=" + q_value) }
			return execRaw(cmd, "POST", "/members/{id}/oneTimeMessagesDismissed", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_value, "value", "", "The message to dismiss")
	return cmd
}

func cmdPostMembersIdSavedsearches() *cobra.Command {
	var (
		q_name string
		q_query string
		q_pos string
	)
	cmd := &cobra.Command{
		Use:   "post-members-id-savedsearches <id>",
		Short: "Create saved Search for Member",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_name != "" { queryVars = append(queryVars, "name" + "=" + q_name) }
			if q_query != "" { queryVars = append(queryVars, "query" + "=" + q_query) }
			if q_pos != "" { queryVars = append(queryVars, "pos" + "=" + q_pos) }
			return execRaw(cmd, "POST", "/members/{id}/savedSearches", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_name, "name", "", "The name for the saved search")
	cmd.Flags().StringVar(&q_query, "query", "", "The search query")
	cmd.Flags().StringVar(&q_pos, "pos", "", "The position of the saved search. `top`, `bottom`, or a positive float.")
	return cmd
}

func cmdPutMembersId() *cobra.Command {
	var (
		q_fullName string
		q_initials string
		q_username string
		q_bio string
		q_avatarSource string
		q_prefscolorBlind string
		q_prefslocale string
		q_prefsminutesBetweenSummaries string
	)
	cmd := &cobra.Command{
		Use:   "put-members-id <id>",
		Short: "Update a Member",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_fullName != "" { queryVars = append(queryVars, "fullName" + "=" + q_fullName) }
			if q_initials != "" { queryVars = append(queryVars, "initials" + "=" + q_initials) }
			if q_username != "" { queryVars = append(queryVars, "username" + "=" + q_username) }
			if q_bio != "" { queryVars = append(queryVars, "bio" + "=" + q_bio) }
			if q_avatarSource != "" { queryVars = append(queryVars, "avatarSource" + "=" + q_avatarSource) }
			if q_prefscolorBlind != "" { queryVars = append(queryVars, "prefs/colorBlind" + "=" + q_prefscolorBlind) }
			if q_prefslocale != "" { queryVars = append(queryVars, "prefs/locale" + "=" + q_prefslocale) }
			if q_prefsminutesBetweenSummaries != "" { queryVars = append(queryVars, "prefs/minutesBetweenSummaries" + "=" + q_prefsminutesBetweenSummaries) }
			return execRaw(cmd, "PUT", "/members/{id}", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_fullName, "fullName", "", "New name for the member. Cannot begin or end with a space.")
	cmd.Flags().StringVar(&q_initials, "initials", "", "New initials for the member. 1-4 characters long.")
	cmd.Flags().StringVar(&q_username, "username", "", "New username for the member. At least 3 characters long, only lowercase lette...")
	cmd.Flags().StringVar(&q_bio, "bio", "", "")
	cmd.Flags().StringVar(&q_avatarSource, "avatarSource", "", "One of: `gravatar`, `none`, `upload`")
	cmd.Flags().StringVar(&q_prefscolorBlind, "prefs/colorBlind", "", "")
	cmd.Flags().StringVar(&q_prefslocale, "prefs/locale", "", "")
	cmd.Flags().StringVar(&q_prefsminutesBetweenSummaries, "prefs/minutesBetweenSummaries", "", "`-1` for disabled, `1`, or `60`")
	return cmd
}

func cmdPutMembersIdBoardbackgroundsIdbackground() *cobra.Command {
	var (
		q_brightness string
		q_tile string
	)
	cmd := &cobra.Command{
		Use:   "put-members-id-boardbackgrounds-idbackground <id> <idBackground>",
		Short: "Update a Member's custom Board background",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idBackground" + "=" + args[1],
			}
			queryVars := []string{}
			if q_brightness != "" { queryVars = append(queryVars, "brightness" + "=" + q_brightness) }
			if q_tile != "" { queryVars = append(queryVars, "tile" + "=" + q_tile) }
			return execRaw(cmd, "PUT", "/members/{id}/boardBackgrounds/{idBackground}", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_brightness, "brightness", "", "One of: `dark`, `light`, `unknown`")
	cmd.Flags().StringVar(&q_tile, "tile", "", "Whether the background should be tiled")
	return cmd
}

func cmdPutMembersIdBoardstarsIdstar() *cobra.Command {
	var (
		q_pos string
	)
	cmd := &cobra.Command{
		Use:   "put-members-id-boardstars-idstar <id> <idStar>",
		Short: "Update the position of a boardStar of Member",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idStar" + "=" + args[1],
			}
			queryVars := []string{}
			if q_pos != "" { queryVars = append(queryVars, "pos" + "=" + q_pos) }
			return execRaw(cmd, "PUT", "/members/{id}/boardStars/{idStar}", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_pos, "pos", "", "New position for the starred board. `top`, `bottom`, or a positive float.")
	return cmd
}

func cmdPutMembersIdCustomboardbackgroundsIdbackground() *cobra.Command {
	var (
		q_brightness string
		q_tile string
	)
	cmd := &cobra.Command{
		Use:   "put-members-id-customboardbackgrounds-idbackground <id> <idBackground>",
		Short: "Update custom Board Background of Member",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idBackground" + "=" + args[1],
			}
			queryVars := []string{}
			if q_brightness != "" { queryVars = append(queryVars, "brightness" + "=" + q_brightness) }
			if q_tile != "" { queryVars = append(queryVars, "tile" + "=" + q_tile) }
			return execRaw(cmd, "PUT", "/members/{id}/customBoardBackgrounds/{idBackground}", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_brightness, "brightness", "", "One of: `dark`, `light`, `unknown`")
	cmd.Flags().StringVar(&q_tile, "tile", "", "Whether to tile the background")
	return cmd
}

func cmdPutMembersIdNotificationchannelsettings() *cobra.Command {
	var (
		dataArg string
	)
	cmd := &cobra.Command{
		Use:   "put-members-id-notificationchannelsettings <id>",
		Short: "Update blocked notification keys of Member on a channel",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "PUT", "/members/{id}/notificationsChannelSettings", pathVars, queryVars, dataArg)
		},
	}
	cmd.Flags().StringVar(&dataArg, "data", "", "Request body: literal JSON or @file")
	return cmd
}

func cmdPutMembersIdNotificationchannelsettingsChannel() *cobra.Command {
	var (
		dataArg string
	)
	cmd := &cobra.Command{
		Use:   "put-members-id-notificationchannelsettings-channel <id> <channel>",
		Short: "Update blocked notification keys of Member on a channel",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"channel" + "=" + args[1],
			}
			queryVars := []string{}
			return execRaw(cmd, "PUT", "/members/{id}/notificationsChannelSettings/{channel}", pathVars, queryVars, dataArg)
		},
	}
	cmd.Flags().StringVar(&dataArg, "data", "", "Request body: literal JSON or @file")
	return cmd
}

func cmdPutMembersIdSavedsearchesIdsearch() *cobra.Command {
	var (
		q_name string
		q_query string
		q_pos string
	)
	cmd := &cobra.Command{
		Use:   "put-members-id-savedsearches-idsearch <id> <idSearch>",
		Short: "Update a saved search",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idSearch" + "=" + args[1],
			}
			queryVars := []string{}
			if q_name != "" { queryVars = append(queryVars, "name" + "=" + q_name) }
			if q_query != "" { queryVars = append(queryVars, "query" + "=" + q_query) }
			if q_pos != "" { queryVars = append(queryVars, "pos" + "=" + q_pos) }
			return execRaw(cmd, "PUT", "/members/{id}/savedSearches/{idSearch}", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_name, "name", "", "The new name for the saved search")
	cmd.Flags().StringVar(&q_query, "query", "", "The new search query")
	cmd.Flags().StringVar(&q_pos, "pos", "", "New position for saves search. `top`, `bottom`, or a positive float.")
	return cmd
}

