// Code generated by tools/cmdgen. DO NOT EDIT.

package auto

import "github.com/spf13/cobra"

func GroupNotifications() *cobra.Command {
	cmd := &cobra.Command{Use: "notifications", Short: "Auto-generated commands for notifications"}
	cmd.AddCommand(cmdGetNotificationsId())
	cmd.AddCommand(cmdGetNotificationsIdBoard())
	cmd.AddCommand(cmdGetNotificationsIdCard())
	cmd.AddCommand(cmdGetNotificationsIdField())
	cmd.AddCommand(cmdGetNotificationsIdList())
	cmd.AddCommand(cmdGetNotificationsIdMembercreator())
	cmd.AddCommand(cmdGetNotificationsIdOrganization())
	cmd.AddCommand(cmdNotificationsidmember())
	cmd.AddCommand(cmdPostNotificationsAllRead())
	cmd.AddCommand(cmdPutNotificationsId())
	cmd.AddCommand(cmdPutNotificationsIdUnread())
	return cmd
}

func cmdGetNotificationsId() *cobra.Command {
	var (
		q_board string
		q_boardfields string
		q_card string
		q_cardfields string
		q_display string
		q_entities string
		q_fields string
		q_list string
		q_member string
		q_memberfields string
		q_memberCreator string
		q_memberCreatorfields string
		q_organization string
		q_organizationfields string
	)
	cmd := &cobra.Command{
		Use:   "get-notifications-id <id>",
		Short: "Get a Notification",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_board != "" { queryVars = append(queryVars, "board" + "=" + q_board) }
			if q_boardfields != "" { queryVars = append(queryVars, "board_fields" + "=" + q_boardfields) }
			if q_card != "" { queryVars = append(queryVars, "card" + "=" + q_card) }
			if q_cardfields != "" { queryVars = append(queryVars, "card_fields" + "=" + q_cardfields) }
			if q_display != "" { queryVars = append(queryVars, "display" + "=" + q_display) }
			if q_entities != "" { queryVars = append(queryVars, "entities" + "=" + q_entities) }
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			if q_list != "" { queryVars = append(queryVars, "list" + "=" + q_list) }
			if q_member != "" { queryVars = append(queryVars, "member" + "=" + q_member) }
			if q_memberfields != "" { queryVars = append(queryVars, "member_fields" + "=" + q_memberfields) }
			if q_memberCreator != "" { queryVars = append(queryVars, "memberCreator" + "=" + q_memberCreator) }
			if q_memberCreatorfields != "" { queryVars = append(queryVars, "memberCreator_fields" + "=" + q_memberCreatorfields) }
			if q_organization != "" { queryVars = append(queryVars, "organization" + "=" + q_organization) }
			if q_organizationfields != "" { queryVars = append(queryVars, "organization_fields" + "=" + q_organizationfields) }
			return execRaw(cmd, "GET", "/notifications/{id}", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_board, "board", "", "Whether to include the board object")
	cmd.Flags().StringVar(&q_boardfields, "board_fields", "", "`all` or a comma-separated list of board [fields](/cloud/trello/guides/rest-a...")
	cmd.Flags().StringVar(&q_card, "card", "", "Whether to include the card object")
	cmd.Flags().StringVar(&q_cardfields, "card_fields", "", "`all` or a comma-separated list of card [fields](/cloud/trello/guides/rest-ap...")
	cmd.Flags().StringVar(&q_display, "display", "", "Whether to include the display object with the results")
	cmd.Flags().StringVar(&q_entities, "entities", "", "Whether to include the entities object with the results")
	cmd.Flags().StringVar(&q_fields, "fields", "", "`all` or a comma-separated list of notification [fields](/cloud/trello/guides...")
	cmd.Flags().StringVar(&q_list, "list", "", "Whether to include the list object")
	cmd.Flags().StringVar(&q_member, "member", "", "Whether to include the member object")
	cmd.Flags().StringVar(&q_memberfields, "member_fields", "", "`all` or a comma-separated list of member [fields](/cloud/trello/guides/rest-...")
	cmd.Flags().StringVar(&q_memberCreator, "memberCreator", "", "Whether to include the member object of the creator")
	cmd.Flags().StringVar(&q_memberCreatorfields, "memberCreator_fields", "", "`all` or a comma-separated list of member [fields](/cloud/trello/guides/rest-...")
	cmd.Flags().StringVar(&q_organization, "organization", "", "Whether to include the organization object")
	cmd.Flags().StringVar(&q_organizationfields, "organization_fields", "", "`all` or a comma-separated list of organization [fields](/cloud/trello/guides...")
	return cmd
}

func cmdGetNotificationsIdBoard() *cobra.Command {
	var (
		q_fields string
	)
	cmd := &cobra.Command{
		Use:   "get-notifications-id-board <id>",
		Short: "Get the Board a Notification is on",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			return execRaw(cmd, "GET", "/notifications/{id}/board", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_fields, "fields", "", "`all` or a comma-separated list of board[fields](/cloud/trello/guides/rest-ap...")
	return cmd
}

func cmdGetNotificationsIdCard() *cobra.Command {
	var (
		q_fields string
	)
	cmd := &cobra.Command{
		Use:   "get-notifications-id-card <id>",
		Short: "Get the Card a Notification is on",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			return execRaw(cmd, "GET", "/notifications/{id}/card", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_fields, "fields", "", "`all` or a comma-separated list of card [fields](/cloud/trello/guides/rest-ap...")
	return cmd
}

func cmdGetNotificationsIdField() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "get-notifications-id-field <id> <field>",
		Short: "Get a field of a Notification",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"field" + "=" + args[1],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/notifications/{id}/{field}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetNotificationsIdList() *cobra.Command {
	var (
		q_fields string
	)
	cmd := &cobra.Command{
		Use:   "get-notifications-id-list <id>",
		Short: "Get the List a Notification is on",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			return execRaw(cmd, "GET", "/notifications/{id}/list", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_fields, "fields", "", "`all` or a comma-separated list of list [fields](/cloud/trello/guides/rest-ap...")
	return cmd
}

func cmdGetNotificationsIdMembercreator() *cobra.Command {
	var (
		q_fields string
	)
	cmd := &cobra.Command{
		Use:   "get-notifications-id-membercreator <id>",
		Short: "Get the Member who created the Notification",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			return execRaw(cmd, "GET", "/notifications/{id}/memberCreator", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_fields, "fields", "", "`all` or a comma-separated list of member [fields](/cloud/trello/guides/rest-...")
	return cmd
}

func cmdGetNotificationsIdOrganization() *cobra.Command {
	var (
		q_fields string
	)
	cmd := &cobra.Command{
		Use:   "get-notifications-id-organization <id>",
		Short: "Get a Notification's associated Organization",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			return execRaw(cmd, "GET", "/notifications/{id}/organization", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_fields, "fields", "", "`all` or a comma-separated list of organization [fields](/cloud/trello/guides...")
	return cmd
}

func cmdNotificationsidmember() *cobra.Command {
	var (
		q_fields string
	)
	cmd := &cobra.Command{
		Use:   "notificationsidmember <id>",
		Short: "Get the Member a Notification is about (not the creator)",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			return execRaw(cmd, "GET", "/notifications/{id}/member", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_fields, "fields", "", "`all` or a comma-separated list of member [fields](/cloud/trello/guides/rest-...")
	return cmd
}

func cmdPostNotificationsAllRead() *cobra.Command {
	var (
		q_read string
		q_ids string
	)
	cmd := &cobra.Command{
		Use:   "post-notifications-all-read",
		Short: "Mark all Notifications as read",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
			}
			queryVars := []string{}
			if q_read != "" { queryVars = append(queryVars, "read" + "=" + q_read) }
			if q_ids != "" { queryVars = append(queryVars, "ids" + "=" + q_ids) }
			return execRaw(cmd, "POST", "/notifications/all/read", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_read, "read", "", "Boolean to specify whether to mark as read or unread (defaults to `true`, mar...")
	cmd.Flags().StringVar(&q_ids, "ids", "", "A comma-seperated list of IDs. Allows specifying an array of notification IDs...")
	return cmd
}

func cmdPutNotificationsId() *cobra.Command {
	var (
		q_unread string
	)
	cmd := &cobra.Command{
		Use:   "put-notifications-id <id>",
		Short: "Update a Notification's read status",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_unread != "" { queryVars = append(queryVars, "unread" + "=" + q_unread) }
			return execRaw(cmd, "PUT", "/notifications/{id}", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_unread, "unread", "", "Whether the notification should be marked as read or not")
	return cmd
}

func cmdPutNotificationsIdUnread() *cobra.Command {
	var (
		q_value string
	)
	cmd := &cobra.Command{
		Use:   "put-notifications-id-unread <id>",
		Short: "Update Notification's read status",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_value != "" { queryVars = append(queryVars, "value" + "=" + q_value) }
			return execRaw(cmd, "PUT", "/notifications/{id}/unread", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_value, "value", "", "")
	return cmd
}

