// Code generated by tools/cmdgen. DO NOT EDIT.

package auto

import "github.com/spf13/cobra"

func GroupOrganizations() *cobra.Command {
	cmd := &cobra.Command{Use: "organizations", Short: "Auto-generated commands for organizations"}
	cmd.AddCommand(cmdDeleteOrganizationsId())
	cmd.AddCommand(cmdDeleteOrganizationsIdLogo())
	cmd.AddCommand(cmdDeleteOrganizationsIdMembers())
	cmd.AddCommand(cmdDeleteOrganizationsIdPrefsAssociateddomain())
	cmd.AddCommand(cmdDeleteOrganizationsIdPrefsOrginviterestrict())
	cmd.AddCommand(cmdDeleteOrganizationsIdTagsIdtag())
	cmd.AddCommand(cmdGetOrganizationsId())
	cmd.AddCommand(cmdGetOrganizationsIdActions())
	cmd.AddCommand(cmdGetOrganizationsIdBoards())
	cmd.AddCommand(cmdGetOrganizationsIdExports())
	cmd.AddCommand(cmdGetOrganizationsIdField())
	cmd.AddCommand(cmdGetOrganizationsIdMembers())
	cmd.AddCommand(cmdGetOrganizationsIdMemberships())
	cmd.AddCommand(cmdGetOrganizationsIdMembershipsIdmembership())
	cmd.AddCommand(cmdGetOrganizationsIdNewbillableguestsIdboard())
	cmd.AddCommand(cmdGetOrganizationsIdPlugindata())
	cmd.AddCommand(cmdGetOrganizationsIdTags())
	cmd.AddCommand(cmdOrganizationsIdMembersIdmemberAll())
	cmd.AddCommand(cmdPostOrganizations())
	cmd.AddCommand(cmdPostOrganizationsIdExports())
	cmd.AddCommand(cmdPostOrganizationsIdLogo())
	cmd.AddCommand(cmdPostOrganizationsIdTags())
	cmd.AddCommand(cmdPutOrganizationsId())
	cmd.AddCommand(cmdPutOrganizationsIdMembers())
	cmd.AddCommand(cmdPutOrganizationsIdMembersIdmember())
	cmd.AddCommand(cmdPutOrganizationsIdMembersIdmemberDeactivated())
	return cmd
}

func cmdDeleteOrganizationsId() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "delete-organizations-id <id>",
		Short: "Delete an Organization",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "DELETE", "/organizations/{id}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdDeleteOrganizationsIdLogo() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "delete-organizations-id-logo <id>",
		Short: "Delete Logo for Organization",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "DELETE", "/organizations/{id}/logo", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdDeleteOrganizationsIdMembers() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "delete-organizations-id-members <id> <idMember>",
		Short: "Remove a Member from an Organization",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idMember" + "=" + args[1],
			}
			queryVars := []string{}
			return execRaw(cmd, "DELETE", "/organizations/{id}/members/{idMember}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdDeleteOrganizationsIdPrefsAssociateddomain() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "delete-organizations-id-prefs-associateddomain <id>",
		Short: "Remove the associated Google Apps domain from a Workspace",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "DELETE", "/organizations/{id}/prefs/associatedDomain", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdDeleteOrganizationsIdPrefsOrginviterestrict() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "delete-organizations-id-prefs-orginviterestrict <id>",
		Short: "Delete the email domain restriction on who can be invited to the Workspace",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "DELETE", "/organizations/{id}/prefs/orgInviteRestrict", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdDeleteOrganizationsIdTagsIdtag() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "delete-organizations-id-tags-idtag <id> <idTag>",
		Short: "Delete an Organization's Tag",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idTag" + "=" + args[1],
			}
			queryVars := []string{}
			return execRaw(cmd, "DELETE", "/organizations/{id}/tags/{idTag}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetOrganizationsId() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "get-organizations-id <id>",
		Short: "Get an Organization",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/organizations/{id}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetOrganizationsIdActions() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "get-organizations-id-actions <id>",
		Short: "Get Actions for Organization",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/organizations/{id}/actions", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetOrganizationsIdBoards() *cobra.Command {
	var (
		q_filter string
		q_fields string
	)
	cmd := &cobra.Command{
		Use:   "get-organizations-id-boards <id>",
		Short: "Get Boards in an Organization",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_filter != "" { queryVars = append(queryVars, "filter" + "=" + q_filter) }
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			return execRaw(cmd, "GET", "/organizations/{id}/boards", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_filter, "filter", "", "`all` or a comma-separated list of: `open`, `closed`, `members`, `organizatio...")
	cmd.Flags().StringVar(&q_fields, "fields", "", "`all` or a comma-separated list of board [fields](/cloud/trello/guides/rest-a...")
	return cmd
}

func cmdGetOrganizationsIdExports() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "get-organizations-id-exports <id>",
		Short: "Retrieve Organization's Exports",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/organizations/{id}/exports", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetOrganizationsIdField() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "get-organizations-id-field <id> <field>",
		Short: "Get field on Organization",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"field" + "=" + args[1],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/organizations/{id}/{field}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetOrganizationsIdMembers() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "get-organizations-id-members <id>",
		Short: "Get the Members of an Organization",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/organizations/{id}/members", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetOrganizationsIdMemberships() *cobra.Command {
	var (
		q_filter string
		q_member string
	)
	cmd := &cobra.Command{
		Use:   "get-organizations-id-memberships <id>",
		Short: "Get Memberships of an Organization",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_filter != "" { queryVars = append(queryVars, "filter" + "=" + q_filter) }
			if q_member != "" { queryVars = append(queryVars, "member" + "=" + q_member) }
			return execRaw(cmd, "GET", "/organizations/{id}/memberships", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_filter, "filter", "", "`all` or a comma-separated list of: `active`, `admin`, `deactivated`, `me`, `...")
	cmd.Flags().StringVar(&q_member, "member", "", "Whether to include the Member objects with the Memberships")
	return cmd
}

func cmdGetOrganizationsIdMembershipsIdmembership() *cobra.Command {
	var (
		q_member string
	)
	cmd := &cobra.Command{
		Use:   "get-organizations-id-memberships-idmembership <id> <idMembership>",
		Short: "Get a Membership of an Organization",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idMembership" + "=" + args[1],
			}
			queryVars := []string{}
			if q_member != "" { queryVars = append(queryVars, "member" + "=" + q_member) }
			return execRaw(cmd, "GET", "/organizations/{id}/memberships/{idMembership}", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_member, "member", "", "Whether to include the Member object in the response")
	return cmd
}

func cmdGetOrganizationsIdNewbillableguestsIdboard() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "get-organizations-id-newbillableguests-idboard <id> <idBoard>",
		Short: "Get Organizations new billable guests",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idBoard" + "=" + args[1],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/organizations/{id}/newBillableGuests/{idBoard}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetOrganizationsIdPlugindata() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "get-organizations-id-plugindata <id>",
		Short: "Get the pluginData Scoped to Organization",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/organizations/{id}/pluginData", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetOrganizationsIdTags() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "get-organizations-id-tags <id>",
		Short: "Get Tags of an Organization",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/organizations/{id}/tags", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdOrganizationsIdMembersIdmemberAll() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "organizations-id-members-idmember-all <id> <idMember>",
		Short: "Remove a Member from an Organization and all Organization Boards",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idMember" + "=" + args[1],
			}
			queryVars := []string{}
			return execRaw(cmd, "DELETE", "/organizations/{id}/members/{idMember}/all", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdPostOrganizations() *cobra.Command {
	var (
		q_displayName string
		q_desc string
		q_name string
		q_website string
	)
	cmd := &cobra.Command{
		Use:   "post-organizations",
		Short: "Create a new Organization",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
			}
			queryVars := []string{}
			if q_displayName != "" { queryVars = append(queryVars, "displayName" + "=" + q_displayName) }
			if q_desc != "" { queryVars = append(queryVars, "desc" + "=" + q_desc) }
			if q_name != "" { queryVars = append(queryVars, "name" + "=" + q_name) }
			if q_website != "" { queryVars = append(queryVars, "website" + "=" + q_website) }
			return execRaw(cmd, "POST", "/organizations", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_displayName, "displayName", "", "The name to display for the Organization")
	cmd.Flags().StringVar(&q_desc, "desc", "", "The description for the organizations")
	cmd.Flags().StringVar(&q_name, "name", "", "A string with a length of at least 3. Only lowercase letters, underscores, an...")
	cmd.Flags().StringVar(&q_website, "website", "", "A URL starting with `http://` or `https://`")
	return cmd
}

func cmdPostOrganizationsIdExports() *cobra.Command {
	var (
		q_attachments string
	)
	cmd := &cobra.Command{
		Use:   "post-organizations-id-exports <id>",
		Short: "Create Export for Organizations",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_attachments != "" { queryVars = append(queryVars, "attachments" + "=" + q_attachments) }
			return execRaw(cmd, "POST", "/organizations/{id}/exports", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_attachments, "attachments", "", "Whether the CSV should include attachments or not.")
	return cmd
}

func cmdPostOrganizationsIdLogo() *cobra.Command {
	var (
		q_file string
	)
	cmd := &cobra.Command{
		Use:   "post-organizations-id-logo <id>",
		Short: "Update logo for an Organization",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_file != "" { queryVars = append(queryVars, "file" + "=" + q_file) }
			return execRaw(cmd, "POST", "/organizations/{id}/logo", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_file, "file", "", "Image file for the logo")
	return cmd
}

func cmdPostOrganizationsIdTags() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "post-organizations-id-tags <id>",
		Short: "Create a Tag in Organization",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "POST", "/organizations/{id}/tags", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdPutOrganizationsId() *cobra.Command {
	var (
		q_name string
		q_displayName string
		q_desc string
		q_website string
		q_prefsassociatedDomain string
		q_prefsexternalMembersDisabled string
		q_prefsgoogleAppsVersion string
		q_prefsboardVisibilityRestrictorg string
		q_prefsboardVisibilityRestrictprivate string
		q_prefsboardVisibilityRestrictpublic string
		q_prefsorgInviteRestrict string
		q_prefspermissionLevel string
	)
	cmd := &cobra.Command{
		Use:   "put-organizations-id <id>",
		Short: "Update an Organization",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_name != "" { queryVars = append(queryVars, "name" + "=" + q_name) }
			if q_displayName != "" { queryVars = append(queryVars, "displayName" + "=" + q_displayName) }
			if q_desc != "" { queryVars = append(queryVars, "desc" + "=" + q_desc) }
			if q_website != "" { queryVars = append(queryVars, "website" + "=" + q_website) }
			if q_prefsassociatedDomain != "" { queryVars = append(queryVars, "prefs/associatedDomain" + "=" + q_prefsassociatedDomain) }
			if q_prefsexternalMembersDisabled != "" { queryVars = append(queryVars, "prefs/externalMembersDisabled" + "=" + q_prefsexternalMembersDisabled) }
			if q_prefsgoogleAppsVersion != "" { queryVars = append(queryVars, "prefs/googleAppsVersion" + "=" + q_prefsgoogleAppsVersion) }
			if q_prefsboardVisibilityRestrictorg != "" { queryVars = append(queryVars, "prefs/boardVisibilityRestrict/org" + "=" + q_prefsboardVisibilityRestrictorg) }
			if q_prefsboardVisibilityRestrictprivate != "" { queryVars = append(queryVars, "prefs/boardVisibilityRestrict/private" + "=" + q_prefsboardVisibilityRestrictprivate) }
			if q_prefsboardVisibilityRestrictpublic != "" { queryVars = append(queryVars, "prefs/boardVisibilityRestrict/public" + "=" + q_prefsboardVisibilityRestrictpublic) }
			if q_prefsorgInviteRestrict != "" { queryVars = append(queryVars, "prefs/orgInviteRestrict" + "=" + q_prefsorgInviteRestrict) }
			if q_prefspermissionLevel != "" { queryVars = append(queryVars, "prefs/permissionLevel" + "=" + q_prefspermissionLevel) }
			return execRaw(cmd, "PUT", "/organizations/{id}", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_name, "name", "", "A new name for the organization. At least 3 lowercase letters, underscores, a...")
	cmd.Flags().StringVar(&q_displayName, "displayName", "", "A new displayName for the organization. Must be at least 1 character long and...")
	cmd.Flags().StringVar(&q_desc, "desc", "", "A new description for the organization")
	cmd.Flags().StringVar(&q_website, "website", "", "A URL starting with `http://`, `https://`, or `null`")
	cmd.Flags().StringVar(&q_prefsassociatedDomain, "prefs/associatedDomain", "", "The Google Apps domain to link this org to.")
	cmd.Flags().StringVar(&q_prefsexternalMembersDisabled, "prefs/externalMembersDisabled", "", "Whether non-workspace members can be added to boards inside the Workspace")
	cmd.Flags().StringVar(&q_prefsgoogleAppsVersion, "prefs/googleAppsVersion", "", "`1` or `2`")
	cmd.Flags().StringVar(&q_prefsboardVisibilityRestrictorg, "prefs/boardVisibilityRestrict/org", "", "Who on the Workspace can make Workspace visible boards. One of `admin`, `none...")
	cmd.Flags().StringVar(&q_prefsboardVisibilityRestrictprivate, "prefs/boardVisibilityRestrict/private", "", "Who can make private boards. One of: `admin`, `none`, `org`")
	cmd.Flags().StringVar(&q_prefsboardVisibilityRestrictpublic, "prefs/boardVisibilityRestrict/public", "", "Who on the Workspace can make public boards. One of: `admin`, `none`, `org`")
	cmd.Flags().StringVar(&q_prefsorgInviteRestrict, "prefs/orgInviteRestrict", "", "An email address with optional wildcard characters. (E.g. `subdomain.*.trello...")
	cmd.Flags().StringVar(&q_prefspermissionLevel, "prefs/permissionLevel", "", "Whether the Workspace page is publicly visible. One of: `private`, `public`")
	return cmd
}

func cmdPutOrganizationsIdMembers() *cobra.Command {
	var (
		q_email string
		q_fullName string
		q_type string
	)
	cmd := &cobra.Command{
		Use:   "put-organizations-id-members <id>",
		Short: "Update an Organization's Members",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_email != "" { queryVars = append(queryVars, "email" + "=" + q_email) }
			if q_fullName != "" { queryVars = append(queryVars, "fullName" + "=" + q_fullName) }
			if q_type != "" { queryVars = append(queryVars, "type" + "=" + q_type) }
			return execRaw(cmd, "PUT", "/organizations/{id}/members", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_email, "email", "", "An email address")
	cmd.Flags().StringVar(&q_fullName, "fullName", "", "Name for the member, at least 1 character not beginning or ending with a space")
	cmd.Flags().StringVar(&q_type, "type", "", "One of: `admin`, `normal`")
	return cmd
}

func cmdPutOrganizationsIdMembersIdmember() *cobra.Command {
	var (
		q_type string
	)
	cmd := &cobra.Command{
		Use:   "put-organizations-id-members-idmember <id> <idMember>",
		Short: "Update a Member of an Organization",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idMember" + "=" + args[1],
			}
			queryVars := []string{}
			if q_type != "" { queryVars = append(queryVars, "type" + "=" + q_type) }
			return execRaw(cmd, "PUT", "/organizations/{id}/members/{idMember}", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_type, "type", "", "One of: `admin`, `normal`")
	return cmd
}

func cmdPutOrganizationsIdMembersIdmemberDeactivated() *cobra.Command {
	var (
		q_value string
	)
	cmd := &cobra.Command{
		Use:   "put-organizations-id-members-idmember-deactivated <id> <idMember>",
		Short: "Deactivate or reactivate a member of an Organization",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"idMember" + "=" + args[1],
			}
			queryVars := []string{}
			if q_value != "" { queryVars = append(queryVars, "value" + "=" + q_value) }
			return execRaw(cmd, "PUT", "/organizations/{id}/members/{idMember}/deactivated", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_value, "value", "", "")
	return cmd
}

