// Code generated by tools/cmdgen. DO NOT EDIT.

package auto

import "github.com/spf13/cobra"

func GroupPlugins() *cobra.Command {
	cmd := &cobra.Command{Use: "plugins", Short: "Auto-generated commands for plugins"}
	cmd.AddCommand(cmdGetPluginsId())
	cmd.AddCommand(cmdGetPluginsIdComplianceMemberprivacy())
	cmd.AddCommand(cmdPostPluginsIdpluginListing())
	cmd.AddCommand(cmdPutPluginsId())
	cmd.AddCommand(cmdPutPluginsIdpluginListingsIdlisting())
	return cmd
}

func cmdGetPluginsId() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "get-plugins-id <id>",
		Short: "Get a Plugin",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/plugins/{id}/", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetPluginsIdComplianceMemberprivacy() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "get-plugins-id-compliance-memberprivacy <id>",
		Short: "Get Plugin's Member privacy compliance",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/plugins/{id}/compliance/memberPrivacy", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdPostPluginsIdpluginListing() *cobra.Command {
	var (
		dataArg string
	)
	cmd := &cobra.Command{
		Use:   "post-plugins-idplugin-listing <idPlugin>",
		Short: "Create a Listing for Plugin",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"idPlugin" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "POST", "/plugins/{idPlugin}/listing", pathVars, queryVars, dataArg)
		},
	}
	cmd.Flags().StringVar(&dataArg, "data", "", "Request body: literal JSON or @file")
	return cmd
}

func cmdPutPluginsId() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "put-plugins-id <id>",
		Short: "Update a Plugin",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "PUT", "/plugins/{id}/", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdPutPluginsIdpluginListingsIdlisting() *cobra.Command {
	var (
		dataArg string
	)
	cmd := &cobra.Command{
		Use:   "put-plugins-idplugin-listings-idlisting <idPlugin> <idListing>",
		Short: "Updating Plugin's Listing",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"idPlugin" + "=" + args[0],
				"idListing" + "=" + args[1],
			}
			queryVars := []string{}
			return execRaw(cmd, "PUT", "/plugins/{idPlugin}/listings/{idListing}", pathVars, queryVars, dataArg)
		},
	}
	cmd.Flags().StringVar(&dataArg, "data", "", "Request body: literal JSON or @file")
	return cmd
}

