// Code generated by tools/cmdgen. DO NOT EDIT.

package auto

import "github.com/spf13/cobra"

func GroupSearch() *cobra.Command {
	cmd := &cobra.Command{Use: "search", Short: "Auto-generated commands for search"}
	cmd.AddCommand(cmdGetSearch())
	cmd.AddCommand(cmdGetSearchMembers())
	return cmd
}

func cmdGetSearch() *cobra.Command {
	var (
		q_query string
		q_idBoards string
		q_idOrganizations string
		q_idCards string
		q_modelTypes string
		q_boardfields string
		q_boardslimit string
		q_boardorganization string
		q_cardfields string
		q_cardslimit string
		q_cardspage string
		q_cardboard string
		q_cardlist string
		q_cardmembers string
		q_cardstickers string
		q_cardattachments string
		q_organizationfields string
		q_organizationslimit string
		q_memberfields string
		q_memberslimit string
		q_partial string
	)
	cmd := &cobra.Command{
		Use:   "get-search",
		Short: "Search Trello",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
			}
			queryVars := []string{}
			if q_query != "" { queryVars = append(queryVars, "query" + "=" + q_query) }
			if q_idBoards != "" { queryVars = append(queryVars, "idBoards" + "=" + q_idBoards) }
			if q_idOrganizations != "" { queryVars = append(queryVars, "idOrganizations" + "=" + q_idOrganizations) }
			if q_idCards != "" { queryVars = append(queryVars, "idCards" + "=" + q_idCards) }
			if q_modelTypes != "" { queryVars = append(queryVars, "modelTypes" + "=" + q_modelTypes) }
			if q_boardfields != "" { queryVars = append(queryVars, "board_fields" + "=" + q_boardfields) }
			if q_boardslimit != "" { queryVars = append(queryVars, "boards_limit" + "=" + q_boardslimit) }
			if q_boardorganization != "" { queryVars = append(queryVars, "board_organization" + "=" + q_boardorganization) }
			if q_cardfields != "" { queryVars = append(queryVars, "card_fields" + "=" + q_cardfields) }
			if q_cardslimit != "" { queryVars = append(queryVars, "cards_limit" + "=" + q_cardslimit) }
			if q_cardspage != "" { queryVars = append(queryVars, "cards_page" + "=" + q_cardspage) }
			if q_cardboard != "" { queryVars = append(queryVars, "card_board" + "=" + q_cardboard) }
			if q_cardlist != "" { queryVars = append(queryVars, "card_list" + "=" + q_cardlist) }
			if q_cardmembers != "" { queryVars = append(queryVars, "card_members" + "=" + q_cardmembers) }
			if q_cardstickers != "" { queryVars = append(queryVars, "card_stickers" + "=" + q_cardstickers) }
			if q_cardattachments != "" { queryVars = append(queryVars, "card_attachments" + "=" + q_cardattachments) }
			if q_organizationfields != "" { queryVars = append(queryVars, "organization_fields" + "=" + q_organizationfields) }
			if q_organizationslimit != "" { queryVars = append(queryVars, "organizations_limit" + "=" + q_organizationslimit) }
			if q_memberfields != "" { queryVars = append(queryVars, "member_fields" + "=" + q_memberfields) }
			if q_memberslimit != "" { queryVars = append(queryVars, "members_limit" + "=" + q_memberslimit) }
			if q_partial != "" { queryVars = append(queryVars, "partial" + "=" + q_partial) }
			return execRaw(cmd, "GET", "/search", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_query, "query", "", "The search query with a length of 1 to 16384 characters")
	cmd.Flags().StringVar(&q_idBoards, "idBoards", "", "`mine` or a comma-separated list of Board IDs")
	cmd.Flags().StringVar(&q_idOrganizations, "idOrganizations", "", "A comma-separated list of Organization IDs")
	cmd.Flags().StringVar(&q_idCards, "idCards", "", "A comma-separated list of Card IDs")
	cmd.Flags().StringVar(&q_modelTypes, "modelTypes", "", "What type or types of Trello objects you want to search. all or a comma-separ...")
	cmd.Flags().StringVar(&q_boardfields, "board_fields", "", "all or a comma-separated list of: `closed`, `dateLastActivity`, `dateLastView...")
	cmd.Flags().StringVar(&q_boardslimit, "boards_limit", "", "The maximum number of boards returned. Maximum: 1000")
	cmd.Flags().StringVar(&q_boardorganization, "board_organization", "", "Whether to include the parent organization with board results")
	cmd.Flags().StringVar(&q_cardfields, "card_fields", "", "all or a comma-separated list of: `badges`, `checkItemStates`, `closed`, `dat...")
	cmd.Flags().StringVar(&q_cardslimit, "cards_limit", "", "The maximum number of cards to return. Maximum: 1000")
	cmd.Flags().StringVar(&q_cardspage, "cards_page", "", "The page of results for cards. Maximum: 100")
	cmd.Flags().StringVar(&q_cardboard, "card_board", "", "Whether to include the parent board with card results")
	cmd.Flags().StringVar(&q_cardlist, "card_list", "", "Whether to include the parent list with card results")
	cmd.Flags().StringVar(&q_cardmembers, "card_members", "", "Whether to include member objects with card results")
	cmd.Flags().StringVar(&q_cardstickers, "card_stickers", "", "Whether to include sticker objects with card results")
	cmd.Flags().StringVar(&q_cardattachments, "card_attachments", "", "Whether to include attachment objects with card results. A boolean value (tru...")
	cmd.Flags().StringVar(&q_organizationfields, "organization_fields", "", "all or a comma-separated list of billableMemberCount, desc, descData, display...")
	cmd.Flags().StringVar(&q_organizationslimit, "organizations_limit", "", "The maximum number of Workspaces to return. Maximum 1000")
	cmd.Flags().StringVar(&q_memberfields, "member_fields", "", "all or a comma-separated list of: avatarHash, bio, bioData, confirmed, fullNa...")
	cmd.Flags().StringVar(&q_memberslimit, "members_limit", "", "The maximum number of members to return. Maximum 1000")
	cmd.Flags().StringVar(&q_partial, "partial", "", "By default, Trello searches for each word in your query against exactly match...")
	return cmd
}

func cmdGetSearchMembers() *cobra.Command {
	var (
		q_query string
		q_limit string
		q_idBoard string
		q_idOrganization string
		q_onlyOrgMembers string
	)
	cmd := &cobra.Command{
		Use:   "get-search-members",
		Short: "Search for Members",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
			}
			queryVars := []string{}
			if q_query != "" { queryVars = append(queryVars, "query" + "=" + q_query) }
			if q_limit != "" { queryVars = append(queryVars, "limit" + "=" + q_limit) }
			if q_idBoard != "" { queryVars = append(queryVars, "idBoard" + "=" + q_idBoard) }
			if q_idOrganization != "" { queryVars = append(queryVars, "idOrganization" + "=" + q_idOrganization) }
			if q_onlyOrgMembers != "" { queryVars = append(queryVars, "onlyOrgMembers" + "=" + q_onlyOrgMembers) }
			return execRaw(cmd, "GET", "/search/members/", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_query, "query", "", "Search query 1 to 16384 characters long")
	cmd.Flags().StringVar(&q_limit, "limit", "", "The maximum number of results to return. Maximum of 20.")
	cmd.Flags().StringVar(&q_idBoard, "idBoard", "", "")
	cmd.Flags().StringVar(&q_idOrganization, "idOrganization", "", "")
	cmd.Flags().StringVar(&q_onlyOrgMembers, "onlyOrgMembers", "", "")
	return cmd
}

