// Code generated by tools/cmdgen. DO NOT EDIT.

package auto

import "github.com/spf13/cobra"

func GroupTokens() *cobra.Command {
	cmd := &cobra.Command{Use: "tokens", Short: "Auto-generated commands for tokens"}
	cmd.AddCommand(cmdDeleteToken())
	cmd.AddCommand(cmdDeleteTokensTokenWebhooksIdwebhook())
	cmd.AddCommand(cmdGetTokensToken())
	cmd.AddCommand(cmdGetTokensTokenMember())
	cmd.AddCommand(cmdGetTokensTokenWebhooks())
	cmd.AddCommand(cmdGetTokensTokenWebhooksIdwebhook())
	cmd.AddCommand(cmdPostTokensTokenWebhooks())
	cmd.AddCommand(cmdTokenstokenwebhooks1())
	return cmd
}

func cmdDeleteToken() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "delete-token <token>",
		Short: "Delete a Token",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"token" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "DELETE", "/tokens/{token}/", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdDeleteTokensTokenWebhooksIdwebhook() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "delete-tokens-token-webhooks-idwebhook <token> <idWebhook>",
		Short: "Delete a Webhook created by Token",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"token" + "=" + args[0],
				"idWebhook" + "=" + args[1],
			}
			queryVars := []string{}
			return execRaw(cmd, "DELETE", "/tokens/{token}/webhooks/{idWebhook}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetTokensToken() *cobra.Command {
	var (
		q_fields string
		q_webhooks string
	)
	cmd := &cobra.Command{
		Use:   "get-tokens-token <token>",
		Short: "Get a Token",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"token" + "=" + args[0],
			}
			queryVars := []string{}
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			if q_webhooks != "" { queryVars = append(queryVars, "webhooks" + "=" + q_webhooks) }
			return execRaw(cmd, "GET", "/tokens/{token}", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_fields, "fields", "", "`all` or a comma-separated list of `dateCreated`, `dateExpires`, `idMember`, ...")
	cmd.Flags().StringVar(&q_webhooks, "webhooks", "", "Determines whether to include webhooks.")
	return cmd
}

func cmdGetTokensTokenMember() *cobra.Command {
	var (
		q_fields string
	)
	cmd := &cobra.Command{
		Use:   "get-tokens-token-member <token>",
		Short: "Get Token's Member",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"token" + "=" + args[0],
			}
			queryVars := []string{}
			if q_fields != "" { queryVars = append(queryVars, "fields" + "=" + q_fields) }
			return execRaw(cmd, "GET", "/tokens/{token}/member", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_fields, "fields", "", "`all` or a comma-separated list of valid fields for [Member Object](/cloud/tr...")
	return cmd
}

func cmdGetTokensTokenWebhooks() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "get-tokens-token-webhooks <token>",
		Short: "Get Webhooks for Token",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"token" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/tokens/{token}/webhooks", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetTokensTokenWebhooksIdwebhook() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "get-tokens-token-webhooks-idwebhook <token> <idWebhook>",
		Short: "Get a Webhook belonging to a Token",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"token" + "=" + args[0],
				"idWebhook" + "=" + args[1],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/tokens/{token}/webhooks/{idWebhook}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdPostTokensTokenWebhooks() *cobra.Command {
	var (
		q_description string
		q_callbackURL string
		q_idModel string
	)
	cmd := &cobra.Command{
		Use:   "post-tokens-token-webhooks <token>",
		Short: "Create Webhooks for Token",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"token" + "=" + args[0],
			}
			queryVars := []string{}
			if q_description != "" { queryVars = append(queryVars, "description" + "=" + q_description) }
			if q_callbackURL != "" { queryVars = append(queryVars, "callbackURL" + "=" + q_callbackURL) }
			if q_idModel != "" { queryVars = append(queryVars, "idModel" + "=" + q_idModel) }
			return execRaw(cmd, "POST", "/tokens/{token}/webhooks", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_description, "description", "", "A description to be displayed when retrieving information about the webhook.")
	cmd.Flags().StringVar(&q_callbackURL, "callbackURL", "", "The URL that the webhook should POST information to.")
	cmd.Flags().StringVar(&q_idModel, "idModel", "", "ID of the object to create a webhook on.")
	return cmd
}

func cmdTokenstokenwebhooks1() *cobra.Command {
	var (
		q_description string
		q_callbackURL string
		q_idModel string
	)
	cmd := &cobra.Command{
		Use:   "tokenstokenwebhooks-1 <token> <idWebhook>",
		Short: "Update a Webhook created by Token",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"token" + "=" + args[0],
				"idWebhook" + "=" + args[1],
			}
			queryVars := []string{}
			if q_description != "" { queryVars = append(queryVars, "description" + "=" + q_description) }
			if q_callbackURL != "" { queryVars = append(queryVars, "callbackURL" + "=" + q_callbackURL) }
			if q_idModel != "" { queryVars = append(queryVars, "idModel" + "=" + q_idModel) }
			return execRaw(cmd, "PUT", "/tokens/{token}/webhooks/{idWebhook}", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_description, "description", "", "A description to be displayed when retrieving information about the webhook.")
	cmd.Flags().StringVar(&q_callbackURL, "callbackURL", "", "The URL that the webhook should `POST` information to.")
	cmd.Flags().StringVar(&q_idModel, "idModel", "", "ID of the object that the webhook is on.")
	return cmd
}

