// Code generated by tools/cmdgen. DO NOT EDIT.

package auto

import "github.com/spf13/cobra"

func GroupWebhooks() *cobra.Command {
	cmd := &cobra.Command{Use: "webhooks", Short: "Auto-generated commands for webhooks"}
	cmd.AddCommand(cmdDeleteWebhooksId())
	cmd.AddCommand(cmdGetWebhooksId())
	cmd.AddCommand(cmdPostWebhooks())
	cmd.AddCommand(cmdPutWebhooksId())
	cmd.AddCommand(cmdWebhooksidfield())
	return cmd
}

func cmdDeleteWebhooksId() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "delete-webhooks-id <id>",
		Short: "Delete a Webhook",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "DELETE", "/webhooks/{id}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdGetWebhooksId() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "get-webhooks-id <id>",
		Short: "Get a Webhook",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/webhooks/{id}", pathVars, queryVars, "")
		},
	}
	return cmd
}

func cmdPostWebhooks() *cobra.Command {
	var (
		q_description string
		q_callbackURL string
		q_idModel string
		q_active string
	)
	cmd := &cobra.Command{
		Use:   "post-webhooks",
		Short: "Create a Webhook",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
			}
			queryVars := []string{}
			if q_description != "" { queryVars = append(queryVars, "description" + "=" + q_description) }
			if q_callbackURL != "" { queryVars = append(queryVars, "callbackURL" + "=" + q_callbackURL) }
			if q_idModel != "" { queryVars = append(queryVars, "idModel" + "=" + q_idModel) }
			if q_active != "" { queryVars = append(queryVars, "active" + "=" + q_active) }
			return execRaw(cmd, "POST", "/webhooks/", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_description, "description", "", "A string with a length from `0` to `16384`.")
	cmd.Flags().StringVar(&q_callbackURL, "callbackURL", "", "A valid URL that is reachable with a `HEAD` and `POST` request.")
	cmd.Flags().StringVar(&q_idModel, "idModel", "", "ID of the model to be monitored")
	cmd.Flags().StringVar(&q_active, "active", "", "Determines whether the webhook is active and sending `POST` requests.")
	return cmd
}

func cmdPutWebhooksId() *cobra.Command {
	var (
		q_description string
		q_callbackURL string
		q_idModel string
		q_active string
	)
	cmd := &cobra.Command{
		Use:   "put-webhooks-id <id>",
		Short: "Update a Webhook",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
			}
			queryVars := []string{}
			if q_description != "" { queryVars = append(queryVars, "description" + "=" + q_description) }
			if q_callbackURL != "" { queryVars = append(queryVars, "callbackURL" + "=" + q_callbackURL) }
			if q_idModel != "" { queryVars = append(queryVars, "idModel" + "=" + q_idModel) }
			if q_active != "" { queryVars = append(queryVars, "active" + "=" + q_active) }
			return execRaw(cmd, "PUT", "/webhooks/{id}", pathVars, queryVars, "")
		},
	}
	cmd.Flags().StringVar(&q_description, "description", "", "A string with a length from `0` to `16384`.")
	cmd.Flags().StringVar(&q_callbackURL, "callbackURL", "", "A valid URL that is reachable with a `HEAD` and `POST` request.")
	cmd.Flags().StringVar(&q_idModel, "idModel", "", "ID of the model to be monitored")
	cmd.Flags().StringVar(&q_active, "active", "", "Determines whether the webhook is active and sending `POST` requests.")
	return cmd
}

func cmdWebhooksidfield() *cobra.Command {
	var (
	)
	cmd := &cobra.Command{
		Use:   "webhooksidfield <id> <field>",
		Short: "Get a field on a Webhook",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			pathVars := []string{
				"id" + "=" + args[0],
				"field" + "=" + args[1],
			}
			queryVars := []string{}
			return execRaw(cmd, "GET", "/webhooks/{id}/{field}", pathVars, queryVars, "")
		},
	}
	return cmd
}

